// Code generated by novaerp.com, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccountLogin is the predicate function for accountlogin builders.
type AccountLogin func(*sql.Selector)

// UserAccount is the predicate function for useraccount builders.
type UserAccount func(*sql.Selector)
