// Code generated by novaerp.com, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"vn.vato.zora.be.api/apps/zalo/internal/data/ent/ticket"
	"vn.vato.zora.be.api/apps/zalo/internal/data/ent/ticketseat"
	"vn.vato.zora.be.api/apps/zalo/internal/data/ent_schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	ticketMixin := ent_schema.Ticket{}.Mixin()
	ticketMixinFields0 := ticketMixin[0].Fields()
	_ = ticketMixinFields0
	ticketMixinFields1 := ticketMixin[1].Fields()
	_ = ticketMixinFields1
	ticketMixinFields2 := ticketMixin[2].Fields()
	_ = ticketMixinFields2
	ticketFields := ent_schema.Ticket{}.Fields()
	_ = ticketFields
	// ticketDescCreatedAt is the schema descriptor for created_at field.
	ticketDescCreatedAt := ticketMixinFields1[0].Descriptor()
	// ticket.DefaultCreatedAt holds the default value on creation for the created_at field.
	ticket.DefaultCreatedAt = ticketDescCreatedAt.Default.(func() time.Time)
	// ticketDescUpdatedAt is the schema descriptor for updated_at field.
	ticketDescUpdatedAt := ticketMixinFields1[1].Descriptor()
	// ticket.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ticket.DefaultUpdatedAt = ticketDescUpdatedAt.Default.(func() time.Time)
	// ticket.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ticket.UpdateDefaultUpdatedAt = ticketDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ticketDescTenantID is the schema descriptor for tenant_id field.
	ticketDescTenantID := ticketMixinFields2[0].Descriptor()
	// ticket.DefaultTenantID holds the default value on creation for the tenant_id field.
	ticket.DefaultTenantID = ticketDescTenantID.Default.(func() uuid.UUID)
	// ticketDescCode is the schema descriptor for code field.
	ticketDescCode := ticketFields[0].Descriptor()
	// ticket.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	ticket.CodeValidator = func() func(string) error {
		validators := ticketDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// ticketDescPaymentMethod is the schema descriptor for payment_method field.
	ticketDescPaymentMethod := ticketFields[4].Descriptor()
	// ticket.DefaultPaymentMethod holds the default value on creation for the payment_method field.
	ticket.DefaultPaymentMethod = ticketDescPaymentMethod.Default.(int)
	// ticketDescIsActive is the schema descriptor for is_active field.
	ticketDescIsActive := ticketFields[5].Descriptor()
	// ticket.DefaultIsActive holds the default value on creation for the is_active field.
	ticket.DefaultIsActive = ticketDescIsActive.Default.(bool)
	// ticketDescDepartureTimes is the schema descriptor for departure_times field.
	ticketDescDepartureTimes := ticketFields[7].Descriptor()
	// ticket.DefaultDepartureTimes holds the default value on creation for the departure_times field.
	ticket.DefaultDepartureTimes = ticketDescDepartureTimes.Default.([]string)
	// ticketDescOriginAmount is the schema descriptor for origin_amount field.
	ticketDescOriginAmount := ticketFields[8].Descriptor()
	// ticket.DefaultOriginAmount holds the default value on creation for the origin_amount field.
	ticket.DefaultOriginAmount = ticketDescOriginAmount.Default.(float64)
	// ticket.OriginAmountValidator is a validator for the "origin_amount" field. It is called by the builders before save.
	ticket.OriginAmountValidator = ticketDescOriginAmount.Validators[0].(func(float64) error)
	// ticketDescDiscountAmount is the schema descriptor for discount_amount field.
	ticketDescDiscountAmount := ticketFields[9].Descriptor()
	// ticket.DefaultDiscountAmount holds the default value on creation for the discount_amount field.
	ticket.DefaultDiscountAmount = ticketDescDiscountAmount.Default.(float64)
	// ticket.DiscountAmountValidator is a validator for the "discount_amount" field. It is called by the builders before save.
	ticket.DiscountAmountValidator = ticketDescDiscountAmount.Validators[0].(func(float64) error)
	// ticketDescRefundAmount is the schema descriptor for refund_amount field.
	ticketDescRefundAmount := ticketFields[10].Descriptor()
	// ticket.DefaultRefundAmount holds the default value on creation for the refund_amount field.
	ticket.DefaultRefundAmount = ticketDescRefundAmount.Default.(float64)
	// ticket.RefundAmountValidator is a validator for the "refund_amount" field. It is called by the builders before save.
	ticket.RefundAmountValidator = ticketDescRefundAmount.Validators[0].(func(float64) error)
	// ticketDescReferenceUserID is the schema descriptor for reference_user_id field.
	ticketDescReferenceUserID := ticketFields[12].Descriptor()
	// ticket.ReferenceUserIDValidator is a validator for the "reference_user_id" field. It is called by the builders before save.
	ticket.ReferenceUserIDValidator = ticketDescReferenceUserID.Validators[0].(func(string) error)
	// ticketDescID is the schema descriptor for id field.
	ticketDescID := ticketMixinFields0[0].Descriptor()
	// ticket.DefaultID holds the default value on creation for the id field.
	ticket.DefaultID = ticketDescID.Default.(func() uuid.UUID)
	ticketseatMixin := ent_schema.TicketSeat{}.Mixin()
	ticketseatMixinFields0 := ticketseatMixin[0].Fields()
	_ = ticketseatMixinFields0
	ticketseatMixinFields1 := ticketseatMixin[1].Fields()
	_ = ticketseatMixinFields1
	ticketseatFields := ent_schema.TicketSeat{}.Fields()
	_ = ticketseatFields
	// ticketseatDescCreatedAt is the schema descriptor for created_at field.
	ticketseatDescCreatedAt := ticketseatMixinFields1[0].Descriptor()
	// ticketseat.DefaultCreatedAt holds the default value on creation for the created_at field.
	ticketseat.DefaultCreatedAt = ticketseatDescCreatedAt.Default.(func() time.Time)
	// ticketseatDescUpdatedAt is the schema descriptor for updated_at field.
	ticketseatDescUpdatedAt := ticketseatMixinFields1[1].Descriptor()
	// ticketseat.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ticketseat.DefaultUpdatedAt = ticketseatDescUpdatedAt.Default.(func() time.Time)
	// ticketseat.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ticketseat.UpdateDefaultUpdatedAt = ticketseatDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ticketseatDescRouteID is the schema descriptor for route_id field.
	ticketseatDescRouteID := ticketseatFields[1].Descriptor()
	// ticketseat.RouteIDValidator is a validator for the "route_id" field. It is called by the builders before save.
	ticketseat.RouteIDValidator = func() func(string) error {
		validators := ticketseatDescRouteID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(route_id string) error {
			for _, fn := range fns {
				if err := fn(route_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// ticketseatDescRouteName is the schema descriptor for route_name field.
	ticketseatDescRouteName := ticketseatFields[3].Descriptor()
	// ticketseat.RouteNameValidator is a validator for the "route_name" field. It is called by the builders before save.
	ticketseat.RouteNameValidator = ticketseatDescRouteName.Validators[0].(func(string) error)
	// ticketseatDescTripID is the schema descriptor for trip_id field.
	ticketseatDescTripID := ticketseatFields[5].Descriptor()
	// ticketseat.TripIDValidator is a validator for the "trip_id" field. It is called by the builders before save.
	ticketseat.TripIDValidator = ticketseatDescTripID.Validators[0].(func(string) error)
	// ticketseatDescSeatID is the schema descriptor for seat_id field.
	ticketseatDescSeatID := ticketseatFields[6].Descriptor()
	// ticketseat.SeatIDValidator is a validator for the "seat_id" field. It is called by the builders before save.
	ticketseat.SeatIDValidator = func() func(string) error {
		validators := ticketseatDescSeatID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(seat_id string) error {
			for _, fn := range fns {
				if err := fn(seat_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// ticketseatDescSeatName is the schema descriptor for seat_name field.
	ticketseatDescSeatName := ticketseatFields[7].Descriptor()
	// ticketseat.SeatNameValidator is a validator for the "seat_name" field. It is called by the builders before save.
	ticketseat.SeatNameValidator = ticketseatDescSeatName.Validators[0].(func(string) error)
	// ticketseatDescOriginAmount is the schema descriptor for origin_amount field.
	ticketseatDescOriginAmount := ticketseatFields[9].Descriptor()
	// ticketseat.DefaultOriginAmount holds the default value on creation for the origin_amount field.
	ticketseat.DefaultOriginAmount = ticketseatDescOriginAmount.Default.(float64)
	// ticketseat.OriginAmountValidator is a validator for the "origin_amount" field. It is called by the builders before save.
	ticketseat.OriginAmountValidator = ticketseatDescOriginAmount.Validators[0].(func(float64) error)
	// ticketseatDescDiscountAmount is the schema descriptor for discount_amount field.
	ticketseatDescDiscountAmount := ticketseatFields[10].Descriptor()
	// ticketseat.DefaultDiscountAmount holds the default value on creation for the discount_amount field.
	ticketseat.DefaultDiscountAmount = ticketseatDescDiscountAmount.Default.(float64)
	// ticketseat.DiscountAmountValidator is a validator for the "discount_amount" field. It is called by the builders before save.
	ticketseat.DiscountAmountValidator = ticketseatDescDiscountAmount.Validators[0].(func(float64) error)
	// ticketseatDescRefundAmount is the schema descriptor for refund_amount field.
	ticketseatDescRefundAmount := ticketseatFields[11].Descriptor()
	// ticketseat.DefaultRefundAmount holds the default value on creation for the refund_amount field.
	ticketseat.DefaultRefundAmount = ticketseatDescRefundAmount.Default.(float64)
	// ticketseat.RefundAmountValidator is a validator for the "refund_amount" field. It is called by the builders before save.
	ticketseat.RefundAmountValidator = ticketseatDescRefundAmount.Validators[0].(func(float64) error)
	// ticketseatDescKind is the schema descriptor for kind field.
	ticketseatDescKind := ticketseatFields[16].Descriptor()
	// ticketseat.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	ticketseat.KindValidator = ticketseatDescKind.Validators[0].(func(string) error)
	// ticketseatDescOriginCode is the schema descriptor for origin_code field.
	ticketseatDescOriginCode := ticketseatFields[17].Descriptor()
	// ticketseat.OriginCodeValidator is a validator for the "origin_code" field. It is called by the builders before save.
	ticketseat.OriginCodeValidator = ticketseatDescOriginCode.Validators[0].(func(string) error)
	// ticketseatDescDestCode is the schema descriptor for dest_code field.
	ticketseatDescDestCode := ticketseatFields[19].Descriptor()
	// ticketseat.DestCodeValidator is a validator for the "dest_code" field. It is called by the builders before save.
	ticketseat.DestCodeValidator = ticketseatDescDestCode.Validators[0].(func(string) error)
	// ticketseatDescWayID is the schema descriptor for way_id field.
	ticketseatDescWayID := ticketseatFields[23].Descriptor()
	// ticketseat.WayIDValidator is a validator for the "way_id" field. It is called by the builders before save.
	ticketseat.WayIDValidator = ticketseatDescWayID.Validators[0].(func(string) error)
	// ticketseatDescPickupID is the schema descriptor for pickup_id field.
	ticketseatDescPickupID := ticketseatFields[26].Descriptor()
	// ticketseat.PickupIDValidator is a validator for the "pickup_id" field. It is called by the builders before save.
	ticketseat.PickupIDValidator = ticketseatDescPickupID.Validators[0].(func(string) error)
	// ticketseatDescPickupInfo is the schema descriptor for pickup_info field.
	ticketseatDescPickupInfo := ticketseatFields[29].Descriptor()
	// ticketseat.DefaultPickupInfo holds the default value on creation for the pickup_info field.
	ticketseat.DefaultPickupInfo = ticketseatDescPickupInfo.Default.(map[string]interface{})
	// ticketseatDescDropOffID is the schema descriptor for drop_off_id field.
	ticketseatDescDropOffID := ticketseatFields[31].Descriptor()
	// ticketseat.DropOffIDValidator is a validator for the "drop_off_id" field. It is called by the builders before save.
	ticketseat.DropOffIDValidator = ticketseatDescDropOffID.Validators[0].(func(string) error)
	// ticketseatDescDropOffInfo is the schema descriptor for drop_off_info field.
	ticketseatDescDropOffInfo := ticketseatFields[34].Descriptor()
	// ticketseat.DefaultDropOffInfo holds the default value on creation for the drop_off_info field.
	ticketseat.DefaultDropOffInfo = ticketseatDescDropOffInfo.Default.(map[string]interface{})
	// ticketseatDescExtraData is the schema descriptor for extra_data field.
	ticketseatDescExtraData := ticketseatFields[35].Descriptor()
	// ticketseat.DefaultExtraData holds the default value on creation for the extra_data field.
	ticketseat.DefaultExtraData = ticketseatDescExtraData.Default.(map[string]interface{})
	// ticketseatDescID is the schema descriptor for id field.
	ticketseatDescID := ticketseatMixinFields0[0].Descriptor()
	// ticketseat.DefaultID holds the default value on creation for the id field.
	ticketseat.DefaultID = ticketseatDescID.Default.(func() uuid.UUID)
}
