// Code generated by novaerp.com, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"vn.vato.zora.be.api/apps/zalo/internal/data/ent/ticket"
	"vn.vato.zora.be.api/apps/zalo/internal/data/ent/ticketseat"
)

// TicketSeat is the model entity for the TicketSeat schema.
type TicketSeat struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key
	ID uuid.UUID `json:"id,omitempty"`
	// Record creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Record last update timestamp
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TicketID holds the value of the "ticket_id" field.
	TicketID uuid.UUID `json:"ticket_id,omitempty"`
	// RouteID holds the value of the "route_id" field.
	RouteID string `json:"route_id,omitempty"`
	// SeatType holds the value of the "seat_type" field.
	SeatType ticketseat.SeatType `json:"seat_type,omitempty"`
	// RouteName holds the value of the "route_name" field.
	RouteName string `json:"route_name,omitempty"`
	// Scheduled departure time for the ticket
	DepartureTime time.Time `json:"departure_time,omitempty"`
	// TripID holds the value of the "trip_id" field.
	TripID *string `json:"trip_id,omitempty"`
	// SeatID holds the value of the "seat_id" field.
	SeatID string `json:"seat_id,omitempty"`
	// SeatName holds the value of the "seat_name" field.
	SeatName string `json:"seat_name,omitempty"`
	// Status holds the value of the "status" field.
	Status ticketseat.Status `json:"status,omitempty"`
	// Origin amount for the ticket
	OriginAmount float64 `json:"origin_amount,omitempty"`
	// Discount amount applied to the ticket
	DiscountAmount float64 `json:"discount_amount,omitempty"`
	// Refund amount for the ticket
	RefundAmount float64 `json:"refund_amount,omitempty"`
	// Timestamp when the ticket was paid
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// Timestamp when the ticket was exported
	ExportedAt *time.Time `json:"exported_at,omitempty"`
	// Timestamp when the ticket was cancelled
	CancelledAt *time.Time `json:"cancelled_at,omitempty"`
	// Timestamp when the ticket was refunded
	RefundedAt *time.Time `json:"refunded_at,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind *string `json:"kind,omitempty"`
	// OriginCode holds the value of the "origin_code" field.
	OriginCode *string `json:"origin_code,omitempty"`
	// OriginName holds the value of the "origin_name" field.
	OriginName *string `json:"origin_name,omitempty"`
	// DestCode holds the value of the "dest_code" field.
	DestCode *string `json:"dest_code,omitempty"`
	// DestName holds the value of the "dest_name" field.
	DestName *string `json:"dest_name,omitempty"`
	// DistanceKm holds the value of the "distance_km" field.
	DistanceKm *float64 `json:"distance_km,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs *int64 `json:"duration_ms,omitempty"`
	// WayID holds the value of the "way_id" field.
	WayID *string `json:"way_id,omitempty"`
	// WayName holds the value of the "way_name" field.
	WayName *string `json:"way_name,omitempty"`
	// PickupType holds the value of the "pickup_type" field.
	PickupType *ticketseat.PickupType `json:"pickup_type,omitempty"`
	// PickupID holds the value of the "pickup_id" field.
	PickupID *string `json:"pickup_id,omitempty"`
	// PickupName holds the value of the "pickup_name" field.
	PickupName *string `json:"pickup_name,omitempty"`
	// PickupAddress holds the value of the "pickup_address" field.
	PickupAddress *string `json:"pickup_address,omitempty"`
	// PickupInfo holds the value of the "pickup_info" field.
	PickupInfo map[string]interface{} `json:"pickup_info,omitempty"`
	// DropOffType holds the value of the "drop_off_type" field.
	DropOffType *ticketseat.DropOffType `json:"drop_off_type,omitempty"`
	// DropOffID holds the value of the "drop_off_id" field.
	DropOffID *string `json:"drop_off_id,omitempty"`
	// DropOffName holds the value of the "drop_off_name" field.
	DropOffName *string `json:"drop_off_name,omitempty"`
	// DropOffAddress holds the value of the "drop_off_address" field.
	DropOffAddress *string `json:"drop_off_address,omitempty"`
	// DropOffInfo holds the value of the "drop_off_info" field.
	DropOffInfo map[string]interface{} `json:"drop_off_info,omitempty"`
	// ExtraData holds the value of the "extra_data" field.
	ExtraData map[string]interface{} `json:"extra_data,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TicketSeatQuery when eager-loading is set.
	Edges        TicketSeatEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TicketSeatEdges holds the relations/edges for other nodes in the graph.
type TicketSeatEdges struct {
	// Ticket holds the value of the ticket edge.
	Ticket *Ticket `json:"ticket,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TicketOrErr returns the Ticket value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketSeatEdges) TicketOrErr() (*Ticket, error) {
	if e.Ticket != nil {
		return e.Ticket, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: ticket.Label}
	}
	return nil, &NotLoadedError{edge: "ticket"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TicketSeat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ticketseat.FieldPickupInfo, ticketseat.FieldDropOffInfo, ticketseat.FieldExtraData:
			values[i] = new([]byte)
		case ticketseat.FieldOriginAmount, ticketseat.FieldDiscountAmount, ticketseat.FieldRefundAmount, ticketseat.FieldDistanceKm:
			values[i] = new(sql.NullFloat64)
		case ticketseat.FieldDurationMs:
			values[i] = new(sql.NullInt64)
		case ticketseat.FieldRouteID, ticketseat.FieldSeatType, ticketseat.FieldRouteName, ticketseat.FieldTripID, ticketseat.FieldSeatID, ticketseat.FieldSeatName, ticketseat.FieldStatus, ticketseat.FieldKind, ticketseat.FieldOriginCode, ticketseat.FieldOriginName, ticketseat.FieldDestCode, ticketseat.FieldDestName, ticketseat.FieldWayID, ticketseat.FieldWayName, ticketseat.FieldPickupType, ticketseat.FieldPickupID, ticketseat.FieldPickupName, ticketseat.FieldPickupAddress, ticketseat.FieldDropOffType, ticketseat.FieldDropOffID, ticketseat.FieldDropOffName, ticketseat.FieldDropOffAddress:
			values[i] = new(sql.NullString)
		case ticketseat.FieldCreatedAt, ticketseat.FieldUpdatedAt, ticketseat.FieldDepartureTime, ticketseat.FieldPaidAt, ticketseat.FieldExportedAt, ticketseat.FieldCancelledAt, ticketseat.FieldRefundedAt:
			values[i] = new(sql.NullTime)
		case ticketseat.FieldID, ticketseat.FieldTicketID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TicketSeat fields.
func (_m *TicketSeat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ticketseat.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case ticketseat.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ticketseat.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ticketseat.FieldTicketID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_id", values[i])
			} else if value != nil {
				_m.TicketID = *value
			}
		case ticketseat.FieldRouteID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field route_id", values[i])
			} else if value.Valid {
				_m.RouteID = value.String
			}
		case ticketseat.FieldSeatType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field seat_type", values[i])
			} else if value.Valid {
				_m.SeatType = ticketseat.SeatType(value.String)
			}
		case ticketseat.FieldRouteName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field route_name", values[i])
			} else if value.Valid {
				_m.RouteName = value.String
			}
		case ticketseat.FieldDepartureTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field departure_time", values[i])
			} else if value.Valid {
				_m.DepartureTime = value.Time
			}
		case ticketseat.FieldTripID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trip_id", values[i])
			} else if value.Valid {
				_m.TripID = new(string)
				*_m.TripID = value.String
			}
		case ticketseat.FieldSeatID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field seat_id", values[i])
			} else if value.Valid {
				_m.SeatID = value.String
			}
		case ticketseat.FieldSeatName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field seat_name", values[i])
			} else if value.Valid {
				_m.SeatName = value.String
			}
		case ticketseat.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = ticketseat.Status(value.String)
			}
		case ticketseat.FieldOriginAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field origin_amount", values[i])
			} else if value.Valid {
				_m.OriginAmount = value.Float64
			}
		case ticketseat.FieldDiscountAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field discount_amount", values[i])
			} else if value.Valid {
				_m.DiscountAmount = value.Float64
			}
		case ticketseat.FieldRefundAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field refund_amount", values[i])
			} else if value.Valid {
				_m.RefundAmount = value.Float64
			}
		case ticketseat.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case ticketseat.FieldExportedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field exported_at", values[i])
			} else if value.Valid {
				_m.ExportedAt = new(time.Time)
				*_m.ExportedAt = value.Time
			}
		case ticketseat.FieldCancelledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cancelled_at", values[i])
			} else if value.Valid {
				_m.CancelledAt = new(time.Time)
				*_m.CancelledAt = value.Time
			}
		case ticketseat.FieldRefundedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field refunded_at", values[i])
			} else if value.Valid {
				_m.RefundedAt = new(time.Time)
				*_m.RefundedAt = value.Time
			}
		case ticketseat.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = new(string)
				*_m.Kind = value.String
			}
		case ticketseat.FieldOriginCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field origin_code", values[i])
			} else if value.Valid {
				_m.OriginCode = new(string)
				*_m.OriginCode = value.String
			}
		case ticketseat.FieldOriginName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field origin_name", values[i])
			} else if value.Valid {
				_m.OriginName = new(string)
				*_m.OriginName = value.String
			}
		case ticketseat.FieldDestCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dest_code", values[i])
			} else if value.Valid {
				_m.DestCode = new(string)
				*_m.DestCode = value.String
			}
		case ticketseat.FieldDestName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dest_name", values[i])
			} else if value.Valid {
				_m.DestName = new(string)
				*_m.DestName = value.String
			}
		case ticketseat.FieldDistanceKm:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field distance_km", values[i])
			} else if value.Valid {
				_m.DistanceKm = new(float64)
				*_m.DistanceKm = value.Float64
			}
		case ticketseat.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = new(int64)
				*_m.DurationMs = value.Int64
			}
		case ticketseat.FieldWayID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field way_id", values[i])
			} else if value.Valid {
				_m.WayID = new(string)
				*_m.WayID = value.String
			}
		case ticketseat.FieldWayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field way_name", values[i])
			} else if value.Valid {
				_m.WayName = new(string)
				*_m.WayName = value.String
			}
		case ticketseat.FieldPickupType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pickup_type", values[i])
			} else if value.Valid {
				_m.PickupType = new(ticketseat.PickupType)
				*_m.PickupType = ticketseat.PickupType(value.String)
			}
		case ticketseat.FieldPickupID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pickup_id", values[i])
			} else if value.Valid {
				_m.PickupID = new(string)
				*_m.PickupID = value.String
			}
		case ticketseat.FieldPickupName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pickup_name", values[i])
			} else if value.Valid {
				_m.PickupName = new(string)
				*_m.PickupName = value.String
			}
		case ticketseat.FieldPickupAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pickup_address", values[i])
			} else if value.Valid {
				_m.PickupAddress = new(string)
				*_m.PickupAddress = value.String
			}
		case ticketseat.FieldPickupInfo:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field pickup_info", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PickupInfo); err != nil {
					return fmt.Errorf("unmarshal field pickup_info: %w", err)
				}
			}
		case ticketseat.FieldDropOffType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field drop_off_type", values[i])
			} else if value.Valid {
				_m.DropOffType = new(ticketseat.DropOffType)
				*_m.DropOffType = ticketseat.DropOffType(value.String)
			}
		case ticketseat.FieldDropOffID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field drop_off_id", values[i])
			} else if value.Valid {
				_m.DropOffID = new(string)
				*_m.DropOffID = value.String
			}
		case ticketseat.FieldDropOffName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field drop_off_name", values[i])
			} else if value.Valid {
				_m.DropOffName = new(string)
				*_m.DropOffName = value.String
			}
		case ticketseat.FieldDropOffAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field drop_off_address", values[i])
			} else if value.Valid {
				_m.DropOffAddress = new(string)
				*_m.DropOffAddress = value.String
			}
		case ticketseat.FieldDropOffInfo:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field drop_off_info", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DropOffInfo); err != nil {
					return fmt.Errorf("unmarshal field drop_off_info: %w", err)
				}
			}
		case ticketseat.FieldExtraData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field extra_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExtraData); err != nil {
					return fmt.Errorf("unmarshal field extra_data: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TicketSeat.
// This includes values selected through modifiers, order, etc.
func (_m *TicketSeat) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTicket queries the "ticket" edge of the TicketSeat entity.
func (_m *TicketSeat) QueryTicket() *TicketQuery {
	return NewTicketSeatClient(_m.config).QueryTicket(_m)
}

// Update returns a builder for updating this TicketSeat.
// Note that you need to call TicketSeat.Unwrap() before calling this method if this TicketSeat
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TicketSeat) Update() *TicketSeatUpdateOne {
	return NewTicketSeatClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TicketSeat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TicketSeat) Unwrap() *TicketSeat {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TicketSeat is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TicketSeat) String() string {
	var builder strings.Builder
	builder.WriteString("TicketSeat(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("ticket_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TicketID))
	builder.WriteString(", ")
	builder.WriteString("route_id=")
	builder.WriteString(_m.RouteID)
	builder.WriteString(", ")
	builder.WriteString("seat_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.SeatType))
	builder.WriteString(", ")
	builder.WriteString("route_name=")
	builder.WriteString(_m.RouteName)
	builder.WriteString(", ")
	builder.WriteString("departure_time=")
	builder.WriteString(_m.DepartureTime.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.TripID; v != nil {
		builder.WriteString("trip_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("seat_id=")
	builder.WriteString(_m.SeatID)
	builder.WriteString(", ")
	builder.WriteString("seat_name=")
	builder.WriteString(_m.SeatName)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("origin_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.OriginAmount))
	builder.WriteString(", ")
	builder.WriteString("discount_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiscountAmount))
	builder.WriteString(", ")
	builder.WriteString("refund_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundAmount))
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExportedAt; v != nil {
		builder.WriteString("exported_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CancelledAt; v != nil {
		builder.WriteString("cancelled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RefundedAt; v != nil {
		builder.WriteString("refunded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Kind; v != nil {
		builder.WriteString("kind=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OriginCode; v != nil {
		builder.WriteString("origin_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OriginName; v != nil {
		builder.WriteString("origin_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DestCode; v != nil {
		builder.WriteString("dest_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DestName; v != nil {
		builder.WriteString("dest_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DistanceKm; v != nil {
		builder.WriteString("distance_km=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DurationMs; v != nil {
		builder.WriteString("duration_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.WayID; v != nil {
		builder.WriteString("way_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.WayName; v != nil {
		builder.WriteString("way_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PickupType; v != nil {
		builder.WriteString("pickup_type=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PickupID; v != nil {
		builder.WriteString("pickup_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PickupName; v != nil {
		builder.WriteString("pickup_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PickupAddress; v != nil {
		builder.WriteString("pickup_address=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("pickup_info=")
	builder.WriteString(fmt.Sprintf("%v", _m.PickupInfo))
	builder.WriteString(", ")
	if v := _m.DropOffType; v != nil {
		builder.WriteString("drop_off_type=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DropOffID; v != nil {
		builder.WriteString("drop_off_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DropOffName; v != nil {
		builder.WriteString("drop_off_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DropOffAddress; v != nil {
		builder.WriteString("drop_off_address=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("drop_off_info=")
	builder.WriteString(fmt.Sprintf("%v", _m.DropOffInfo))
	builder.WriteString(", ")
	builder.WriteString("extra_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExtraData))
	builder.WriteByte(')')
	return builder.String()
}

// TicketSeats is a parsable slice of TicketSeat.
type TicketSeats []*TicketSeat
