// Code generated by novaerp.com, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"vn.vato.zora.be.api/apps/zalo/internal/data/ent/ticket"
	"vn.vato.zora.be.api/apps/zalo/internal/data/ent/ticketseat"
)

// TicketCreate is the builder for creating a Ticket entity.
type TicketCreate struct {
	config
	mutation *TicketMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TicketCreate) SetCreatedAt(v time.Time) *TicketCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TicketCreate) SetNillableCreatedAt(v *time.Time) *TicketCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TicketCreate) SetUpdatedAt(v time.Time) *TicketCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TicketCreate) SetNillableUpdatedAt(v *time.Time) *TicketCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *TicketCreate) SetTenantID(v uuid.UUID) *TicketCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *TicketCreate) SetNillableTenantID(v *uuid.UUID) *TicketCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *TicketCreate) SetCode(v string) *TicketCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TicketCreate) SetStatus(v ticket.Status) *TicketCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TicketCreate) SetNillableStatus(v *ticket.Status) *TicketCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetWayType sets the "way_type" field.
func (_c *TicketCreate) SetWayType(v ticket.WayType) *TicketCreate {
	_c.mutation.SetWayType(v)
	return _c
}

// SetNillableWayType sets the "way_type" field if the given value is not nil.
func (_c *TicketCreate) SetNillableWayType(v *ticket.WayType) *TicketCreate {
	if v != nil {
		_c.SetWayType(*v)
	}
	return _c
}

// SetBookingChannel sets the "booking_channel" field.
func (_c *TicketCreate) SetBookingChannel(v ticket.BookingChannel) *TicketCreate {
	_c.mutation.SetBookingChannel(v)
	return _c
}

// SetNillableBookingChannel sets the "booking_channel" field if the given value is not nil.
func (_c *TicketCreate) SetNillableBookingChannel(v *ticket.BookingChannel) *TicketCreate {
	if v != nil {
		_c.SetBookingChannel(*v)
	}
	return _c
}

// SetPaymentMethod sets the "payment_method" field.
func (_c *TicketCreate) SetPaymentMethod(v int) *TicketCreate {
	_c.mutation.SetPaymentMethod(v)
	return _c
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_c *TicketCreate) SetNillablePaymentMethod(v *int) *TicketCreate {
	if v != nil {
		_c.SetPaymentMethod(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *TicketCreate) SetIsActive(v bool) *TicketCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *TicketCreate) SetNillableIsActive(v *bool) *TicketCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetPromotionCode sets the "promotion_code" field.
func (_c *TicketCreate) SetPromotionCode(v string) *TicketCreate {
	_c.mutation.SetPromotionCode(v)
	return _c
}

// SetNillablePromotionCode sets the "promotion_code" field if the given value is not nil.
func (_c *TicketCreate) SetNillablePromotionCode(v *string) *TicketCreate {
	if v != nil {
		_c.SetPromotionCode(*v)
	}
	return _c
}

// SetDepartureTimes sets the "departure_times" field.
func (_c *TicketCreate) SetDepartureTimes(v []string) *TicketCreate {
	_c.mutation.SetDepartureTimes(v)
	return _c
}

// SetOriginAmount sets the "origin_amount" field.
func (_c *TicketCreate) SetOriginAmount(v float64) *TicketCreate {
	_c.mutation.SetOriginAmount(v)
	return _c
}

// SetNillableOriginAmount sets the "origin_amount" field if the given value is not nil.
func (_c *TicketCreate) SetNillableOriginAmount(v *float64) *TicketCreate {
	if v != nil {
		_c.SetOriginAmount(*v)
	}
	return _c
}

// SetDiscountAmount sets the "discount_amount" field.
func (_c *TicketCreate) SetDiscountAmount(v float64) *TicketCreate {
	_c.mutation.SetDiscountAmount(v)
	return _c
}

// SetNillableDiscountAmount sets the "discount_amount" field if the given value is not nil.
func (_c *TicketCreate) SetNillableDiscountAmount(v *float64) *TicketCreate {
	if v != nil {
		_c.SetDiscountAmount(*v)
	}
	return _c
}

// SetRefundAmount sets the "refund_amount" field.
func (_c *TicketCreate) SetRefundAmount(v float64) *TicketCreate {
	_c.mutation.SetRefundAmount(v)
	return _c
}

// SetNillableRefundAmount sets the "refund_amount" field if the given value is not nil.
func (_c *TicketCreate) SetNillableRefundAmount(v *float64) *TicketCreate {
	if v != nil {
		_c.SetRefundAmount(*v)
	}
	return _c
}

// SetRemarks sets the "remarks" field.
func (_c *TicketCreate) SetRemarks(v string) *TicketCreate {
	_c.mutation.SetRemarks(v)
	return _c
}

// SetNillableRemarks sets the "remarks" field if the given value is not nil.
func (_c *TicketCreate) SetNillableRemarks(v *string) *TicketCreate {
	if v != nil {
		_c.SetRemarks(*v)
	}
	return _c
}

// SetReferenceUserID sets the "reference_user_id" field.
func (_c *TicketCreate) SetReferenceUserID(v string) *TicketCreate {
	_c.mutation.SetReferenceUserID(v)
	return _c
}

// SetReferencePhone sets the "reference_phone" field.
func (_c *TicketCreate) SetReferencePhone(v string) *TicketCreate {
	_c.mutation.SetReferencePhone(v)
	return _c
}

// SetReferenceMigrationID sets the "reference_migration_id" field.
func (_c *TicketCreate) SetReferenceMigrationID(v string) *TicketCreate {
	_c.mutation.SetReferenceMigrationID(v)
	return _c
}

// SetNillableReferenceMigrationID sets the "reference_migration_id" field if the given value is not nil.
func (_c *TicketCreate) SetNillableReferenceMigrationID(v *string) *TicketCreate {
	if v != nil {
		_c.SetReferenceMigrationID(*v)
	}
	return _c
}

// SetForceUpdatedUserID sets the "force_updated_user_id" field.
func (_c *TicketCreate) SetForceUpdatedUserID(v string) *TicketCreate {
	_c.mutation.SetForceUpdatedUserID(v)
	return _c
}

// SetNillableForceUpdatedUserID sets the "force_updated_user_id" field if the given value is not nil.
func (_c *TicketCreate) SetNillableForceUpdatedUserID(v *string) *TicketCreate {
	if v != nil {
		_c.SetForceUpdatedUserID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TicketCreate) SetID(v uuid.UUID) *TicketCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TicketCreate) SetNillableID(v *uuid.UUID) *TicketCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddTicketSeatIDs adds the "ticketSeats" edge to the TicketSeat entity by IDs.
func (_c *TicketCreate) AddTicketSeatIDs(ids ...uuid.UUID) *TicketCreate {
	_c.mutation.AddTicketSeatIDs(ids...)
	return _c
}

// AddTicketSeats adds the "ticketSeats" edges to the TicketSeat entity.
func (_c *TicketCreate) AddTicketSeats(v ...*TicketSeat) *TicketCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTicketSeatIDs(ids...)
}

// Mutation returns the TicketMutation object of the builder.
func (_c *TicketCreate) Mutation() *TicketMutation {
	return _c.mutation
}

// Save creates the Ticket in the database.
func (_c *TicketCreate) Save(ctx context.Context) (*Ticket, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TicketCreate) SaveX(ctx context.Context) *Ticket {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TicketCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ticket.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ticket.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := ticket.DefaultTenantID()
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := ticket.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.WayType(); !ok {
		v := ticket.DefaultWayType
		_c.mutation.SetWayType(v)
	}
	if _, ok := _c.mutation.BookingChannel(); !ok {
		v := ticket.DefaultBookingChannel
		_c.mutation.SetBookingChannel(v)
	}
	if _, ok := _c.mutation.PaymentMethod(); !ok {
		v := ticket.DefaultPaymentMethod
		_c.mutation.SetPaymentMethod(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := ticket.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.DepartureTimes(); !ok {
		v := ticket.DefaultDepartureTimes
		_c.mutation.SetDepartureTimes(v)
	}
	if _, ok := _c.mutation.OriginAmount(); !ok {
		v := ticket.DefaultOriginAmount
		_c.mutation.SetOriginAmount(v)
	}
	if _, ok := _c.mutation.DiscountAmount(); !ok {
		v := ticket.DefaultDiscountAmount
		_c.mutation.SetDiscountAmount(v)
	}
	if _, ok := _c.mutation.RefundAmount(); !ok {
		v := ticket.DefaultRefundAmount
		_c.mutation.SetRefundAmount(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := ticket.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TicketCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Ticket.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Ticket.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Ticket.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := ticket.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Ticket.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Ticket.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := ticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Ticket.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WayType(); !ok {
		return &ValidationError{Name: "way_type", err: errors.New(`ent: missing required field "Ticket.way_type"`)}
	}
	if v, ok := _c.mutation.WayType(); ok {
		if err := ticket.WayTypeValidator(v); err != nil {
			return &ValidationError{Name: "way_type", err: fmt.Errorf(`ent: validator failed for field "Ticket.way_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BookingChannel(); !ok {
		return &ValidationError{Name: "booking_channel", err: errors.New(`ent: missing required field "Ticket.booking_channel"`)}
	}
	if v, ok := _c.mutation.BookingChannel(); ok {
		if err := ticket.BookingChannelValidator(v); err != nil {
			return &ValidationError{Name: "booking_channel", err: fmt.Errorf(`ent: validator failed for field "Ticket.booking_channel": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentMethod(); !ok {
		return &ValidationError{Name: "payment_method", err: errors.New(`ent: missing required field "Ticket.payment_method"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Ticket.is_active"`)}
	}
	if _, ok := _c.mutation.DepartureTimes(); !ok {
		return &ValidationError{Name: "departure_times", err: errors.New(`ent: missing required field "Ticket.departure_times"`)}
	}
	if _, ok := _c.mutation.OriginAmount(); !ok {
		return &ValidationError{Name: "origin_amount", err: errors.New(`ent: missing required field "Ticket.origin_amount"`)}
	}
	if v, ok := _c.mutation.OriginAmount(); ok {
		if err := ticket.OriginAmountValidator(v); err != nil {
			return &ValidationError{Name: "origin_amount", err: fmt.Errorf(`ent: validator failed for field "Ticket.origin_amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DiscountAmount(); !ok {
		return &ValidationError{Name: "discount_amount", err: errors.New(`ent: missing required field "Ticket.discount_amount"`)}
	}
	if v, ok := _c.mutation.DiscountAmount(); ok {
		if err := ticket.DiscountAmountValidator(v); err != nil {
			return &ValidationError{Name: "discount_amount", err: fmt.Errorf(`ent: validator failed for field "Ticket.discount_amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RefundAmount(); !ok {
		return &ValidationError{Name: "refund_amount", err: errors.New(`ent: missing required field "Ticket.refund_amount"`)}
	}
	if v, ok := _c.mutation.RefundAmount(); ok {
		if err := ticket.RefundAmountValidator(v); err != nil {
			return &ValidationError{Name: "refund_amount", err: fmt.Errorf(`ent: validator failed for field "Ticket.refund_amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReferenceUserID(); !ok {
		return &ValidationError{Name: "reference_user_id", err: errors.New(`ent: missing required field "Ticket.reference_user_id"`)}
	}
	if v, ok := _c.mutation.ReferenceUserID(); ok {
		if err := ticket.ReferenceUserIDValidator(v); err != nil {
			return &ValidationError{Name: "reference_user_id", err: fmt.Errorf(`ent: validator failed for field "Ticket.reference_user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReferencePhone(); !ok {
		return &ValidationError{Name: "reference_phone", err: errors.New(`ent: missing required field "Ticket.reference_phone"`)}
	}
	return nil
}

func (_c *TicketCreate) sqlSave(ctx context.Context) (*Ticket, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TicketCreate) createSpec() (*Ticket, *sqlgraph.CreateSpec) {
	var (
		_node = &Ticket{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ticket.Table, sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.Ticket
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ticket.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ticket.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(ticket.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(ticket.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(ticket.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.WayType(); ok {
		_spec.SetField(ticket.FieldWayType, field.TypeEnum, value)
		_node.WayType = value
	}
	if value, ok := _c.mutation.BookingChannel(); ok {
		_spec.SetField(ticket.FieldBookingChannel, field.TypeEnum, value)
		_node.BookingChannel = value
	}
	if value, ok := _c.mutation.PaymentMethod(); ok {
		_spec.SetField(ticket.FieldPaymentMethod, field.TypeInt, value)
		_node.PaymentMethod = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(ticket.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.PromotionCode(); ok {
		_spec.SetField(ticket.FieldPromotionCode, field.TypeString, value)
		_node.PromotionCode = &value
	}
	if value, ok := _c.mutation.DepartureTimes(); ok {
		_spec.SetField(ticket.FieldDepartureTimes, field.TypeJSON, value)
		_node.DepartureTimes = value
	}
	if value, ok := _c.mutation.OriginAmount(); ok {
		_spec.SetField(ticket.FieldOriginAmount, field.TypeFloat64, value)
		_node.OriginAmount = value
	}
	if value, ok := _c.mutation.DiscountAmount(); ok {
		_spec.SetField(ticket.FieldDiscountAmount, field.TypeFloat64, value)
		_node.DiscountAmount = value
	}
	if value, ok := _c.mutation.RefundAmount(); ok {
		_spec.SetField(ticket.FieldRefundAmount, field.TypeFloat64, value)
		_node.RefundAmount = value
	}
	if value, ok := _c.mutation.Remarks(); ok {
		_spec.SetField(ticket.FieldRemarks, field.TypeString, value)
		_node.Remarks = &value
	}
	if value, ok := _c.mutation.ReferenceUserID(); ok {
		_spec.SetField(ticket.FieldReferenceUserID, field.TypeString, value)
		_node.ReferenceUserID = value
	}
	if value, ok := _c.mutation.ReferencePhone(); ok {
		_spec.SetField(ticket.FieldReferencePhone, field.TypeString, value)
		_node.ReferencePhone = value
	}
	if value, ok := _c.mutation.ReferenceMigrationID(); ok {
		_spec.SetField(ticket.FieldReferenceMigrationID, field.TypeString, value)
		_node.ReferenceMigrationID = &value
	}
	if value, ok := _c.mutation.ForceUpdatedUserID(); ok {
		_spec.SetField(ticket.FieldForceUpdatedUserID, field.TypeString, value)
		_node.ForceUpdatedUserID = &value
	}
	if nodes := _c.mutation.TicketSeatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ticket.TicketSeatsTable,
			Columns: []string{ticket.TicketSeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticketseat.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.TicketSeat
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Ticket.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketCreate) OnConflict(opts ...sql.ConflictOption) *TicketUpsertOne {
	_c.conflict = opts
	return &TicketUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Ticket.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketCreate) OnConflictColumns(columns ...string) *TicketUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketUpsertOne{
		create: _c,
	}
}

type (
	// TicketUpsertOne is the builder for "upsert"-ing
	//  one Ticket node.
	TicketUpsertOne struct {
		create *TicketCreate
	}

	// TicketUpsert is the "OnConflict" setter.
	TicketUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TicketUpsert) SetUpdatedAt(v time.Time) *TicketUpsert {
	u.Set(ticket.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TicketUpsert) UpdateUpdatedAt() *TicketUpsert {
	u.SetExcluded(ticket.FieldUpdatedAt)
	return u
}

// SetCode sets the "code" field.
func (u *TicketUpsert) SetCode(v string) *TicketUpsert {
	u.Set(ticket.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TicketUpsert) UpdateCode() *TicketUpsert {
	u.SetExcluded(ticket.FieldCode)
	return u
}

// SetStatus sets the "status" field.
func (u *TicketUpsert) SetStatus(v ticket.Status) *TicketUpsert {
	u.Set(ticket.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TicketUpsert) UpdateStatus() *TicketUpsert {
	u.SetExcluded(ticket.FieldStatus)
	return u
}

// SetWayType sets the "way_type" field.
func (u *TicketUpsert) SetWayType(v ticket.WayType) *TicketUpsert {
	u.Set(ticket.FieldWayType, v)
	return u
}

// UpdateWayType sets the "way_type" field to the value that was provided on create.
func (u *TicketUpsert) UpdateWayType() *TicketUpsert {
	u.SetExcluded(ticket.FieldWayType)
	return u
}

// SetBookingChannel sets the "booking_channel" field.
func (u *TicketUpsert) SetBookingChannel(v ticket.BookingChannel) *TicketUpsert {
	u.Set(ticket.FieldBookingChannel, v)
	return u
}

// UpdateBookingChannel sets the "booking_channel" field to the value that was provided on create.
func (u *TicketUpsert) UpdateBookingChannel() *TicketUpsert {
	u.SetExcluded(ticket.FieldBookingChannel)
	return u
}

// SetPaymentMethod sets the "payment_method" field.
func (u *TicketUpsert) SetPaymentMethod(v int) *TicketUpsert {
	u.Set(ticket.FieldPaymentMethod, v)
	return u
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *TicketUpsert) UpdatePaymentMethod() *TicketUpsert {
	u.SetExcluded(ticket.FieldPaymentMethod)
	return u
}

// AddPaymentMethod adds v to the "payment_method" field.
func (u *TicketUpsert) AddPaymentMethod(v int) *TicketUpsert {
	u.Add(ticket.FieldPaymentMethod, v)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *TicketUpsert) SetIsActive(v bool) *TicketUpsert {
	u.Set(ticket.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *TicketUpsert) UpdateIsActive() *TicketUpsert {
	u.SetExcluded(ticket.FieldIsActive)
	return u
}

// SetPromotionCode sets the "promotion_code" field.
func (u *TicketUpsert) SetPromotionCode(v string) *TicketUpsert {
	u.Set(ticket.FieldPromotionCode, v)
	return u
}

// UpdatePromotionCode sets the "promotion_code" field to the value that was provided on create.
func (u *TicketUpsert) UpdatePromotionCode() *TicketUpsert {
	u.SetExcluded(ticket.FieldPromotionCode)
	return u
}

// ClearPromotionCode clears the value of the "promotion_code" field.
func (u *TicketUpsert) ClearPromotionCode() *TicketUpsert {
	u.SetNull(ticket.FieldPromotionCode)
	return u
}

// SetDepartureTimes sets the "departure_times" field.
func (u *TicketUpsert) SetDepartureTimes(v []string) *TicketUpsert {
	u.Set(ticket.FieldDepartureTimes, v)
	return u
}

// UpdateDepartureTimes sets the "departure_times" field to the value that was provided on create.
func (u *TicketUpsert) UpdateDepartureTimes() *TicketUpsert {
	u.SetExcluded(ticket.FieldDepartureTimes)
	return u
}

// SetOriginAmount sets the "origin_amount" field.
func (u *TicketUpsert) SetOriginAmount(v float64) *TicketUpsert {
	u.Set(ticket.FieldOriginAmount, v)
	return u
}

// UpdateOriginAmount sets the "origin_amount" field to the value that was provided on create.
func (u *TicketUpsert) UpdateOriginAmount() *TicketUpsert {
	u.SetExcluded(ticket.FieldOriginAmount)
	return u
}

// AddOriginAmount adds v to the "origin_amount" field.
func (u *TicketUpsert) AddOriginAmount(v float64) *TicketUpsert {
	u.Add(ticket.FieldOriginAmount, v)
	return u
}

// SetDiscountAmount sets the "discount_amount" field.
func (u *TicketUpsert) SetDiscountAmount(v float64) *TicketUpsert {
	u.Set(ticket.FieldDiscountAmount, v)
	return u
}

// UpdateDiscountAmount sets the "discount_amount" field to the value that was provided on create.
func (u *TicketUpsert) UpdateDiscountAmount() *TicketUpsert {
	u.SetExcluded(ticket.FieldDiscountAmount)
	return u
}

// AddDiscountAmount adds v to the "discount_amount" field.
func (u *TicketUpsert) AddDiscountAmount(v float64) *TicketUpsert {
	u.Add(ticket.FieldDiscountAmount, v)
	return u
}

// SetRefundAmount sets the "refund_amount" field.
func (u *TicketUpsert) SetRefundAmount(v float64) *TicketUpsert {
	u.Set(ticket.FieldRefundAmount, v)
	return u
}

// UpdateRefundAmount sets the "refund_amount" field to the value that was provided on create.
func (u *TicketUpsert) UpdateRefundAmount() *TicketUpsert {
	u.SetExcluded(ticket.FieldRefundAmount)
	return u
}

// AddRefundAmount adds v to the "refund_amount" field.
func (u *TicketUpsert) AddRefundAmount(v float64) *TicketUpsert {
	u.Add(ticket.FieldRefundAmount, v)
	return u
}

// SetRemarks sets the "remarks" field.
func (u *TicketUpsert) SetRemarks(v string) *TicketUpsert {
	u.Set(ticket.FieldRemarks, v)
	return u
}

// UpdateRemarks sets the "remarks" field to the value that was provided on create.
func (u *TicketUpsert) UpdateRemarks() *TicketUpsert {
	u.SetExcluded(ticket.FieldRemarks)
	return u
}

// ClearRemarks clears the value of the "remarks" field.
func (u *TicketUpsert) ClearRemarks() *TicketUpsert {
	u.SetNull(ticket.FieldRemarks)
	return u
}

// SetReferenceUserID sets the "reference_user_id" field.
func (u *TicketUpsert) SetReferenceUserID(v string) *TicketUpsert {
	u.Set(ticket.FieldReferenceUserID, v)
	return u
}

// UpdateReferenceUserID sets the "reference_user_id" field to the value that was provided on create.
func (u *TicketUpsert) UpdateReferenceUserID() *TicketUpsert {
	u.SetExcluded(ticket.FieldReferenceUserID)
	return u
}

// SetReferencePhone sets the "reference_phone" field.
func (u *TicketUpsert) SetReferencePhone(v string) *TicketUpsert {
	u.Set(ticket.FieldReferencePhone, v)
	return u
}

// UpdateReferencePhone sets the "reference_phone" field to the value that was provided on create.
func (u *TicketUpsert) UpdateReferencePhone() *TicketUpsert {
	u.SetExcluded(ticket.FieldReferencePhone)
	return u
}

// SetReferenceMigrationID sets the "reference_migration_id" field.
func (u *TicketUpsert) SetReferenceMigrationID(v string) *TicketUpsert {
	u.Set(ticket.FieldReferenceMigrationID, v)
	return u
}

// UpdateReferenceMigrationID sets the "reference_migration_id" field to the value that was provided on create.
func (u *TicketUpsert) UpdateReferenceMigrationID() *TicketUpsert {
	u.SetExcluded(ticket.FieldReferenceMigrationID)
	return u
}

// ClearReferenceMigrationID clears the value of the "reference_migration_id" field.
func (u *TicketUpsert) ClearReferenceMigrationID() *TicketUpsert {
	u.SetNull(ticket.FieldReferenceMigrationID)
	return u
}

// SetForceUpdatedUserID sets the "force_updated_user_id" field.
func (u *TicketUpsert) SetForceUpdatedUserID(v string) *TicketUpsert {
	u.Set(ticket.FieldForceUpdatedUserID, v)
	return u
}

// UpdateForceUpdatedUserID sets the "force_updated_user_id" field to the value that was provided on create.
func (u *TicketUpsert) UpdateForceUpdatedUserID() *TicketUpsert {
	u.SetExcluded(ticket.FieldForceUpdatedUserID)
	return u
}

// ClearForceUpdatedUserID clears the value of the "force_updated_user_id" field.
func (u *TicketUpsert) ClearForceUpdatedUserID() *TicketUpsert {
	u.SetNull(ticket.FieldForceUpdatedUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Ticket.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ticket.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TicketUpsertOne) UpdateNewValues() *TicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(ticket.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ticket.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(ticket.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Ticket.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TicketUpsertOne) Ignore() *TicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketUpsertOne) DoNothing() *TicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketCreate.OnConflict
// documentation for more info.
func (u *TicketUpsertOne) Update(set func(*TicketUpsert)) *TicketUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TicketUpsertOne) SetUpdatedAt(v time.Time) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateUpdatedAt() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *TicketUpsertOne) SetCode(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateCode() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateCode()
	})
}

// SetStatus sets the "status" field.
func (u *TicketUpsertOne) SetStatus(v ticket.Status) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateStatus() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateStatus()
	})
}

// SetWayType sets the "way_type" field.
func (u *TicketUpsertOne) SetWayType(v ticket.WayType) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetWayType(v)
	})
}

// UpdateWayType sets the "way_type" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateWayType() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateWayType()
	})
}

// SetBookingChannel sets the "booking_channel" field.
func (u *TicketUpsertOne) SetBookingChannel(v ticket.BookingChannel) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetBookingChannel(v)
	})
}

// UpdateBookingChannel sets the "booking_channel" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateBookingChannel() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateBookingChannel()
	})
}

// SetPaymentMethod sets the "payment_method" field.
func (u *TicketUpsertOne) SetPaymentMethod(v int) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetPaymentMethod(v)
	})
}

// AddPaymentMethod adds v to the "payment_method" field.
func (u *TicketUpsertOne) AddPaymentMethod(v int) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.AddPaymentMethod(v)
	})
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdatePaymentMethod() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdatePaymentMethod()
	})
}

// SetIsActive sets the "is_active" field.
func (u *TicketUpsertOne) SetIsActive(v bool) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateIsActive() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateIsActive()
	})
}

// SetPromotionCode sets the "promotion_code" field.
func (u *TicketUpsertOne) SetPromotionCode(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetPromotionCode(v)
	})
}

// UpdatePromotionCode sets the "promotion_code" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdatePromotionCode() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdatePromotionCode()
	})
}

// ClearPromotionCode clears the value of the "promotion_code" field.
func (u *TicketUpsertOne) ClearPromotionCode() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.ClearPromotionCode()
	})
}

// SetDepartureTimes sets the "departure_times" field.
func (u *TicketUpsertOne) SetDepartureTimes(v []string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetDepartureTimes(v)
	})
}

// UpdateDepartureTimes sets the "departure_times" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateDepartureTimes() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateDepartureTimes()
	})
}

// SetOriginAmount sets the "origin_amount" field.
func (u *TicketUpsertOne) SetOriginAmount(v float64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetOriginAmount(v)
	})
}

// AddOriginAmount adds v to the "origin_amount" field.
func (u *TicketUpsertOne) AddOriginAmount(v float64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.AddOriginAmount(v)
	})
}

// UpdateOriginAmount sets the "origin_amount" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateOriginAmount() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateOriginAmount()
	})
}

// SetDiscountAmount sets the "discount_amount" field.
func (u *TicketUpsertOne) SetDiscountAmount(v float64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetDiscountAmount(v)
	})
}

// AddDiscountAmount adds v to the "discount_amount" field.
func (u *TicketUpsertOne) AddDiscountAmount(v float64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.AddDiscountAmount(v)
	})
}

// UpdateDiscountAmount sets the "discount_amount" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateDiscountAmount() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateDiscountAmount()
	})
}

// SetRefundAmount sets the "refund_amount" field.
func (u *TicketUpsertOne) SetRefundAmount(v float64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetRefundAmount(v)
	})
}

// AddRefundAmount adds v to the "refund_amount" field.
func (u *TicketUpsertOne) AddRefundAmount(v float64) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.AddRefundAmount(v)
	})
}

// UpdateRefundAmount sets the "refund_amount" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateRefundAmount() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateRefundAmount()
	})
}

// SetRemarks sets the "remarks" field.
func (u *TicketUpsertOne) SetRemarks(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetRemarks(v)
	})
}

// UpdateRemarks sets the "remarks" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateRemarks() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateRemarks()
	})
}

// ClearRemarks clears the value of the "remarks" field.
func (u *TicketUpsertOne) ClearRemarks() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.ClearRemarks()
	})
}

// SetReferenceUserID sets the "reference_user_id" field.
func (u *TicketUpsertOne) SetReferenceUserID(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetReferenceUserID(v)
	})
}

// UpdateReferenceUserID sets the "reference_user_id" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateReferenceUserID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateReferenceUserID()
	})
}

// SetReferencePhone sets the "reference_phone" field.
func (u *TicketUpsertOne) SetReferencePhone(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetReferencePhone(v)
	})
}

// UpdateReferencePhone sets the "reference_phone" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateReferencePhone() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateReferencePhone()
	})
}

// SetReferenceMigrationID sets the "reference_migration_id" field.
func (u *TicketUpsertOne) SetReferenceMigrationID(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetReferenceMigrationID(v)
	})
}

// UpdateReferenceMigrationID sets the "reference_migration_id" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateReferenceMigrationID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateReferenceMigrationID()
	})
}

// ClearReferenceMigrationID clears the value of the "reference_migration_id" field.
func (u *TicketUpsertOne) ClearReferenceMigrationID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.ClearReferenceMigrationID()
	})
}

// SetForceUpdatedUserID sets the "force_updated_user_id" field.
func (u *TicketUpsertOne) SetForceUpdatedUserID(v string) *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.SetForceUpdatedUserID(v)
	})
}

// UpdateForceUpdatedUserID sets the "force_updated_user_id" field to the value that was provided on create.
func (u *TicketUpsertOne) UpdateForceUpdatedUserID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateForceUpdatedUserID()
	})
}

// ClearForceUpdatedUserID clears the value of the "force_updated_user_id" field.
func (u *TicketUpsertOne) ClearForceUpdatedUserID() *TicketUpsertOne {
	return u.Update(func(s *TicketUpsert) {
		s.ClearForceUpdatedUserID()
	})
}

// Exec executes the query.
func (u *TicketUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TicketUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TicketUpsertOne.ID is not supported by MySQL driver. Use TicketUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TicketUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TicketCreateBulk is the builder for creating many Ticket entities in bulk.
type TicketCreateBulk struct {
	config
	err      error
	builders []*TicketCreate
	conflict []sql.ConflictOption
}

// Save creates the Ticket entities in the database.
func (_c *TicketCreateBulk) Save(ctx context.Context) ([]*Ticket, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Ticket, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TicketCreateBulk) SaveX(ctx context.Context) []*Ticket {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Ticket.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TicketUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TicketCreateBulk) OnConflict(opts ...sql.ConflictOption) *TicketUpsertBulk {
	_c.conflict = opts
	return &TicketUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Ticket.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TicketCreateBulk) OnConflictColumns(columns ...string) *TicketUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TicketUpsertBulk{
		create: _c,
	}
}

// TicketUpsertBulk is the builder for "upsert"-ing
// a bulk of Ticket nodes.
type TicketUpsertBulk struct {
	create *TicketCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Ticket.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ticket.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TicketUpsertBulk) UpdateNewValues() *TicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(ticket.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ticket.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(ticket.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Ticket.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TicketUpsertBulk) Ignore() *TicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TicketUpsertBulk) DoNothing() *TicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TicketCreateBulk.OnConflict
// documentation for more info.
func (u *TicketUpsertBulk) Update(set func(*TicketUpsert)) *TicketUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TicketUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TicketUpsertBulk) SetUpdatedAt(v time.Time) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateUpdatedAt() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *TicketUpsertBulk) SetCode(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateCode() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateCode()
	})
}

// SetStatus sets the "status" field.
func (u *TicketUpsertBulk) SetStatus(v ticket.Status) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateStatus() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateStatus()
	})
}

// SetWayType sets the "way_type" field.
func (u *TicketUpsertBulk) SetWayType(v ticket.WayType) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetWayType(v)
	})
}

// UpdateWayType sets the "way_type" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateWayType() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateWayType()
	})
}

// SetBookingChannel sets the "booking_channel" field.
func (u *TicketUpsertBulk) SetBookingChannel(v ticket.BookingChannel) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetBookingChannel(v)
	})
}

// UpdateBookingChannel sets the "booking_channel" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateBookingChannel() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateBookingChannel()
	})
}

// SetPaymentMethod sets the "payment_method" field.
func (u *TicketUpsertBulk) SetPaymentMethod(v int) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetPaymentMethod(v)
	})
}

// AddPaymentMethod adds v to the "payment_method" field.
func (u *TicketUpsertBulk) AddPaymentMethod(v int) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.AddPaymentMethod(v)
	})
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdatePaymentMethod() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdatePaymentMethod()
	})
}

// SetIsActive sets the "is_active" field.
func (u *TicketUpsertBulk) SetIsActive(v bool) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateIsActive() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateIsActive()
	})
}

// SetPromotionCode sets the "promotion_code" field.
func (u *TicketUpsertBulk) SetPromotionCode(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetPromotionCode(v)
	})
}

// UpdatePromotionCode sets the "promotion_code" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdatePromotionCode() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdatePromotionCode()
	})
}

// ClearPromotionCode clears the value of the "promotion_code" field.
func (u *TicketUpsertBulk) ClearPromotionCode() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.ClearPromotionCode()
	})
}

// SetDepartureTimes sets the "departure_times" field.
func (u *TicketUpsertBulk) SetDepartureTimes(v []string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetDepartureTimes(v)
	})
}

// UpdateDepartureTimes sets the "departure_times" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateDepartureTimes() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateDepartureTimes()
	})
}

// SetOriginAmount sets the "origin_amount" field.
func (u *TicketUpsertBulk) SetOriginAmount(v float64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetOriginAmount(v)
	})
}

// AddOriginAmount adds v to the "origin_amount" field.
func (u *TicketUpsertBulk) AddOriginAmount(v float64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.AddOriginAmount(v)
	})
}

// UpdateOriginAmount sets the "origin_amount" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateOriginAmount() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateOriginAmount()
	})
}

// SetDiscountAmount sets the "discount_amount" field.
func (u *TicketUpsertBulk) SetDiscountAmount(v float64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetDiscountAmount(v)
	})
}

// AddDiscountAmount adds v to the "discount_amount" field.
func (u *TicketUpsertBulk) AddDiscountAmount(v float64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.AddDiscountAmount(v)
	})
}

// UpdateDiscountAmount sets the "discount_amount" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateDiscountAmount() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateDiscountAmount()
	})
}

// SetRefundAmount sets the "refund_amount" field.
func (u *TicketUpsertBulk) SetRefundAmount(v float64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetRefundAmount(v)
	})
}

// AddRefundAmount adds v to the "refund_amount" field.
func (u *TicketUpsertBulk) AddRefundAmount(v float64) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.AddRefundAmount(v)
	})
}

// UpdateRefundAmount sets the "refund_amount" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateRefundAmount() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateRefundAmount()
	})
}

// SetRemarks sets the "remarks" field.
func (u *TicketUpsertBulk) SetRemarks(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetRemarks(v)
	})
}

// UpdateRemarks sets the "remarks" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateRemarks() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateRemarks()
	})
}

// ClearRemarks clears the value of the "remarks" field.
func (u *TicketUpsertBulk) ClearRemarks() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.ClearRemarks()
	})
}

// SetReferenceUserID sets the "reference_user_id" field.
func (u *TicketUpsertBulk) SetReferenceUserID(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetReferenceUserID(v)
	})
}

// UpdateReferenceUserID sets the "reference_user_id" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateReferenceUserID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateReferenceUserID()
	})
}

// SetReferencePhone sets the "reference_phone" field.
func (u *TicketUpsertBulk) SetReferencePhone(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetReferencePhone(v)
	})
}

// UpdateReferencePhone sets the "reference_phone" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateReferencePhone() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateReferencePhone()
	})
}

// SetReferenceMigrationID sets the "reference_migration_id" field.
func (u *TicketUpsertBulk) SetReferenceMigrationID(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetReferenceMigrationID(v)
	})
}

// UpdateReferenceMigrationID sets the "reference_migration_id" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateReferenceMigrationID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateReferenceMigrationID()
	})
}

// ClearReferenceMigrationID clears the value of the "reference_migration_id" field.
func (u *TicketUpsertBulk) ClearReferenceMigrationID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.ClearReferenceMigrationID()
	})
}

// SetForceUpdatedUserID sets the "force_updated_user_id" field.
func (u *TicketUpsertBulk) SetForceUpdatedUserID(v string) *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.SetForceUpdatedUserID(v)
	})
}

// UpdateForceUpdatedUserID sets the "force_updated_user_id" field to the value that was provided on create.
func (u *TicketUpsertBulk) UpdateForceUpdatedUserID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.UpdateForceUpdatedUserID()
	})
}

// ClearForceUpdatedUserID clears the value of the "force_updated_user_id" field.
func (u *TicketUpsertBulk) ClearForceUpdatedUserID() *TicketUpsertBulk {
	return u.Update(func(s *TicketUpsert) {
		s.ClearForceUpdatedUserID()
	})
}

// Exec executes the query.
func (u *TicketUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TicketCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TicketCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TicketUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
