// Code generated by novaerp.com, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"vn.vato.zora.be.api/apps/zalo/internal/data/ent/ticket"
)

// Ticket is the model entity for the Ticket schema.
type Ticket struct {
	config `json:"-"`
	// ID of the ent.
	// Primary key
	ID uuid.UUID `json:"id,omitempty"`
	// Record creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Record last update timestamp
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Status holds the value of the "status" field.
	Status ticket.Status `json:"status,omitempty"`
	// WayType holds the value of the "way_type" field.
	WayType ticket.WayType `json:"way_type,omitempty"`
	// BookingChannel holds the value of the "booking_channel" field.
	BookingChannel ticket.BookingChannel `json:"booking_channel,omitempty"`
	// Payment Method
	PaymentMethod int `json:"payment_method,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// PromotionCode holds the value of the "promotion_code" field.
	PromotionCode *string `json:"promotion_code,omitempty"`
	// Departure Times: [outbound, return]
	DepartureTimes []string `json:"departure_times,omitempty"`
	// Origin amount for the ticket
	OriginAmount float64 `json:"origin_amount,omitempty"`
	// Discount amount applied to the ticket
	DiscountAmount float64 `json:"discount_amount,omitempty"`
	// Refund amount for the ticket
	RefundAmount float64 `json:"refund_amount,omitempty"`
	// Remarks holds the value of the "remarks" field.
	Remarks *string `json:"remarks,omitempty"`
	// ReferenceUserID holds the value of the "reference_user_id" field.
	ReferenceUserID string `json:"reference_user_id,omitempty"`
	// ReferencePhone holds the value of the "reference_phone" field.
	ReferencePhone string `json:"reference_phone,omitempty"`
	// ReferenceMigrationID holds the value of the "reference_migration_id" field.
	ReferenceMigrationID *string `json:"reference_migration_id,omitempty"`
	// ForceUpdatedUserID holds the value of the "force_updated_user_id" field.
	ForceUpdatedUserID *string `json:"force_updated_user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TicketQuery when eager-loading is set.
	Edges        TicketEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TicketEdges holds the relations/edges for other nodes in the graph.
type TicketEdges struct {
	// TicketSeats holds the value of the ticketSeats edge.
	TicketSeats []*TicketSeat `json:"ticketSeats,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes      [1]bool
	namedTicketSeats map[string][]*TicketSeat
}

// TicketSeatsOrErr returns the TicketSeats value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) TicketSeatsOrErr() ([]*TicketSeat, error) {
	if e.loadedTypes[0] {
		return e.TicketSeats, nil
	}
	return nil, &NotLoadedError{edge: "ticketSeats"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ticket) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ticket.FieldDepartureTimes:
			values[i] = new([]byte)
		case ticket.FieldIsActive:
			values[i] = new(sql.NullBool)
		case ticket.FieldOriginAmount, ticket.FieldDiscountAmount, ticket.FieldRefundAmount:
			values[i] = new(sql.NullFloat64)
		case ticket.FieldPaymentMethod:
			values[i] = new(sql.NullInt64)
		case ticket.FieldCode, ticket.FieldStatus, ticket.FieldWayType, ticket.FieldBookingChannel, ticket.FieldPromotionCode, ticket.FieldRemarks, ticket.FieldReferenceUserID, ticket.FieldReferencePhone, ticket.FieldReferenceMigrationID, ticket.FieldForceUpdatedUserID:
			values[i] = new(sql.NullString)
		case ticket.FieldCreatedAt, ticket.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case ticket.FieldID, ticket.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ticket fields.
func (_m *Ticket) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ticket.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case ticket.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ticket.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ticket.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case ticket.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case ticket.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = ticket.Status(value.String)
			}
		case ticket.FieldWayType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field way_type", values[i])
			} else if value.Valid {
				_m.WayType = ticket.WayType(value.String)
			}
		case ticket.FieldBookingChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field booking_channel", values[i])
			} else if value.Valid {
				_m.BookingChannel = ticket.BookingChannel(value.String)
			}
		case ticket.FieldPaymentMethod:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_method", values[i])
			} else if value.Valid {
				_m.PaymentMethod = int(value.Int64)
			}
		case ticket.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case ticket.FieldPromotionCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field promotion_code", values[i])
			} else if value.Valid {
				_m.PromotionCode = new(string)
				*_m.PromotionCode = value.String
			}
		case ticket.FieldDepartureTimes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field departure_times", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DepartureTimes); err != nil {
					return fmt.Errorf("unmarshal field departure_times: %w", err)
				}
			}
		case ticket.FieldOriginAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field origin_amount", values[i])
			} else if value.Valid {
				_m.OriginAmount = value.Float64
			}
		case ticket.FieldDiscountAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field discount_amount", values[i])
			} else if value.Valid {
				_m.DiscountAmount = value.Float64
			}
		case ticket.FieldRefundAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field refund_amount", values[i])
			} else if value.Valid {
				_m.RefundAmount = value.Float64
			}
		case ticket.FieldRemarks:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remarks", values[i])
			} else if value.Valid {
				_m.Remarks = new(string)
				*_m.Remarks = value.String
			}
		case ticket.FieldReferenceUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference_user_id", values[i])
			} else if value.Valid {
				_m.ReferenceUserID = value.String
			}
		case ticket.FieldReferencePhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference_phone", values[i])
			} else if value.Valid {
				_m.ReferencePhone = value.String
			}
		case ticket.FieldReferenceMigrationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference_migration_id", values[i])
			} else if value.Valid {
				_m.ReferenceMigrationID = new(string)
				*_m.ReferenceMigrationID = value.String
			}
		case ticket.FieldForceUpdatedUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field force_updated_user_id", values[i])
			} else if value.Valid {
				_m.ForceUpdatedUserID = new(string)
				*_m.ForceUpdatedUserID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Ticket.
// This includes values selected through modifiers, order, etc.
func (_m *Ticket) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTicketSeats queries the "ticketSeats" edge of the Ticket entity.
func (_m *Ticket) QueryTicketSeats() *TicketSeatQuery {
	return NewTicketClient(_m.config).QueryTicketSeats(_m)
}

// Update returns a builder for updating this Ticket.
// Note that you need to call Ticket.Unwrap() before calling this method if this Ticket
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Ticket) Update() *TicketUpdateOne {
	return NewTicketClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Ticket entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Ticket) Unwrap() *Ticket {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Ticket is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Ticket) String() string {
	var builder strings.Builder
	builder.WriteString("Ticket(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("way_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.WayType))
	builder.WriteString(", ")
	builder.WriteString("booking_channel=")
	builder.WriteString(fmt.Sprintf("%v", _m.BookingChannel))
	builder.WriteString(", ")
	builder.WriteString("payment_method=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaymentMethod))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	if v := _m.PromotionCode; v != nil {
		builder.WriteString("promotion_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("departure_times=")
	builder.WriteString(fmt.Sprintf("%v", _m.DepartureTimes))
	builder.WriteString(", ")
	builder.WriteString("origin_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.OriginAmount))
	builder.WriteString(", ")
	builder.WriteString("discount_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiscountAmount))
	builder.WriteString(", ")
	builder.WriteString("refund_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundAmount))
	builder.WriteString(", ")
	if v := _m.Remarks; v != nil {
		builder.WriteString("remarks=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("reference_user_id=")
	builder.WriteString(_m.ReferenceUserID)
	builder.WriteString(", ")
	builder.WriteString("reference_phone=")
	builder.WriteString(_m.ReferencePhone)
	builder.WriteString(", ")
	if v := _m.ReferenceMigrationID; v != nil {
		builder.WriteString("reference_migration_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ForceUpdatedUserID; v != nil {
		builder.WriteString("force_updated_user_id=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// NamedTicketSeats returns the TicketSeats named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Ticket) NamedTicketSeats(name string) ([]*TicketSeat, error) {
	if _m.Edges.namedTicketSeats == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedTicketSeats[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Ticket) appendNamedTicketSeats(name string, edges ...*TicketSeat) {
	if _m.Edges.namedTicketSeats == nil {
		_m.Edges.namedTicketSeats = make(map[string][]*TicketSeat)
	}
	if len(edges) == 0 {
		_m.Edges.namedTicketSeats[name] = []*TicketSeat{}
	} else {
		_m.Edges.namedTicketSeats[name] = append(_m.Edges.namedTicketSeats[name], edges...)
	}
}

// Tickets is a parsable slice of Ticket.
type Tickets []*Ticket
