// Code generated by novaerp.com, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"vn.vato.zora.be.api/apps/zalo/internal/data/ent/internal"
	"vn.vato.zora.be.api/apps/zalo/internal/data/ent/predicate"
	"vn.vato.zora.be.api/apps/zalo/internal/data/ent/ticketseat"
)

// TicketSeatDelete is the builder for deleting a TicketSeat entity.
type TicketSeatDelete struct {
	config
	hooks    []Hook
	mutation *TicketSeatMutation
}

// Where appends a list predicates to the TicketSeatDelete builder.
func (_d *TicketSeatDelete) Where(ps ...predicate.TicketSeat) *TicketSeatDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TicketSeatDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TicketSeatDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TicketSeatDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ticketseat.Table, sqlgraph.NewFieldSpec(ticketseat.FieldID, field.TypeUUID))
	_spec.Node.Schema = _d.schemaConfig.TicketSeat
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TicketSeatDeleteOne is the builder for deleting a single TicketSeat entity.
type TicketSeatDeleteOne struct {
	_d *TicketSeatDelete
}

// Where appends a list predicates to the TicketSeatDelete builder.
func (_d *TicketSeatDeleteOne) Where(ps ...predicate.TicketSeat) *TicketSeatDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TicketSeatDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ticketseat.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TicketSeatDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
