// Code generated by novaerp.com, DO NOT EDIT.

package ticketseat

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"vn.vato.zora.be.api/apps/zalo/internal/data/ent/internal"
	"vn.vato.zora.be.api/apps/zalo/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldUpdatedAt, v))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v uuid.UUID) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldTicketID, v))
}

// RouteID applies equality check predicate on the "route_id" field. It's identical to RouteIDEQ.
func RouteID(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldRouteID, v))
}

// RouteName applies equality check predicate on the "route_name" field. It's identical to RouteNameEQ.
func RouteName(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldRouteName, v))
}

// DepartureTime applies equality check predicate on the "departure_time" field. It's identical to DepartureTimeEQ.
func DepartureTime(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDepartureTime, v))
}

// TripID applies equality check predicate on the "trip_id" field. It's identical to TripIDEQ.
func TripID(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldTripID, v))
}

// SeatID applies equality check predicate on the "seat_id" field. It's identical to SeatIDEQ.
func SeatID(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldSeatID, v))
}

// SeatName applies equality check predicate on the "seat_name" field. It's identical to SeatNameEQ.
func SeatName(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldSeatName, v))
}

// OriginAmount applies equality check predicate on the "origin_amount" field. It's identical to OriginAmountEQ.
func OriginAmount(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldOriginAmount, v))
}

// DiscountAmount applies equality check predicate on the "discount_amount" field. It's identical to DiscountAmountEQ.
func DiscountAmount(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDiscountAmount, v))
}

// RefundAmount applies equality check predicate on the "refund_amount" field. It's identical to RefundAmountEQ.
func RefundAmount(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldRefundAmount, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldPaidAt, v))
}

// ExportedAt applies equality check predicate on the "exported_at" field. It's identical to ExportedAtEQ.
func ExportedAt(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldExportedAt, v))
}

// CancelledAt applies equality check predicate on the "cancelled_at" field. It's identical to CancelledAtEQ.
func CancelledAt(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldCancelledAt, v))
}

// RefundedAt applies equality check predicate on the "refunded_at" field. It's identical to RefundedAtEQ.
func RefundedAt(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldRefundedAt, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldKind, v))
}

// OriginCode applies equality check predicate on the "origin_code" field. It's identical to OriginCodeEQ.
func OriginCode(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldOriginCode, v))
}

// OriginName applies equality check predicate on the "origin_name" field. It's identical to OriginNameEQ.
func OriginName(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldOriginName, v))
}

// DestCode applies equality check predicate on the "dest_code" field. It's identical to DestCodeEQ.
func DestCode(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDestCode, v))
}

// DestName applies equality check predicate on the "dest_name" field. It's identical to DestNameEQ.
func DestName(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDestName, v))
}

// DistanceKm applies equality check predicate on the "distance_km" field. It's identical to DistanceKmEQ.
func DistanceKm(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDistanceKm, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDurationMs, v))
}

// WayID applies equality check predicate on the "way_id" field. It's identical to WayIDEQ.
func WayID(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldWayID, v))
}

// WayName applies equality check predicate on the "way_name" field. It's identical to WayNameEQ.
func WayName(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldWayName, v))
}

// PickupID applies equality check predicate on the "pickup_id" field. It's identical to PickupIDEQ.
func PickupID(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldPickupID, v))
}

// PickupName applies equality check predicate on the "pickup_name" field. It's identical to PickupNameEQ.
func PickupName(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldPickupName, v))
}

// PickupAddress applies equality check predicate on the "pickup_address" field. It's identical to PickupAddressEQ.
func PickupAddress(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldPickupAddress, v))
}

// DropOffID applies equality check predicate on the "drop_off_id" field. It's identical to DropOffIDEQ.
func DropOffID(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDropOffID, v))
}

// DropOffName applies equality check predicate on the "drop_off_name" field. It's identical to DropOffNameEQ.
func DropOffName(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDropOffName, v))
}

// DropOffAddress applies equality check predicate on the "drop_off_address" field. It's identical to DropOffAddressEQ.
func DropOffAddress(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDropOffAddress, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldUpdatedAt, v))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v uuid.UUID) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v uuid.UUID) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...uuid.UUID) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...uuid.UUID) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldTicketID, vs...))
}

// RouteIDEQ applies the EQ predicate on the "route_id" field.
func RouteIDEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldRouteID, v))
}

// RouteIDNEQ applies the NEQ predicate on the "route_id" field.
func RouteIDNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldRouteID, v))
}

// RouteIDIn applies the In predicate on the "route_id" field.
func RouteIDIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldRouteID, vs...))
}

// RouteIDNotIn applies the NotIn predicate on the "route_id" field.
func RouteIDNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldRouteID, vs...))
}

// RouteIDGT applies the GT predicate on the "route_id" field.
func RouteIDGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldRouteID, v))
}

// RouteIDGTE applies the GTE predicate on the "route_id" field.
func RouteIDGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldRouteID, v))
}

// RouteIDLT applies the LT predicate on the "route_id" field.
func RouteIDLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldRouteID, v))
}

// RouteIDLTE applies the LTE predicate on the "route_id" field.
func RouteIDLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldRouteID, v))
}

// RouteIDContains applies the Contains predicate on the "route_id" field.
func RouteIDContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldRouteID, v))
}

// RouteIDHasPrefix applies the HasPrefix predicate on the "route_id" field.
func RouteIDHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldRouteID, v))
}

// RouteIDHasSuffix applies the HasSuffix predicate on the "route_id" field.
func RouteIDHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldRouteID, v))
}

// RouteIDEqualFold applies the EqualFold predicate on the "route_id" field.
func RouteIDEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldRouteID, v))
}

// RouteIDContainsFold applies the ContainsFold predicate on the "route_id" field.
func RouteIDContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldRouteID, v))
}

// SeatTypeEQ applies the EQ predicate on the "seat_type" field.
func SeatTypeEQ(v SeatType) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldSeatType, v))
}

// SeatTypeNEQ applies the NEQ predicate on the "seat_type" field.
func SeatTypeNEQ(v SeatType) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldSeatType, v))
}

// SeatTypeIn applies the In predicate on the "seat_type" field.
func SeatTypeIn(vs ...SeatType) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldSeatType, vs...))
}

// SeatTypeNotIn applies the NotIn predicate on the "seat_type" field.
func SeatTypeNotIn(vs ...SeatType) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldSeatType, vs...))
}

// RouteNameEQ applies the EQ predicate on the "route_name" field.
func RouteNameEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldRouteName, v))
}

// RouteNameNEQ applies the NEQ predicate on the "route_name" field.
func RouteNameNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldRouteName, v))
}

// RouteNameIn applies the In predicate on the "route_name" field.
func RouteNameIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldRouteName, vs...))
}

// RouteNameNotIn applies the NotIn predicate on the "route_name" field.
func RouteNameNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldRouteName, vs...))
}

// RouteNameGT applies the GT predicate on the "route_name" field.
func RouteNameGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldRouteName, v))
}

// RouteNameGTE applies the GTE predicate on the "route_name" field.
func RouteNameGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldRouteName, v))
}

// RouteNameLT applies the LT predicate on the "route_name" field.
func RouteNameLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldRouteName, v))
}

// RouteNameLTE applies the LTE predicate on the "route_name" field.
func RouteNameLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldRouteName, v))
}

// RouteNameContains applies the Contains predicate on the "route_name" field.
func RouteNameContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldRouteName, v))
}

// RouteNameHasPrefix applies the HasPrefix predicate on the "route_name" field.
func RouteNameHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldRouteName, v))
}

// RouteNameHasSuffix applies the HasSuffix predicate on the "route_name" field.
func RouteNameHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldRouteName, v))
}

// RouteNameEqualFold applies the EqualFold predicate on the "route_name" field.
func RouteNameEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldRouteName, v))
}

// RouteNameContainsFold applies the ContainsFold predicate on the "route_name" field.
func RouteNameContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldRouteName, v))
}

// DepartureTimeEQ applies the EQ predicate on the "departure_time" field.
func DepartureTimeEQ(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDepartureTime, v))
}

// DepartureTimeNEQ applies the NEQ predicate on the "departure_time" field.
func DepartureTimeNEQ(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldDepartureTime, v))
}

// DepartureTimeIn applies the In predicate on the "departure_time" field.
func DepartureTimeIn(vs ...time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldDepartureTime, vs...))
}

// DepartureTimeNotIn applies the NotIn predicate on the "departure_time" field.
func DepartureTimeNotIn(vs ...time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldDepartureTime, vs...))
}

// DepartureTimeGT applies the GT predicate on the "departure_time" field.
func DepartureTimeGT(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldDepartureTime, v))
}

// DepartureTimeGTE applies the GTE predicate on the "departure_time" field.
func DepartureTimeGTE(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldDepartureTime, v))
}

// DepartureTimeLT applies the LT predicate on the "departure_time" field.
func DepartureTimeLT(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldDepartureTime, v))
}

// DepartureTimeLTE applies the LTE predicate on the "departure_time" field.
func DepartureTimeLTE(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldDepartureTime, v))
}

// TripIDEQ applies the EQ predicate on the "trip_id" field.
func TripIDEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldTripID, v))
}

// TripIDNEQ applies the NEQ predicate on the "trip_id" field.
func TripIDNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldTripID, v))
}

// TripIDIn applies the In predicate on the "trip_id" field.
func TripIDIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldTripID, vs...))
}

// TripIDNotIn applies the NotIn predicate on the "trip_id" field.
func TripIDNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldTripID, vs...))
}

// TripIDGT applies the GT predicate on the "trip_id" field.
func TripIDGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldTripID, v))
}

// TripIDGTE applies the GTE predicate on the "trip_id" field.
func TripIDGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldTripID, v))
}

// TripIDLT applies the LT predicate on the "trip_id" field.
func TripIDLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldTripID, v))
}

// TripIDLTE applies the LTE predicate on the "trip_id" field.
func TripIDLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldTripID, v))
}

// TripIDContains applies the Contains predicate on the "trip_id" field.
func TripIDContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldTripID, v))
}

// TripIDHasPrefix applies the HasPrefix predicate on the "trip_id" field.
func TripIDHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldTripID, v))
}

// TripIDHasSuffix applies the HasSuffix predicate on the "trip_id" field.
func TripIDHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldTripID, v))
}

// TripIDIsNil applies the IsNil predicate on the "trip_id" field.
func TripIDIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldTripID))
}

// TripIDNotNil applies the NotNil predicate on the "trip_id" field.
func TripIDNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldTripID))
}

// TripIDEqualFold applies the EqualFold predicate on the "trip_id" field.
func TripIDEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldTripID, v))
}

// TripIDContainsFold applies the ContainsFold predicate on the "trip_id" field.
func TripIDContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldTripID, v))
}

// SeatIDEQ applies the EQ predicate on the "seat_id" field.
func SeatIDEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldSeatID, v))
}

// SeatIDNEQ applies the NEQ predicate on the "seat_id" field.
func SeatIDNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldSeatID, v))
}

// SeatIDIn applies the In predicate on the "seat_id" field.
func SeatIDIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldSeatID, vs...))
}

// SeatIDNotIn applies the NotIn predicate on the "seat_id" field.
func SeatIDNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldSeatID, vs...))
}

// SeatIDGT applies the GT predicate on the "seat_id" field.
func SeatIDGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldSeatID, v))
}

// SeatIDGTE applies the GTE predicate on the "seat_id" field.
func SeatIDGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldSeatID, v))
}

// SeatIDLT applies the LT predicate on the "seat_id" field.
func SeatIDLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldSeatID, v))
}

// SeatIDLTE applies the LTE predicate on the "seat_id" field.
func SeatIDLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldSeatID, v))
}

// SeatIDContains applies the Contains predicate on the "seat_id" field.
func SeatIDContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldSeatID, v))
}

// SeatIDHasPrefix applies the HasPrefix predicate on the "seat_id" field.
func SeatIDHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldSeatID, v))
}

// SeatIDHasSuffix applies the HasSuffix predicate on the "seat_id" field.
func SeatIDHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldSeatID, v))
}

// SeatIDEqualFold applies the EqualFold predicate on the "seat_id" field.
func SeatIDEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldSeatID, v))
}

// SeatIDContainsFold applies the ContainsFold predicate on the "seat_id" field.
func SeatIDContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldSeatID, v))
}

// SeatNameEQ applies the EQ predicate on the "seat_name" field.
func SeatNameEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldSeatName, v))
}

// SeatNameNEQ applies the NEQ predicate on the "seat_name" field.
func SeatNameNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldSeatName, v))
}

// SeatNameIn applies the In predicate on the "seat_name" field.
func SeatNameIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldSeatName, vs...))
}

// SeatNameNotIn applies the NotIn predicate on the "seat_name" field.
func SeatNameNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldSeatName, vs...))
}

// SeatNameGT applies the GT predicate on the "seat_name" field.
func SeatNameGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldSeatName, v))
}

// SeatNameGTE applies the GTE predicate on the "seat_name" field.
func SeatNameGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldSeatName, v))
}

// SeatNameLT applies the LT predicate on the "seat_name" field.
func SeatNameLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldSeatName, v))
}

// SeatNameLTE applies the LTE predicate on the "seat_name" field.
func SeatNameLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldSeatName, v))
}

// SeatNameContains applies the Contains predicate on the "seat_name" field.
func SeatNameContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldSeatName, v))
}

// SeatNameHasPrefix applies the HasPrefix predicate on the "seat_name" field.
func SeatNameHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldSeatName, v))
}

// SeatNameHasSuffix applies the HasSuffix predicate on the "seat_name" field.
func SeatNameHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldSeatName, v))
}

// SeatNameEqualFold applies the EqualFold predicate on the "seat_name" field.
func SeatNameEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldSeatName, v))
}

// SeatNameContainsFold applies the ContainsFold predicate on the "seat_name" field.
func SeatNameContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldSeatName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldStatus, vs...))
}

// OriginAmountEQ applies the EQ predicate on the "origin_amount" field.
func OriginAmountEQ(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldOriginAmount, v))
}

// OriginAmountNEQ applies the NEQ predicate on the "origin_amount" field.
func OriginAmountNEQ(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldOriginAmount, v))
}

// OriginAmountIn applies the In predicate on the "origin_amount" field.
func OriginAmountIn(vs ...float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldOriginAmount, vs...))
}

// OriginAmountNotIn applies the NotIn predicate on the "origin_amount" field.
func OriginAmountNotIn(vs ...float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldOriginAmount, vs...))
}

// OriginAmountGT applies the GT predicate on the "origin_amount" field.
func OriginAmountGT(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldOriginAmount, v))
}

// OriginAmountGTE applies the GTE predicate on the "origin_amount" field.
func OriginAmountGTE(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldOriginAmount, v))
}

// OriginAmountLT applies the LT predicate on the "origin_amount" field.
func OriginAmountLT(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldOriginAmount, v))
}

// OriginAmountLTE applies the LTE predicate on the "origin_amount" field.
func OriginAmountLTE(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldOriginAmount, v))
}

// DiscountAmountEQ applies the EQ predicate on the "discount_amount" field.
func DiscountAmountEQ(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDiscountAmount, v))
}

// DiscountAmountNEQ applies the NEQ predicate on the "discount_amount" field.
func DiscountAmountNEQ(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldDiscountAmount, v))
}

// DiscountAmountIn applies the In predicate on the "discount_amount" field.
func DiscountAmountIn(vs ...float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldDiscountAmount, vs...))
}

// DiscountAmountNotIn applies the NotIn predicate on the "discount_amount" field.
func DiscountAmountNotIn(vs ...float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldDiscountAmount, vs...))
}

// DiscountAmountGT applies the GT predicate on the "discount_amount" field.
func DiscountAmountGT(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldDiscountAmount, v))
}

// DiscountAmountGTE applies the GTE predicate on the "discount_amount" field.
func DiscountAmountGTE(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldDiscountAmount, v))
}

// DiscountAmountLT applies the LT predicate on the "discount_amount" field.
func DiscountAmountLT(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldDiscountAmount, v))
}

// DiscountAmountLTE applies the LTE predicate on the "discount_amount" field.
func DiscountAmountLTE(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldDiscountAmount, v))
}

// RefundAmountEQ applies the EQ predicate on the "refund_amount" field.
func RefundAmountEQ(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldRefundAmount, v))
}

// RefundAmountNEQ applies the NEQ predicate on the "refund_amount" field.
func RefundAmountNEQ(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldRefundAmount, v))
}

// RefundAmountIn applies the In predicate on the "refund_amount" field.
func RefundAmountIn(vs ...float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldRefundAmount, vs...))
}

// RefundAmountNotIn applies the NotIn predicate on the "refund_amount" field.
func RefundAmountNotIn(vs ...float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldRefundAmount, vs...))
}

// RefundAmountGT applies the GT predicate on the "refund_amount" field.
func RefundAmountGT(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldRefundAmount, v))
}

// RefundAmountGTE applies the GTE predicate on the "refund_amount" field.
func RefundAmountGTE(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldRefundAmount, v))
}

// RefundAmountLT applies the LT predicate on the "refund_amount" field.
func RefundAmountLT(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldRefundAmount, v))
}

// RefundAmountLTE applies the LTE predicate on the "refund_amount" field.
func RefundAmountLTE(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldRefundAmount, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldPaidAt))
}

// ExportedAtEQ applies the EQ predicate on the "exported_at" field.
func ExportedAtEQ(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldExportedAt, v))
}

// ExportedAtNEQ applies the NEQ predicate on the "exported_at" field.
func ExportedAtNEQ(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldExportedAt, v))
}

// ExportedAtIn applies the In predicate on the "exported_at" field.
func ExportedAtIn(vs ...time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldExportedAt, vs...))
}

// ExportedAtNotIn applies the NotIn predicate on the "exported_at" field.
func ExportedAtNotIn(vs ...time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldExportedAt, vs...))
}

// ExportedAtGT applies the GT predicate on the "exported_at" field.
func ExportedAtGT(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldExportedAt, v))
}

// ExportedAtGTE applies the GTE predicate on the "exported_at" field.
func ExportedAtGTE(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldExportedAt, v))
}

// ExportedAtLT applies the LT predicate on the "exported_at" field.
func ExportedAtLT(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldExportedAt, v))
}

// ExportedAtLTE applies the LTE predicate on the "exported_at" field.
func ExportedAtLTE(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldExportedAt, v))
}

// ExportedAtIsNil applies the IsNil predicate on the "exported_at" field.
func ExportedAtIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldExportedAt))
}

// ExportedAtNotNil applies the NotNil predicate on the "exported_at" field.
func ExportedAtNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldExportedAt))
}

// CancelledAtEQ applies the EQ predicate on the "cancelled_at" field.
func CancelledAtEQ(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldCancelledAt, v))
}

// CancelledAtNEQ applies the NEQ predicate on the "cancelled_at" field.
func CancelledAtNEQ(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldCancelledAt, v))
}

// CancelledAtIn applies the In predicate on the "cancelled_at" field.
func CancelledAtIn(vs ...time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldCancelledAt, vs...))
}

// CancelledAtNotIn applies the NotIn predicate on the "cancelled_at" field.
func CancelledAtNotIn(vs ...time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldCancelledAt, vs...))
}

// CancelledAtGT applies the GT predicate on the "cancelled_at" field.
func CancelledAtGT(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldCancelledAt, v))
}

// CancelledAtGTE applies the GTE predicate on the "cancelled_at" field.
func CancelledAtGTE(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldCancelledAt, v))
}

// CancelledAtLT applies the LT predicate on the "cancelled_at" field.
func CancelledAtLT(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldCancelledAt, v))
}

// CancelledAtLTE applies the LTE predicate on the "cancelled_at" field.
func CancelledAtLTE(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldCancelledAt, v))
}

// CancelledAtIsNil applies the IsNil predicate on the "cancelled_at" field.
func CancelledAtIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldCancelledAt))
}

// CancelledAtNotNil applies the NotNil predicate on the "cancelled_at" field.
func CancelledAtNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldCancelledAt))
}

// RefundedAtEQ applies the EQ predicate on the "refunded_at" field.
func RefundedAtEQ(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldRefundedAt, v))
}

// RefundedAtNEQ applies the NEQ predicate on the "refunded_at" field.
func RefundedAtNEQ(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldRefundedAt, v))
}

// RefundedAtIn applies the In predicate on the "refunded_at" field.
func RefundedAtIn(vs ...time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldRefundedAt, vs...))
}

// RefundedAtNotIn applies the NotIn predicate on the "refunded_at" field.
func RefundedAtNotIn(vs ...time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldRefundedAt, vs...))
}

// RefundedAtGT applies the GT predicate on the "refunded_at" field.
func RefundedAtGT(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldRefundedAt, v))
}

// RefundedAtGTE applies the GTE predicate on the "refunded_at" field.
func RefundedAtGTE(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldRefundedAt, v))
}

// RefundedAtLT applies the LT predicate on the "refunded_at" field.
func RefundedAtLT(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldRefundedAt, v))
}

// RefundedAtLTE applies the LTE predicate on the "refunded_at" field.
func RefundedAtLTE(v time.Time) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldRefundedAt, v))
}

// RefundedAtIsNil applies the IsNil predicate on the "refunded_at" field.
func RefundedAtIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldRefundedAt))
}

// RefundedAtNotNil applies the NotNil predicate on the "refunded_at" field.
func RefundedAtNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldRefundedAt))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldKind, v))
}

// KindIsNil applies the IsNil predicate on the "kind" field.
func KindIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldKind))
}

// KindNotNil applies the NotNil predicate on the "kind" field.
func KindNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldKind))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldKind, v))
}

// OriginCodeEQ applies the EQ predicate on the "origin_code" field.
func OriginCodeEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldOriginCode, v))
}

// OriginCodeNEQ applies the NEQ predicate on the "origin_code" field.
func OriginCodeNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldOriginCode, v))
}

// OriginCodeIn applies the In predicate on the "origin_code" field.
func OriginCodeIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldOriginCode, vs...))
}

// OriginCodeNotIn applies the NotIn predicate on the "origin_code" field.
func OriginCodeNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldOriginCode, vs...))
}

// OriginCodeGT applies the GT predicate on the "origin_code" field.
func OriginCodeGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldOriginCode, v))
}

// OriginCodeGTE applies the GTE predicate on the "origin_code" field.
func OriginCodeGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldOriginCode, v))
}

// OriginCodeLT applies the LT predicate on the "origin_code" field.
func OriginCodeLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldOriginCode, v))
}

// OriginCodeLTE applies the LTE predicate on the "origin_code" field.
func OriginCodeLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldOriginCode, v))
}

// OriginCodeContains applies the Contains predicate on the "origin_code" field.
func OriginCodeContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldOriginCode, v))
}

// OriginCodeHasPrefix applies the HasPrefix predicate on the "origin_code" field.
func OriginCodeHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldOriginCode, v))
}

// OriginCodeHasSuffix applies the HasSuffix predicate on the "origin_code" field.
func OriginCodeHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldOriginCode, v))
}

// OriginCodeIsNil applies the IsNil predicate on the "origin_code" field.
func OriginCodeIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldOriginCode))
}

// OriginCodeNotNil applies the NotNil predicate on the "origin_code" field.
func OriginCodeNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldOriginCode))
}

// OriginCodeEqualFold applies the EqualFold predicate on the "origin_code" field.
func OriginCodeEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldOriginCode, v))
}

// OriginCodeContainsFold applies the ContainsFold predicate on the "origin_code" field.
func OriginCodeContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldOriginCode, v))
}

// OriginNameEQ applies the EQ predicate on the "origin_name" field.
func OriginNameEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldOriginName, v))
}

// OriginNameNEQ applies the NEQ predicate on the "origin_name" field.
func OriginNameNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldOriginName, v))
}

// OriginNameIn applies the In predicate on the "origin_name" field.
func OriginNameIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldOriginName, vs...))
}

// OriginNameNotIn applies the NotIn predicate on the "origin_name" field.
func OriginNameNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldOriginName, vs...))
}

// OriginNameGT applies the GT predicate on the "origin_name" field.
func OriginNameGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldOriginName, v))
}

// OriginNameGTE applies the GTE predicate on the "origin_name" field.
func OriginNameGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldOriginName, v))
}

// OriginNameLT applies the LT predicate on the "origin_name" field.
func OriginNameLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldOriginName, v))
}

// OriginNameLTE applies the LTE predicate on the "origin_name" field.
func OriginNameLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldOriginName, v))
}

// OriginNameContains applies the Contains predicate on the "origin_name" field.
func OriginNameContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldOriginName, v))
}

// OriginNameHasPrefix applies the HasPrefix predicate on the "origin_name" field.
func OriginNameHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldOriginName, v))
}

// OriginNameHasSuffix applies the HasSuffix predicate on the "origin_name" field.
func OriginNameHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldOriginName, v))
}

// OriginNameIsNil applies the IsNil predicate on the "origin_name" field.
func OriginNameIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldOriginName))
}

// OriginNameNotNil applies the NotNil predicate on the "origin_name" field.
func OriginNameNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldOriginName))
}

// OriginNameEqualFold applies the EqualFold predicate on the "origin_name" field.
func OriginNameEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldOriginName, v))
}

// OriginNameContainsFold applies the ContainsFold predicate on the "origin_name" field.
func OriginNameContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldOriginName, v))
}

// DestCodeEQ applies the EQ predicate on the "dest_code" field.
func DestCodeEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDestCode, v))
}

// DestCodeNEQ applies the NEQ predicate on the "dest_code" field.
func DestCodeNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldDestCode, v))
}

// DestCodeIn applies the In predicate on the "dest_code" field.
func DestCodeIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldDestCode, vs...))
}

// DestCodeNotIn applies the NotIn predicate on the "dest_code" field.
func DestCodeNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldDestCode, vs...))
}

// DestCodeGT applies the GT predicate on the "dest_code" field.
func DestCodeGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldDestCode, v))
}

// DestCodeGTE applies the GTE predicate on the "dest_code" field.
func DestCodeGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldDestCode, v))
}

// DestCodeLT applies the LT predicate on the "dest_code" field.
func DestCodeLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldDestCode, v))
}

// DestCodeLTE applies the LTE predicate on the "dest_code" field.
func DestCodeLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldDestCode, v))
}

// DestCodeContains applies the Contains predicate on the "dest_code" field.
func DestCodeContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldDestCode, v))
}

// DestCodeHasPrefix applies the HasPrefix predicate on the "dest_code" field.
func DestCodeHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldDestCode, v))
}

// DestCodeHasSuffix applies the HasSuffix predicate on the "dest_code" field.
func DestCodeHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldDestCode, v))
}

// DestCodeIsNil applies the IsNil predicate on the "dest_code" field.
func DestCodeIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldDestCode))
}

// DestCodeNotNil applies the NotNil predicate on the "dest_code" field.
func DestCodeNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldDestCode))
}

// DestCodeEqualFold applies the EqualFold predicate on the "dest_code" field.
func DestCodeEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldDestCode, v))
}

// DestCodeContainsFold applies the ContainsFold predicate on the "dest_code" field.
func DestCodeContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldDestCode, v))
}

// DestNameEQ applies the EQ predicate on the "dest_name" field.
func DestNameEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDestName, v))
}

// DestNameNEQ applies the NEQ predicate on the "dest_name" field.
func DestNameNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldDestName, v))
}

// DestNameIn applies the In predicate on the "dest_name" field.
func DestNameIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldDestName, vs...))
}

// DestNameNotIn applies the NotIn predicate on the "dest_name" field.
func DestNameNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldDestName, vs...))
}

// DestNameGT applies the GT predicate on the "dest_name" field.
func DestNameGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldDestName, v))
}

// DestNameGTE applies the GTE predicate on the "dest_name" field.
func DestNameGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldDestName, v))
}

// DestNameLT applies the LT predicate on the "dest_name" field.
func DestNameLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldDestName, v))
}

// DestNameLTE applies the LTE predicate on the "dest_name" field.
func DestNameLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldDestName, v))
}

// DestNameContains applies the Contains predicate on the "dest_name" field.
func DestNameContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldDestName, v))
}

// DestNameHasPrefix applies the HasPrefix predicate on the "dest_name" field.
func DestNameHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldDestName, v))
}

// DestNameHasSuffix applies the HasSuffix predicate on the "dest_name" field.
func DestNameHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldDestName, v))
}

// DestNameIsNil applies the IsNil predicate on the "dest_name" field.
func DestNameIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldDestName))
}

// DestNameNotNil applies the NotNil predicate on the "dest_name" field.
func DestNameNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldDestName))
}

// DestNameEqualFold applies the EqualFold predicate on the "dest_name" field.
func DestNameEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldDestName, v))
}

// DestNameContainsFold applies the ContainsFold predicate on the "dest_name" field.
func DestNameContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldDestName, v))
}

// DistanceKmEQ applies the EQ predicate on the "distance_km" field.
func DistanceKmEQ(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDistanceKm, v))
}

// DistanceKmNEQ applies the NEQ predicate on the "distance_km" field.
func DistanceKmNEQ(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldDistanceKm, v))
}

// DistanceKmIn applies the In predicate on the "distance_km" field.
func DistanceKmIn(vs ...float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldDistanceKm, vs...))
}

// DistanceKmNotIn applies the NotIn predicate on the "distance_km" field.
func DistanceKmNotIn(vs ...float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldDistanceKm, vs...))
}

// DistanceKmGT applies the GT predicate on the "distance_km" field.
func DistanceKmGT(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldDistanceKm, v))
}

// DistanceKmGTE applies the GTE predicate on the "distance_km" field.
func DistanceKmGTE(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldDistanceKm, v))
}

// DistanceKmLT applies the LT predicate on the "distance_km" field.
func DistanceKmLT(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldDistanceKm, v))
}

// DistanceKmLTE applies the LTE predicate on the "distance_km" field.
func DistanceKmLTE(v float64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldDistanceKm, v))
}

// DistanceKmIsNil applies the IsNil predicate on the "distance_km" field.
func DistanceKmIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldDistanceKm))
}

// DistanceKmNotNil applies the NotNil predicate on the "distance_km" field.
func DistanceKmNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldDistanceKm))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldDurationMs))
}

// WayIDEQ applies the EQ predicate on the "way_id" field.
func WayIDEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldWayID, v))
}

// WayIDNEQ applies the NEQ predicate on the "way_id" field.
func WayIDNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldWayID, v))
}

// WayIDIn applies the In predicate on the "way_id" field.
func WayIDIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldWayID, vs...))
}

// WayIDNotIn applies the NotIn predicate on the "way_id" field.
func WayIDNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldWayID, vs...))
}

// WayIDGT applies the GT predicate on the "way_id" field.
func WayIDGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldWayID, v))
}

// WayIDGTE applies the GTE predicate on the "way_id" field.
func WayIDGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldWayID, v))
}

// WayIDLT applies the LT predicate on the "way_id" field.
func WayIDLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldWayID, v))
}

// WayIDLTE applies the LTE predicate on the "way_id" field.
func WayIDLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldWayID, v))
}

// WayIDContains applies the Contains predicate on the "way_id" field.
func WayIDContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldWayID, v))
}

// WayIDHasPrefix applies the HasPrefix predicate on the "way_id" field.
func WayIDHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldWayID, v))
}

// WayIDHasSuffix applies the HasSuffix predicate on the "way_id" field.
func WayIDHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldWayID, v))
}

// WayIDIsNil applies the IsNil predicate on the "way_id" field.
func WayIDIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldWayID))
}

// WayIDNotNil applies the NotNil predicate on the "way_id" field.
func WayIDNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldWayID))
}

// WayIDEqualFold applies the EqualFold predicate on the "way_id" field.
func WayIDEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldWayID, v))
}

// WayIDContainsFold applies the ContainsFold predicate on the "way_id" field.
func WayIDContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldWayID, v))
}

// WayNameEQ applies the EQ predicate on the "way_name" field.
func WayNameEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldWayName, v))
}

// WayNameNEQ applies the NEQ predicate on the "way_name" field.
func WayNameNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldWayName, v))
}

// WayNameIn applies the In predicate on the "way_name" field.
func WayNameIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldWayName, vs...))
}

// WayNameNotIn applies the NotIn predicate on the "way_name" field.
func WayNameNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldWayName, vs...))
}

// WayNameGT applies the GT predicate on the "way_name" field.
func WayNameGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldWayName, v))
}

// WayNameGTE applies the GTE predicate on the "way_name" field.
func WayNameGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldWayName, v))
}

// WayNameLT applies the LT predicate on the "way_name" field.
func WayNameLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldWayName, v))
}

// WayNameLTE applies the LTE predicate on the "way_name" field.
func WayNameLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldWayName, v))
}

// WayNameContains applies the Contains predicate on the "way_name" field.
func WayNameContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldWayName, v))
}

// WayNameHasPrefix applies the HasPrefix predicate on the "way_name" field.
func WayNameHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldWayName, v))
}

// WayNameHasSuffix applies the HasSuffix predicate on the "way_name" field.
func WayNameHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldWayName, v))
}

// WayNameIsNil applies the IsNil predicate on the "way_name" field.
func WayNameIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldWayName))
}

// WayNameNotNil applies the NotNil predicate on the "way_name" field.
func WayNameNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldWayName))
}

// WayNameEqualFold applies the EqualFold predicate on the "way_name" field.
func WayNameEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldWayName, v))
}

// WayNameContainsFold applies the ContainsFold predicate on the "way_name" field.
func WayNameContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldWayName, v))
}

// PickupTypeEQ applies the EQ predicate on the "pickup_type" field.
func PickupTypeEQ(v PickupType) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldPickupType, v))
}

// PickupTypeNEQ applies the NEQ predicate on the "pickup_type" field.
func PickupTypeNEQ(v PickupType) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldPickupType, v))
}

// PickupTypeIn applies the In predicate on the "pickup_type" field.
func PickupTypeIn(vs ...PickupType) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldPickupType, vs...))
}

// PickupTypeNotIn applies the NotIn predicate on the "pickup_type" field.
func PickupTypeNotIn(vs ...PickupType) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldPickupType, vs...))
}

// PickupTypeIsNil applies the IsNil predicate on the "pickup_type" field.
func PickupTypeIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldPickupType))
}

// PickupTypeNotNil applies the NotNil predicate on the "pickup_type" field.
func PickupTypeNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldPickupType))
}

// PickupIDEQ applies the EQ predicate on the "pickup_id" field.
func PickupIDEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldPickupID, v))
}

// PickupIDNEQ applies the NEQ predicate on the "pickup_id" field.
func PickupIDNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldPickupID, v))
}

// PickupIDIn applies the In predicate on the "pickup_id" field.
func PickupIDIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldPickupID, vs...))
}

// PickupIDNotIn applies the NotIn predicate on the "pickup_id" field.
func PickupIDNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldPickupID, vs...))
}

// PickupIDGT applies the GT predicate on the "pickup_id" field.
func PickupIDGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldPickupID, v))
}

// PickupIDGTE applies the GTE predicate on the "pickup_id" field.
func PickupIDGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldPickupID, v))
}

// PickupIDLT applies the LT predicate on the "pickup_id" field.
func PickupIDLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldPickupID, v))
}

// PickupIDLTE applies the LTE predicate on the "pickup_id" field.
func PickupIDLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldPickupID, v))
}

// PickupIDContains applies the Contains predicate on the "pickup_id" field.
func PickupIDContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldPickupID, v))
}

// PickupIDHasPrefix applies the HasPrefix predicate on the "pickup_id" field.
func PickupIDHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldPickupID, v))
}

// PickupIDHasSuffix applies the HasSuffix predicate on the "pickup_id" field.
func PickupIDHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldPickupID, v))
}

// PickupIDIsNil applies the IsNil predicate on the "pickup_id" field.
func PickupIDIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldPickupID))
}

// PickupIDNotNil applies the NotNil predicate on the "pickup_id" field.
func PickupIDNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldPickupID))
}

// PickupIDEqualFold applies the EqualFold predicate on the "pickup_id" field.
func PickupIDEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldPickupID, v))
}

// PickupIDContainsFold applies the ContainsFold predicate on the "pickup_id" field.
func PickupIDContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldPickupID, v))
}

// PickupNameEQ applies the EQ predicate on the "pickup_name" field.
func PickupNameEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldPickupName, v))
}

// PickupNameNEQ applies the NEQ predicate on the "pickup_name" field.
func PickupNameNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldPickupName, v))
}

// PickupNameIn applies the In predicate on the "pickup_name" field.
func PickupNameIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldPickupName, vs...))
}

// PickupNameNotIn applies the NotIn predicate on the "pickup_name" field.
func PickupNameNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldPickupName, vs...))
}

// PickupNameGT applies the GT predicate on the "pickup_name" field.
func PickupNameGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldPickupName, v))
}

// PickupNameGTE applies the GTE predicate on the "pickup_name" field.
func PickupNameGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldPickupName, v))
}

// PickupNameLT applies the LT predicate on the "pickup_name" field.
func PickupNameLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldPickupName, v))
}

// PickupNameLTE applies the LTE predicate on the "pickup_name" field.
func PickupNameLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldPickupName, v))
}

// PickupNameContains applies the Contains predicate on the "pickup_name" field.
func PickupNameContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldPickupName, v))
}

// PickupNameHasPrefix applies the HasPrefix predicate on the "pickup_name" field.
func PickupNameHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldPickupName, v))
}

// PickupNameHasSuffix applies the HasSuffix predicate on the "pickup_name" field.
func PickupNameHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldPickupName, v))
}

// PickupNameIsNil applies the IsNil predicate on the "pickup_name" field.
func PickupNameIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldPickupName))
}

// PickupNameNotNil applies the NotNil predicate on the "pickup_name" field.
func PickupNameNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldPickupName))
}

// PickupNameEqualFold applies the EqualFold predicate on the "pickup_name" field.
func PickupNameEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldPickupName, v))
}

// PickupNameContainsFold applies the ContainsFold predicate on the "pickup_name" field.
func PickupNameContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldPickupName, v))
}

// PickupAddressEQ applies the EQ predicate on the "pickup_address" field.
func PickupAddressEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldPickupAddress, v))
}

// PickupAddressNEQ applies the NEQ predicate on the "pickup_address" field.
func PickupAddressNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldPickupAddress, v))
}

// PickupAddressIn applies the In predicate on the "pickup_address" field.
func PickupAddressIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldPickupAddress, vs...))
}

// PickupAddressNotIn applies the NotIn predicate on the "pickup_address" field.
func PickupAddressNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldPickupAddress, vs...))
}

// PickupAddressGT applies the GT predicate on the "pickup_address" field.
func PickupAddressGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldPickupAddress, v))
}

// PickupAddressGTE applies the GTE predicate on the "pickup_address" field.
func PickupAddressGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldPickupAddress, v))
}

// PickupAddressLT applies the LT predicate on the "pickup_address" field.
func PickupAddressLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldPickupAddress, v))
}

// PickupAddressLTE applies the LTE predicate on the "pickup_address" field.
func PickupAddressLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldPickupAddress, v))
}

// PickupAddressContains applies the Contains predicate on the "pickup_address" field.
func PickupAddressContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldPickupAddress, v))
}

// PickupAddressHasPrefix applies the HasPrefix predicate on the "pickup_address" field.
func PickupAddressHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldPickupAddress, v))
}

// PickupAddressHasSuffix applies the HasSuffix predicate on the "pickup_address" field.
func PickupAddressHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldPickupAddress, v))
}

// PickupAddressIsNil applies the IsNil predicate on the "pickup_address" field.
func PickupAddressIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldPickupAddress))
}

// PickupAddressNotNil applies the NotNil predicate on the "pickup_address" field.
func PickupAddressNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldPickupAddress))
}

// PickupAddressEqualFold applies the EqualFold predicate on the "pickup_address" field.
func PickupAddressEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldPickupAddress, v))
}

// PickupAddressContainsFold applies the ContainsFold predicate on the "pickup_address" field.
func PickupAddressContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldPickupAddress, v))
}

// PickupInfoIsNil applies the IsNil predicate on the "pickup_info" field.
func PickupInfoIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldPickupInfo))
}

// PickupInfoNotNil applies the NotNil predicate on the "pickup_info" field.
func PickupInfoNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldPickupInfo))
}

// DropOffTypeEQ applies the EQ predicate on the "drop_off_type" field.
func DropOffTypeEQ(v DropOffType) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDropOffType, v))
}

// DropOffTypeNEQ applies the NEQ predicate on the "drop_off_type" field.
func DropOffTypeNEQ(v DropOffType) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldDropOffType, v))
}

// DropOffTypeIn applies the In predicate on the "drop_off_type" field.
func DropOffTypeIn(vs ...DropOffType) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldDropOffType, vs...))
}

// DropOffTypeNotIn applies the NotIn predicate on the "drop_off_type" field.
func DropOffTypeNotIn(vs ...DropOffType) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldDropOffType, vs...))
}

// DropOffTypeIsNil applies the IsNil predicate on the "drop_off_type" field.
func DropOffTypeIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldDropOffType))
}

// DropOffTypeNotNil applies the NotNil predicate on the "drop_off_type" field.
func DropOffTypeNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldDropOffType))
}

// DropOffIDEQ applies the EQ predicate on the "drop_off_id" field.
func DropOffIDEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDropOffID, v))
}

// DropOffIDNEQ applies the NEQ predicate on the "drop_off_id" field.
func DropOffIDNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldDropOffID, v))
}

// DropOffIDIn applies the In predicate on the "drop_off_id" field.
func DropOffIDIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldDropOffID, vs...))
}

// DropOffIDNotIn applies the NotIn predicate on the "drop_off_id" field.
func DropOffIDNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldDropOffID, vs...))
}

// DropOffIDGT applies the GT predicate on the "drop_off_id" field.
func DropOffIDGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldDropOffID, v))
}

// DropOffIDGTE applies the GTE predicate on the "drop_off_id" field.
func DropOffIDGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldDropOffID, v))
}

// DropOffIDLT applies the LT predicate on the "drop_off_id" field.
func DropOffIDLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldDropOffID, v))
}

// DropOffIDLTE applies the LTE predicate on the "drop_off_id" field.
func DropOffIDLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldDropOffID, v))
}

// DropOffIDContains applies the Contains predicate on the "drop_off_id" field.
func DropOffIDContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldDropOffID, v))
}

// DropOffIDHasPrefix applies the HasPrefix predicate on the "drop_off_id" field.
func DropOffIDHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldDropOffID, v))
}

// DropOffIDHasSuffix applies the HasSuffix predicate on the "drop_off_id" field.
func DropOffIDHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldDropOffID, v))
}

// DropOffIDIsNil applies the IsNil predicate on the "drop_off_id" field.
func DropOffIDIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldDropOffID))
}

// DropOffIDNotNil applies the NotNil predicate on the "drop_off_id" field.
func DropOffIDNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldDropOffID))
}

// DropOffIDEqualFold applies the EqualFold predicate on the "drop_off_id" field.
func DropOffIDEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldDropOffID, v))
}

// DropOffIDContainsFold applies the ContainsFold predicate on the "drop_off_id" field.
func DropOffIDContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldDropOffID, v))
}

// DropOffNameEQ applies the EQ predicate on the "drop_off_name" field.
func DropOffNameEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDropOffName, v))
}

// DropOffNameNEQ applies the NEQ predicate on the "drop_off_name" field.
func DropOffNameNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldDropOffName, v))
}

// DropOffNameIn applies the In predicate on the "drop_off_name" field.
func DropOffNameIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldDropOffName, vs...))
}

// DropOffNameNotIn applies the NotIn predicate on the "drop_off_name" field.
func DropOffNameNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldDropOffName, vs...))
}

// DropOffNameGT applies the GT predicate on the "drop_off_name" field.
func DropOffNameGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldDropOffName, v))
}

// DropOffNameGTE applies the GTE predicate on the "drop_off_name" field.
func DropOffNameGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldDropOffName, v))
}

// DropOffNameLT applies the LT predicate on the "drop_off_name" field.
func DropOffNameLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldDropOffName, v))
}

// DropOffNameLTE applies the LTE predicate on the "drop_off_name" field.
func DropOffNameLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldDropOffName, v))
}

// DropOffNameContains applies the Contains predicate on the "drop_off_name" field.
func DropOffNameContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldDropOffName, v))
}

// DropOffNameHasPrefix applies the HasPrefix predicate on the "drop_off_name" field.
func DropOffNameHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldDropOffName, v))
}

// DropOffNameHasSuffix applies the HasSuffix predicate on the "drop_off_name" field.
func DropOffNameHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldDropOffName, v))
}

// DropOffNameIsNil applies the IsNil predicate on the "drop_off_name" field.
func DropOffNameIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldDropOffName))
}

// DropOffNameNotNil applies the NotNil predicate on the "drop_off_name" field.
func DropOffNameNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldDropOffName))
}

// DropOffNameEqualFold applies the EqualFold predicate on the "drop_off_name" field.
func DropOffNameEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldDropOffName, v))
}

// DropOffNameContainsFold applies the ContainsFold predicate on the "drop_off_name" field.
func DropOffNameContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldDropOffName, v))
}

// DropOffAddressEQ applies the EQ predicate on the "drop_off_address" field.
func DropOffAddressEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEQ(FieldDropOffAddress, v))
}

// DropOffAddressNEQ applies the NEQ predicate on the "drop_off_address" field.
func DropOffAddressNEQ(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNEQ(FieldDropOffAddress, v))
}

// DropOffAddressIn applies the In predicate on the "drop_off_address" field.
func DropOffAddressIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIn(FieldDropOffAddress, vs...))
}

// DropOffAddressNotIn applies the NotIn predicate on the "drop_off_address" field.
func DropOffAddressNotIn(vs ...string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotIn(FieldDropOffAddress, vs...))
}

// DropOffAddressGT applies the GT predicate on the "drop_off_address" field.
func DropOffAddressGT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGT(FieldDropOffAddress, v))
}

// DropOffAddressGTE applies the GTE predicate on the "drop_off_address" field.
func DropOffAddressGTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldGTE(FieldDropOffAddress, v))
}

// DropOffAddressLT applies the LT predicate on the "drop_off_address" field.
func DropOffAddressLT(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLT(FieldDropOffAddress, v))
}

// DropOffAddressLTE applies the LTE predicate on the "drop_off_address" field.
func DropOffAddressLTE(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldLTE(FieldDropOffAddress, v))
}

// DropOffAddressContains applies the Contains predicate on the "drop_off_address" field.
func DropOffAddressContains(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContains(FieldDropOffAddress, v))
}

// DropOffAddressHasPrefix applies the HasPrefix predicate on the "drop_off_address" field.
func DropOffAddressHasPrefix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasPrefix(FieldDropOffAddress, v))
}

// DropOffAddressHasSuffix applies the HasSuffix predicate on the "drop_off_address" field.
func DropOffAddressHasSuffix(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldHasSuffix(FieldDropOffAddress, v))
}

// DropOffAddressIsNil applies the IsNil predicate on the "drop_off_address" field.
func DropOffAddressIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldDropOffAddress))
}

// DropOffAddressNotNil applies the NotNil predicate on the "drop_off_address" field.
func DropOffAddressNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldDropOffAddress))
}

// DropOffAddressEqualFold applies the EqualFold predicate on the "drop_off_address" field.
func DropOffAddressEqualFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldEqualFold(FieldDropOffAddress, v))
}

// DropOffAddressContainsFold applies the ContainsFold predicate on the "drop_off_address" field.
func DropOffAddressContainsFold(v string) predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldContainsFold(FieldDropOffAddress, v))
}

// DropOffInfoIsNil applies the IsNil predicate on the "drop_off_info" field.
func DropOffInfoIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldDropOffInfo))
}

// DropOffInfoNotNil applies the NotNil predicate on the "drop_off_info" field.
func DropOffInfoNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldDropOffInfo))
}

// ExtraDataIsNil applies the IsNil predicate on the "extra_data" field.
func ExtraDataIsNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldIsNull(FieldExtraData))
}

// ExtraDataNotNil applies the NotNil predicate on the "extra_data" field.
func ExtraDataNotNil() predicate.TicketSeat {
	return predicate.TicketSeat(sql.FieldNotNull(FieldExtraData))
}

// HasTicket applies the HasEdge predicate on the "ticket" edge.
func HasTicket() predicate.TicketSeat {
	return predicate.TicketSeat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Ticket
		step.Edge.Schema = schemaConfig.TicketSeat
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketWith applies the HasEdge predicate on the "ticket" edge with a given conditions (other predicates).
func HasTicketWith(preds ...predicate.Ticket) predicate.TicketSeat {
	return predicate.TicketSeat(func(s *sql.Selector) {
		step := newTicketStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Ticket
		step.Edge.Schema = schemaConfig.TicketSeat
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TicketSeat) predicate.TicketSeat {
	return predicate.TicketSeat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TicketSeat) predicate.TicketSeat {
	return predicate.TicketSeat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TicketSeat) predicate.TicketSeat {
	return predicate.TicketSeat(sql.NotPredicates(p))
}
