package constant

import (
	"fmt"
)

// TableWithPrefix generates a table name with the specified module, function, and name.
// This is useful for organizing tables in a way that reflects their purpose and origin.
// The format is: "{module}_{function}__{name}".
// For example, if the module is "smp", the function is "iam", and the name is "users",
// the resulting table name would be "smp_iam__users".
// This helps in maintaining a clear structure in the database ent_schema, especially when
// dealing with multiple modules and functions that may have similar or overlapping names.
// It is particularly useful in larger applications where different components may need
// to interact with the database in a modular way, allowing for better organization and
// easier identification of tables related to specific functionalities.
func TableWithPrefix(module, function, name string) string {
	return fmt.Sprintf("%s%s", tablePrefix(module, function), name)
}

// tablePrefix generates a prefix for a table based on the module and function.
// This prefix can be used to create a consistent naming convention for tables
// that belong to specific modules and functions within the application.
// The format is: "{module}_{function}__".
// For example, if the module is "smp" and the function is "iam", the resulting prefix
// would be "smp_iam__". This is useful for ensuring that tables are easily identifiable
// and organized according to their respective modules and functions, especially in
// larger applications where multiple modules may interact with the database.
func tablePrefix(module, function string) string {
	return fmt.Sprintf("%s_%s__", module, function)
}

// InitTablePrefix initializes a list of table prefixes based on predefined module-function pairs.
// It returns a slice of strings where each string is a table name generated by
// the `tableWithPrefix` function using the specified module and function constants.
func InitTablePrefix() []string {
	pairs := [][2]string{
		{"VATO", BOOKING},
		// TODO: Add more pairs as needed
	}

	prefixes := make([]string, 0, len(pairs))
	for _, p := range pairs {
		prefixes = append(prefixes, tablePrefix(p[0], p[1]))
	}
	return prefixes
}
