// Code generated by novaerp.com, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TicketsColumns holds the columns for the "tickets" table.
	TicketsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUUID, Nullable: true},
		{Name: "code", Type: field.TypeString, Size: 20},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"unknown", "cancel_by_app_vato", "cancel_by_futa", "booking", "processing_booking", "payment_success", "payment_fail", "completed", "update_by_futa", "ticket_was_changed", "booking_cancel_admin", "cash_back", "processing_callback", "expired"}, Default: "unknown"},
		{Name: "way_type", Type: field.TypeEnum, Enums: []string{"one_way", "round_trip"}, Default: "one_way"},
		{Name: "booking_channel", Type: field.TypeEnum, Enums: []string{"unknown", "web_client", "mobile_app", "kiosk_app"}, Default: "unknown"},
		{Name: "payment_method", Type: field.TypeInt, Default: 0},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "promotion_code", Type: field.TypeString, Nullable: true},
		{Name: "departure_times", Type: field.TypeJSON},
		{Name: "origin_amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "numeric(18,2)"}},
		{Name: "discount_amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "numeric(18,2)"}},
		{Name: "refund_amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "numeric(18,2)"}},
		{Name: "remarks", Type: field.TypeString, Nullable: true},
		{Name: "reference_user_id", Type: field.TypeString},
		{Name: "reference_phone", Type: field.TypeString},
		{Name: "reference_migration_id", Type: field.TypeString, Nullable: true},
		{Name: "force_updated_user_id", Type: field.TypeString, Nullable: true},
	}
	// TicketsTable holds the schema information for the "tickets" table.
	TicketsTable = &schema.Table{
		Name:       "tickets",
		Columns:    TicketsColumns,
		PrimaryKey: []*schema.Column{TicketsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ticket_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{TicketsColumns[3]},
			},
			{
				Name:    "ticket_tenant_id_code",
				Unique:  true,
				Columns: []*schema.Column{TicketsColumns[3], TicketsColumns[4]},
			},
			{
				Name:    "ticket_code",
				Unique:  false,
				Columns: []*schema.Column{TicketsColumns[4]},
			},
			{
				Name:    "ticket_code_status",
				Unique:  false,
				Columns: []*schema.Column{TicketsColumns[4], TicketsColumns[5]},
			},
			{
				Name:    "ticket_reference_user_id",
				Unique:  false,
				Columns: []*schema.Column{TicketsColumns[16]},
			},
		},
	}
	// TicketSeatsColumns holds the columns for the "ticket_seats" table.
	TicketSeatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "route_id", Type: field.TypeString, Size: 50},
		{Name: "seat_type", Type: field.TypeEnum, Enums: []string{"outbound", "return"}, Default: "outbound"},
		{Name: "route_name", Type: field.TypeString},
		{Name: "departure_time", Type: field.TypeTime},
		{Name: "trip_id", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "seat_id", Type: field.TypeString, Size: 50},
		{Name: "seat_name", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"initial", "paid", "exported", "cancelled", "refunded", "created_by_futa", "cancelled_by_futa"}, Default: "initial"},
		{Name: "origin_amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "numeric(18,2)"}},
		{Name: "discount_amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "numeric(18,2)"}},
		{Name: "refund_amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "numeric(18,2)"}},
		{Name: "paid_at", Type: field.TypeTime, Nullable: true},
		{Name: "exported_at", Type: field.TypeTime, Nullable: true},
		{Name: "cancelled_at", Type: field.TypeTime, Nullable: true},
		{Name: "refunded_at", Type: field.TypeTime, Nullable: true},
		{Name: "kind", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "origin_code", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "origin_name", Type: field.TypeString, Nullable: true},
		{Name: "dest_code", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "dest_name", Type: field.TypeString, Nullable: true},
		{Name: "distance_km", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "numeric(18,4)"}},
		{Name: "duration_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "way_id", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "way_name", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "pickup_type", Type: field.TypeEnum, Nullable: true, Enums: []string{"shuttle", "self", "office", "transit"}},
		{Name: "pickup_id", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "pickup_name", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "pickup_address", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "pickup_info", Type: field.TypeJSON, Nullable: true},
		{Name: "drop_off_type", Type: field.TypeEnum, Nullable: true, Enums: []string{"shuttle", "self", "office", "transit"}},
		{Name: "drop_off_id", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "drop_off_name", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "drop_off_address", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "drop_off_info", Type: field.TypeJSON, Nullable: true},
		{Name: "extra_data", Type: field.TypeJSON, Nullable: true},
		{Name: "ticket_id", Type: field.TypeUUID},
	}
	// TicketSeatsTable holds the schema information for the "ticket_seats" table.
	TicketSeatsTable = &schema.Table{
		Name:       "ticket_seats",
		Columns:    TicketSeatsColumns,
		PrimaryKey: []*schema.Column{TicketSeatsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ticket_seats_tickets_ticketSeats",
				Columns:    []*schema.Column{TicketSeatsColumns[38]},
				RefColumns: []*schema.Column{TicketsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "ticketseat_ticket_id",
				Unique:  false,
				Columns: []*schema.Column{TicketSeatsColumns[38]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TicketsTable,
		TicketSeatsTable,
	}
)

func init() {
	TicketSeatsTable.ForeignKeys[0].RefTable = TicketsTable
}
