// Code generated by novaerp.com, DO NOT EDIT.

package accountlogin

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/internal"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLTE(FieldID, id))
}

// Account applies equality check predicate on the "account" field. It's identical to AccountEQ.
func Account(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldAccount, v))
}

// AccountType applies equality check predicate on the "account_type" field. It's identical to AccountTypeEQ.
func AccountType(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldAccountType, v))
}

// PasswordSalt applies equality check predicate on the "password_salt" field. It's identical to PasswordSaltEQ.
func PasswordSalt(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldPasswordSalt, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldPasswordHash, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldUpdatedBy, v))
}

// AccountEQ applies the EQ predicate on the "account" field.
func AccountEQ(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldAccount, v))
}

// AccountNEQ applies the NEQ predicate on the "account" field.
func AccountNEQ(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNEQ(FieldAccount, v))
}

// AccountIn applies the In predicate on the "account" field.
func AccountIn(vs ...string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldIn(FieldAccount, vs...))
}

// AccountNotIn applies the NotIn predicate on the "account" field.
func AccountNotIn(vs ...string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNotIn(FieldAccount, vs...))
}

// AccountGT applies the GT predicate on the "account" field.
func AccountGT(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGT(FieldAccount, v))
}

// AccountGTE applies the GTE predicate on the "account" field.
func AccountGTE(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGTE(FieldAccount, v))
}

// AccountLT applies the LT predicate on the "account" field.
func AccountLT(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLT(FieldAccount, v))
}

// AccountLTE applies the LTE predicate on the "account" field.
func AccountLTE(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLTE(FieldAccount, v))
}

// AccountContains applies the Contains predicate on the "account" field.
func AccountContains(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldContains(FieldAccount, v))
}

// AccountHasPrefix applies the HasPrefix predicate on the "account" field.
func AccountHasPrefix(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldHasPrefix(FieldAccount, v))
}

// AccountHasSuffix applies the HasSuffix predicate on the "account" field.
func AccountHasSuffix(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldHasSuffix(FieldAccount, v))
}

// AccountEqualFold applies the EqualFold predicate on the "account" field.
func AccountEqualFold(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEqualFold(FieldAccount, v))
}

// AccountContainsFold applies the ContainsFold predicate on the "account" field.
func AccountContainsFold(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldContainsFold(FieldAccount, v))
}

// AccountTypeEQ applies the EQ predicate on the "account_type" field.
func AccountTypeEQ(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldAccountType, v))
}

// AccountTypeNEQ applies the NEQ predicate on the "account_type" field.
func AccountTypeNEQ(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNEQ(FieldAccountType, v))
}

// AccountTypeIn applies the In predicate on the "account_type" field.
func AccountTypeIn(vs ...string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldIn(FieldAccountType, vs...))
}

// AccountTypeNotIn applies the NotIn predicate on the "account_type" field.
func AccountTypeNotIn(vs ...string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNotIn(FieldAccountType, vs...))
}

// AccountTypeGT applies the GT predicate on the "account_type" field.
func AccountTypeGT(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGT(FieldAccountType, v))
}

// AccountTypeGTE applies the GTE predicate on the "account_type" field.
func AccountTypeGTE(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGTE(FieldAccountType, v))
}

// AccountTypeLT applies the LT predicate on the "account_type" field.
func AccountTypeLT(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLT(FieldAccountType, v))
}

// AccountTypeLTE applies the LTE predicate on the "account_type" field.
func AccountTypeLTE(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLTE(FieldAccountType, v))
}

// AccountTypeContains applies the Contains predicate on the "account_type" field.
func AccountTypeContains(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldContains(FieldAccountType, v))
}

// AccountTypeHasPrefix applies the HasPrefix predicate on the "account_type" field.
func AccountTypeHasPrefix(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldHasPrefix(FieldAccountType, v))
}

// AccountTypeHasSuffix applies the HasSuffix predicate on the "account_type" field.
func AccountTypeHasSuffix(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldHasSuffix(FieldAccountType, v))
}

// AccountTypeEqualFold applies the EqualFold predicate on the "account_type" field.
func AccountTypeEqualFold(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEqualFold(FieldAccountType, v))
}

// AccountTypeContainsFold applies the ContainsFold predicate on the "account_type" field.
func AccountTypeContainsFold(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldContainsFold(FieldAccountType, v))
}

// PasswordSaltEQ applies the EQ predicate on the "password_salt" field.
func PasswordSaltEQ(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldPasswordSalt, v))
}

// PasswordSaltNEQ applies the NEQ predicate on the "password_salt" field.
func PasswordSaltNEQ(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNEQ(FieldPasswordSalt, v))
}

// PasswordSaltIn applies the In predicate on the "password_salt" field.
func PasswordSaltIn(vs ...string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldIn(FieldPasswordSalt, vs...))
}

// PasswordSaltNotIn applies the NotIn predicate on the "password_salt" field.
func PasswordSaltNotIn(vs ...string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNotIn(FieldPasswordSalt, vs...))
}

// PasswordSaltGT applies the GT predicate on the "password_salt" field.
func PasswordSaltGT(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGT(FieldPasswordSalt, v))
}

// PasswordSaltGTE applies the GTE predicate on the "password_salt" field.
func PasswordSaltGTE(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGTE(FieldPasswordSalt, v))
}

// PasswordSaltLT applies the LT predicate on the "password_salt" field.
func PasswordSaltLT(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLT(FieldPasswordSalt, v))
}

// PasswordSaltLTE applies the LTE predicate on the "password_salt" field.
func PasswordSaltLTE(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLTE(FieldPasswordSalt, v))
}

// PasswordSaltContains applies the Contains predicate on the "password_salt" field.
func PasswordSaltContains(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldContains(FieldPasswordSalt, v))
}

// PasswordSaltHasPrefix applies the HasPrefix predicate on the "password_salt" field.
func PasswordSaltHasPrefix(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldHasPrefix(FieldPasswordSalt, v))
}

// PasswordSaltHasSuffix applies the HasSuffix predicate on the "password_salt" field.
func PasswordSaltHasSuffix(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldHasSuffix(FieldPasswordSalt, v))
}

// PasswordSaltEqualFold applies the EqualFold predicate on the "password_salt" field.
func PasswordSaltEqualFold(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEqualFold(FieldPasswordSalt, v))
}

// PasswordSaltContainsFold applies the ContainsFold predicate on the "password_salt" field.
func PasswordSaltContainsFold(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldContainsFold(FieldPasswordSalt, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldContainsFold(FieldPasswordHash, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLTE(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uuid.UUID) predicate.AccountLogin {
	return predicate.AccountLogin(sql.FieldLTE(FieldUpdatedBy, v))
}

// HasUserAccount applies the HasEdge predicate on the "user_account" edge.
func HasUserAccount() predicate.AccountLogin {
	return predicate.AccountLogin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, UserAccountTable, UserAccountColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.UserAccount
		step.Edge.Schema = schemaConfig.UserAccount
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserAccountWith applies the HasEdge predicate on the "user_account" edge with a given conditions (other predicates).
func HasUserAccountWith(preds ...predicate.UserAccount) predicate.AccountLogin {
	return predicate.AccountLogin(func(s *sql.Selector) {
		step := newUserAccountStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.UserAccount
		step.Edge.Schema = schemaConfig.UserAccount
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountLogin) predicate.AccountLogin {
	return predicate.AccountLogin(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountLogin) predicate.AccountLogin {
	return predicate.AccountLogin(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountLogin) predicate.AccountLogin {
	return predicate.AccountLogin(sql.NotPredicates(p))
}
