// Code generated by novaerp.com, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/accountlogin"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/internal"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/predicate"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/useraccount"
)

// AccountLoginUpdate is the builder for updating AccountLogin entities.
type AccountLoginUpdate struct {
	config
	hooks     []Hook
	mutation  *AccountLoginMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AccountLoginUpdate builder.
func (_u *AccountLoginUpdate) Where(ps ...predicate.AccountLogin) *AccountLoginUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccount sets the "account" field.
func (_u *AccountLoginUpdate) SetAccount(v string) *AccountLoginUpdate {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *AccountLoginUpdate) SetNillableAccount(v *string) *AccountLoginUpdate {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetAccountType sets the "account_type" field.
func (_u *AccountLoginUpdate) SetAccountType(v string) *AccountLoginUpdate {
	_u.mutation.SetAccountType(v)
	return _u
}

// SetNillableAccountType sets the "account_type" field if the given value is not nil.
func (_u *AccountLoginUpdate) SetNillableAccountType(v *string) *AccountLoginUpdate {
	if v != nil {
		_u.SetAccountType(*v)
	}
	return _u
}

// SetPasswordSalt sets the "password_salt" field.
func (_u *AccountLoginUpdate) SetPasswordSalt(v string) *AccountLoginUpdate {
	_u.mutation.SetPasswordSalt(v)
	return _u
}

// SetNillablePasswordSalt sets the "password_salt" field if the given value is not nil.
func (_u *AccountLoginUpdate) SetNillablePasswordSalt(v *string) *AccountLoginUpdate {
	if v != nil {
		_u.SetPasswordSalt(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *AccountLoginUpdate) SetPasswordHash(v string) *AccountLoginUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *AccountLoginUpdate) SetNillablePasswordHash(v *string) *AccountLoginUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AccountLoginUpdate) SetIsActive(v bool) *AccountLoginUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AccountLoginUpdate) SetNillableIsActive(v *bool) *AccountLoginUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountLoginUpdate) SetUpdatedAt(v time.Time) *AccountLoginUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AccountLoginUpdate) SetCreatedBy(v uuid.UUID) *AccountLoginUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AccountLoginUpdate) SetNillableCreatedBy(v *uuid.UUID) *AccountLoginUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *AccountLoginUpdate) SetUpdatedBy(v uuid.UUID) *AccountLoginUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *AccountLoginUpdate) SetNillableUpdatedBy(v *uuid.UUID) *AccountLoginUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetUserAccountID sets the "user_account" edge to the UserAccount entity by ID.
func (_u *AccountLoginUpdate) SetUserAccountID(id uuid.UUID) *AccountLoginUpdate {
	_u.mutation.SetUserAccountID(id)
	return _u
}

// SetNillableUserAccountID sets the "user_account" edge to the UserAccount entity by ID if the given value is not nil.
func (_u *AccountLoginUpdate) SetNillableUserAccountID(id *uuid.UUID) *AccountLoginUpdate {
	if id != nil {
		_u = _u.SetUserAccountID(*id)
	}
	return _u
}

// SetUserAccount sets the "user_account" edge to the UserAccount entity.
func (_u *AccountLoginUpdate) SetUserAccount(v *UserAccount) *AccountLoginUpdate {
	return _u.SetUserAccountID(v.ID)
}

// Mutation returns the AccountLoginMutation object of the builder.
func (_u *AccountLoginUpdate) Mutation() *AccountLoginMutation {
	return _u.mutation
}

// ClearUserAccount clears the "user_account" edge to the UserAccount entity.
func (_u *AccountLoginUpdate) ClearUserAccount() *AccountLoginUpdate {
	_u.mutation.ClearUserAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountLoginUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountLoginUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountLoginUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountLoginUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountLoginUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountlogin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountLoginUpdate) check() error {
	if v, ok := _u.mutation.Account(); ok {
		if err := accountlogin.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "AccountLogin.account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountType(); ok {
		if err := accountlogin.AccountTypeValidator(v); err != nil {
			return &ValidationError{Name: "account_type", err: fmt.Errorf(`ent: validator failed for field "AccountLogin.account_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordSalt(); ok {
		if err := accountlogin.PasswordSaltValidator(v); err != nil {
			return &ValidationError{Name: "password_salt", err: fmt.Errorf(`ent: validator failed for field "AccountLogin.password_salt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := accountlogin.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "AccountLogin.password_hash": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AccountLoginUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AccountLoginUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AccountLoginUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountlogin.Table, accountlogin.Columns, sqlgraph.NewFieldSpec(accountlogin.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(accountlogin.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountType(); ok {
		_spec.SetField(accountlogin.FieldAccountType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordSalt(); ok {
		_spec.SetField(accountlogin.FieldPasswordSalt, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(accountlogin.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(accountlogin.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountlogin.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(accountlogin.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(accountlogin.FieldUpdatedBy, field.TypeUUID, value)
	}
	if _u.mutation.UserAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   accountlogin.UserAccountTable,
			Columns: []string{accountlogin.UserAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraccount.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.UserAccount
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   accountlogin.UserAccountTable,
			Columns: []string{accountlogin.UserAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraccount.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.UserAccount
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.AccountLogin
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountlogin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountLoginUpdateOne is the builder for updating a single AccountLogin entity.
type AccountLoginUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AccountLoginMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetAccount sets the "account" field.
func (_u *AccountLoginUpdateOne) SetAccount(v string) *AccountLoginUpdateOne {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *AccountLoginUpdateOne) SetNillableAccount(v *string) *AccountLoginUpdateOne {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetAccountType sets the "account_type" field.
func (_u *AccountLoginUpdateOne) SetAccountType(v string) *AccountLoginUpdateOne {
	_u.mutation.SetAccountType(v)
	return _u
}

// SetNillableAccountType sets the "account_type" field if the given value is not nil.
func (_u *AccountLoginUpdateOne) SetNillableAccountType(v *string) *AccountLoginUpdateOne {
	if v != nil {
		_u.SetAccountType(*v)
	}
	return _u
}

// SetPasswordSalt sets the "password_salt" field.
func (_u *AccountLoginUpdateOne) SetPasswordSalt(v string) *AccountLoginUpdateOne {
	_u.mutation.SetPasswordSalt(v)
	return _u
}

// SetNillablePasswordSalt sets the "password_salt" field if the given value is not nil.
func (_u *AccountLoginUpdateOne) SetNillablePasswordSalt(v *string) *AccountLoginUpdateOne {
	if v != nil {
		_u.SetPasswordSalt(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *AccountLoginUpdateOne) SetPasswordHash(v string) *AccountLoginUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *AccountLoginUpdateOne) SetNillablePasswordHash(v *string) *AccountLoginUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AccountLoginUpdateOne) SetIsActive(v bool) *AccountLoginUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AccountLoginUpdateOne) SetNillableIsActive(v *bool) *AccountLoginUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountLoginUpdateOne) SetUpdatedAt(v time.Time) *AccountLoginUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AccountLoginUpdateOne) SetCreatedBy(v uuid.UUID) *AccountLoginUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AccountLoginUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *AccountLoginUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *AccountLoginUpdateOne) SetUpdatedBy(v uuid.UUID) *AccountLoginUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *AccountLoginUpdateOne) SetNillableUpdatedBy(v *uuid.UUID) *AccountLoginUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetUserAccountID sets the "user_account" edge to the UserAccount entity by ID.
func (_u *AccountLoginUpdateOne) SetUserAccountID(id uuid.UUID) *AccountLoginUpdateOne {
	_u.mutation.SetUserAccountID(id)
	return _u
}

// SetNillableUserAccountID sets the "user_account" edge to the UserAccount entity by ID if the given value is not nil.
func (_u *AccountLoginUpdateOne) SetNillableUserAccountID(id *uuid.UUID) *AccountLoginUpdateOne {
	if id != nil {
		_u = _u.SetUserAccountID(*id)
	}
	return _u
}

// SetUserAccount sets the "user_account" edge to the UserAccount entity.
func (_u *AccountLoginUpdateOne) SetUserAccount(v *UserAccount) *AccountLoginUpdateOne {
	return _u.SetUserAccountID(v.ID)
}

// Mutation returns the AccountLoginMutation object of the builder.
func (_u *AccountLoginUpdateOne) Mutation() *AccountLoginMutation {
	return _u.mutation
}

// ClearUserAccount clears the "user_account" edge to the UserAccount entity.
func (_u *AccountLoginUpdateOne) ClearUserAccount() *AccountLoginUpdateOne {
	_u.mutation.ClearUserAccount()
	return _u
}

// Where appends a list predicates to the AccountLoginUpdate builder.
func (_u *AccountLoginUpdateOne) Where(ps ...predicate.AccountLogin) *AccountLoginUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountLoginUpdateOne) Select(field string, fields ...string) *AccountLoginUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountLogin entity.
func (_u *AccountLoginUpdateOne) Save(ctx context.Context) (*AccountLogin, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountLoginUpdateOne) SaveX(ctx context.Context) *AccountLogin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountLoginUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountLoginUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountLoginUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountlogin.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountLoginUpdateOne) check() error {
	if v, ok := _u.mutation.Account(); ok {
		if err := accountlogin.AccountValidator(v); err != nil {
			return &ValidationError{Name: "account", err: fmt.Errorf(`ent: validator failed for field "AccountLogin.account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountType(); ok {
		if err := accountlogin.AccountTypeValidator(v); err != nil {
			return &ValidationError{Name: "account_type", err: fmt.Errorf(`ent: validator failed for field "AccountLogin.account_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordSalt(); ok {
		if err := accountlogin.PasswordSaltValidator(v); err != nil {
			return &ValidationError{Name: "password_salt", err: fmt.Errorf(`ent: validator failed for field "AccountLogin.password_salt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := accountlogin.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "AccountLogin.password_hash": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AccountLoginUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AccountLoginUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AccountLoginUpdateOne) sqlSave(ctx context.Context) (_node *AccountLogin, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountlogin.Table, accountlogin.Columns, sqlgraph.NewFieldSpec(accountlogin.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountLogin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountlogin.FieldID)
		for _, f := range fields {
			if !accountlogin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountlogin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(accountlogin.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountType(); ok {
		_spec.SetField(accountlogin.FieldAccountType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordSalt(); ok {
		_spec.SetField(accountlogin.FieldPasswordSalt, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(accountlogin.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(accountlogin.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountlogin.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(accountlogin.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(accountlogin.FieldUpdatedBy, field.TypeUUID, value)
	}
	if _u.mutation.UserAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   accountlogin.UserAccountTable,
			Columns: []string{accountlogin.UserAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraccount.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.UserAccount
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   accountlogin.UserAccountTable,
			Columns: []string{accountlogin.UserAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraccount.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.UserAccount
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.AccountLogin
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_spec.AddModifiers(_u.modifiers...)
	_node = &AccountLogin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountlogin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
