// Code generated by novaerp.com, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/accountlogin"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/useraccount"
)

// AccountLogin is the model entity for the AccountLogin schema.
type AccountLogin struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Account holds the value of the "account" field.
	Account string `json:"account,omitempty"`
	// AccountType holds the value of the "account_type" field.
	AccountType string `json:"account_type,omitempty"`
	// PasswordSalt holds the value of the "password_salt" field.
	PasswordSalt string `json:"password_salt,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"password_hash,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy uuid.UUID `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy uuid.UUID `json:"updated_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountLoginQuery when eager-loading is set.
	Edges        AccountLoginEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountLoginEdges holds the relations/edges for other nodes in the graph.
type AccountLoginEdges struct {
	// UserAccount holds the value of the user_account edge.
	UserAccount *UserAccount `json:"user_account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserAccountOrErr returns the UserAccount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountLoginEdges) UserAccountOrErr() (*UserAccount, error) {
	if e.UserAccount != nil {
		return e.UserAccount, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: useraccount.Label}
	}
	return nil, &NotLoadedError{edge: "user_account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountLogin) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountlogin.FieldIsActive:
			values[i] = new(sql.NullBool)
		case accountlogin.FieldAccount, accountlogin.FieldAccountType, accountlogin.FieldPasswordSalt, accountlogin.FieldPasswordHash:
			values[i] = new(sql.NullString)
		case accountlogin.FieldCreatedAt, accountlogin.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case accountlogin.FieldID, accountlogin.FieldCreatedBy, accountlogin.FieldUpdatedBy:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountLogin fields.
func (_m *AccountLogin) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountlogin.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case accountlogin.FieldAccount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account", values[i])
			} else if value.Valid {
				_m.Account = value.String
			}
		case accountlogin.FieldAccountType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_type", values[i])
			} else if value.Valid {
				_m.AccountType = value.String
			}
		case accountlogin.FieldPasswordSalt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_salt", values[i])
			} else if value.Valid {
				_m.PasswordSalt = value.String
			}
		case accountlogin.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case accountlogin.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case accountlogin.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountlogin.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case accountlogin.FieldCreatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value != nil {
				_m.CreatedBy = *value
			}
		case accountlogin.FieldUpdatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value != nil {
				_m.UpdatedBy = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountLogin.
// This includes values selected through modifiers, order, etc.
func (_m *AccountLogin) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUserAccount queries the "user_account" edge of the AccountLogin entity.
func (_m *AccountLogin) QueryUserAccount() *UserAccountQuery {
	return NewAccountLoginClient(_m.config).QueryUserAccount(_m)
}

// Update returns a builder for updating this AccountLogin.
// Note that you need to call AccountLogin.Unwrap() before calling this method if this AccountLogin
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountLogin) Update() *AccountLoginUpdateOne {
	return NewAccountLoginClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountLogin entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountLogin) Unwrap() *AccountLogin {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountLogin is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountLogin) String() string {
	var builder strings.Builder
	builder.WriteString("AccountLogin(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account=")
	builder.WriteString(_m.Account)
	builder.WriteString(", ")
	builder.WriteString("account_type=")
	builder.WriteString(_m.AccountType)
	builder.WriteString(", ")
	builder.WriteString("password_salt=")
	builder.WriteString(_m.PasswordSalt)
	builder.WriteString(", ")
	builder.WriteString("password_hash=")
	builder.WriteString(_m.PasswordHash)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedBy))
	builder.WriteByte(')')
	return builder.String()
}

// AccountLogins is a parsable slice of AccountLogin.
type AccountLogins []*AccountLogin
