// Code generated by novaerp.com, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/accountlogin"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/useraccount"

	stdsql "database/sql"

	"vn.vato.zora.be.api/apps/user/internal/data/ent/internal"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AccountLogin is the client for interacting with the AccountLogin builders.
	AccountLogin *AccountLoginClient
	// UserAccount is the client for interacting with the UserAccount builders.
	UserAccount *UserAccountClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AccountLogin = NewAccountLoginClient(c.config)
	c.UserAccount = NewUserAccountClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
		// schemaConfig contains alternative names for all tables.
		schemaConfig SchemaConfig
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		AccountLogin: NewAccountLoginClient(cfg),
		UserAccount:  NewUserAccountClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		AccountLogin: NewAccountLoginClient(cfg),
		UserAccount:  NewUserAccountClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AccountLogin.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.AccountLogin.Use(hooks...)
	c.UserAccount.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.AccountLogin.Intercept(interceptors...)
	c.UserAccount.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AccountLoginMutation:
		return c.AccountLogin.mutate(ctx, m)
	case *UserAccountMutation:
		return c.UserAccount.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AccountLoginClient is a client for the AccountLogin schema.
type AccountLoginClient struct {
	config
}

// NewAccountLoginClient returns a client for the AccountLogin from the given config.
func NewAccountLoginClient(c config) *AccountLoginClient {
	return &AccountLoginClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `accountlogin.Hooks(f(g(h())))`.
func (c *AccountLoginClient) Use(hooks ...Hook) {
	c.hooks.AccountLogin = append(c.hooks.AccountLogin, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `accountlogin.Intercept(f(g(h())))`.
func (c *AccountLoginClient) Intercept(interceptors ...Interceptor) {
	c.inters.AccountLogin = append(c.inters.AccountLogin, interceptors...)
}

// Create returns a builder for creating a AccountLogin entity.
func (c *AccountLoginClient) Create() *AccountLoginCreate {
	mutation := newAccountLoginMutation(c.config, OpCreate)
	return &AccountLoginCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AccountLogin entities.
func (c *AccountLoginClient) CreateBulk(builders ...*AccountLoginCreate) *AccountLoginCreateBulk {
	return &AccountLoginCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AccountLoginClient) MapCreateBulk(slice any, setFunc func(*AccountLoginCreate, int)) *AccountLoginCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AccountLoginCreateBulk{err: fmt.Errorf("calling to AccountLoginClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AccountLoginCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AccountLoginCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AccountLogin.
func (c *AccountLoginClient) Update() *AccountLoginUpdate {
	mutation := newAccountLoginMutation(c.config, OpUpdate)
	return &AccountLoginUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AccountLoginClient) UpdateOne(_m *AccountLogin) *AccountLoginUpdateOne {
	mutation := newAccountLoginMutation(c.config, OpUpdateOne, withAccountLogin(_m))
	return &AccountLoginUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AccountLoginClient) UpdateOneID(id uuid.UUID) *AccountLoginUpdateOne {
	mutation := newAccountLoginMutation(c.config, OpUpdateOne, withAccountLoginID(id))
	return &AccountLoginUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AccountLogin.
func (c *AccountLoginClient) Delete() *AccountLoginDelete {
	mutation := newAccountLoginMutation(c.config, OpDelete)
	return &AccountLoginDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AccountLoginClient) DeleteOne(_m *AccountLogin) *AccountLoginDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AccountLoginClient) DeleteOneID(id uuid.UUID) *AccountLoginDeleteOne {
	builder := c.Delete().Where(accountlogin.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AccountLoginDeleteOne{builder}
}

// Query returns a query builder for AccountLogin.
func (c *AccountLoginClient) Query() *AccountLoginQuery {
	return &AccountLoginQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAccountLogin},
		inters: c.Interceptors(),
	}
}

// Get returns a AccountLogin entity by its id.
func (c *AccountLoginClient) Get(ctx context.Context, id uuid.UUID) (*AccountLogin, error) {
	return c.Query().Where(accountlogin.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AccountLoginClient) GetX(ctx context.Context, id uuid.UUID) *AccountLogin {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUserAccount queries the user_account edge of a AccountLogin.
func (c *AccountLoginClient) QueryUserAccount(_m *AccountLogin) *UserAccountQuery {
	query := (&UserAccountClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(accountlogin.Table, accountlogin.FieldID, id),
			sqlgraph.To(useraccount.Table, useraccount.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, accountlogin.UserAccountTable, accountlogin.UserAccountColumn),
		)
		schemaConfig := _m.schemaConfig
		step.To.Schema = schemaConfig.UserAccount
		step.Edge.Schema = schemaConfig.UserAccount
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AccountLoginClient) Hooks() []Hook {
	return c.hooks.AccountLogin
}

// Interceptors returns the client interceptors.
func (c *AccountLoginClient) Interceptors() []Interceptor {
	return c.inters.AccountLogin
}

func (c *AccountLoginClient) mutate(ctx context.Context, m *AccountLoginMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AccountLoginCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AccountLoginUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AccountLoginUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AccountLoginDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AccountLogin mutation op: %q", m.Op())
	}
}

// UserAccountClient is a client for the UserAccount schema.
type UserAccountClient struct {
	config
}

// NewUserAccountClient returns a client for the UserAccount from the given config.
func NewUserAccountClient(c config) *UserAccountClient {
	return &UserAccountClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `useraccount.Hooks(f(g(h())))`.
func (c *UserAccountClient) Use(hooks ...Hook) {
	c.hooks.UserAccount = append(c.hooks.UserAccount, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `useraccount.Intercept(f(g(h())))`.
func (c *UserAccountClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserAccount = append(c.inters.UserAccount, interceptors...)
}

// Create returns a builder for creating a UserAccount entity.
func (c *UserAccountClient) Create() *UserAccountCreate {
	mutation := newUserAccountMutation(c.config, OpCreate)
	return &UserAccountCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserAccount entities.
func (c *UserAccountClient) CreateBulk(builders ...*UserAccountCreate) *UserAccountCreateBulk {
	return &UserAccountCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserAccountClient) MapCreateBulk(slice any, setFunc func(*UserAccountCreate, int)) *UserAccountCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserAccountCreateBulk{err: fmt.Errorf("calling to UserAccountClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserAccountCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserAccountCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserAccount.
func (c *UserAccountClient) Update() *UserAccountUpdate {
	mutation := newUserAccountMutation(c.config, OpUpdate)
	return &UserAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserAccountClient) UpdateOne(_m *UserAccount) *UserAccountUpdateOne {
	mutation := newUserAccountMutation(c.config, OpUpdateOne, withUserAccount(_m))
	return &UserAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserAccountClient) UpdateOneID(id uuid.UUID) *UserAccountUpdateOne {
	mutation := newUserAccountMutation(c.config, OpUpdateOne, withUserAccountID(id))
	return &UserAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserAccount.
func (c *UserAccountClient) Delete() *UserAccountDelete {
	mutation := newUserAccountMutation(c.config, OpDelete)
	return &UserAccountDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserAccountClient) DeleteOne(_m *UserAccount) *UserAccountDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserAccountClient) DeleteOneID(id uuid.UUID) *UserAccountDeleteOne {
	builder := c.Delete().Where(useraccount.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserAccountDeleteOne{builder}
}

// Query returns a query builder for UserAccount.
func (c *UserAccountClient) Query() *UserAccountQuery {
	return &UserAccountQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserAccount},
		inters: c.Interceptors(),
	}
}

// Get returns a UserAccount entity by its id.
func (c *UserAccountClient) Get(ctx context.Context, id uuid.UUID) (*UserAccount, error) {
	return c.Query().Where(useraccount.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserAccountClient) GetX(ctx context.Context, id uuid.UUID) *UserAccount {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAccountLogin queries the account_login edge of a UserAccount.
func (c *UserAccountClient) QueryAccountLogin(_m *UserAccount) *AccountLoginQuery {
	query := (&AccountLoginClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(useraccount.Table, useraccount.FieldID, id),
			sqlgraph.To(accountlogin.Table, accountlogin.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, useraccount.AccountLoginTable, useraccount.AccountLoginColumn),
		)
		schemaConfig := _m.schemaConfig
		step.To.Schema = schemaConfig.AccountLogin
		step.Edge.Schema = schemaConfig.UserAccount
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserAccountClient) Hooks() []Hook {
	return c.hooks.UserAccount
}

// Interceptors returns the client interceptors.
func (c *UserAccountClient) Interceptors() []Interceptor {
	return c.inters.UserAccount
}

func (c *UserAccountClient) mutate(ctx context.Context, m *UserAccountMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserAccountCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserAccountDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserAccount mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AccountLogin, UserAccount []ent.Hook
	}
	inters struct {
		AccountLogin, UserAccount []ent.Interceptor
	}
)

// SchemaConfig represents alternative schema names for all tables
// that can be passed at runtime.
type SchemaConfig = internal.SchemaConfig

// AlternateSchemas allows alternate schema names to be
// passed into ent operations.
func AlternateSchema(schemaConfig SchemaConfig) Option {
	return func(c *config) {
		c.schemaConfig = schemaConfig
	}
}

// ExecContext allows calling the underlying ExecContext method of the driver if it is supported by it.
// See, database/sql#DB.ExecContext for more information.
func (c *config) ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error) {
	ex, ok := c.driver.(interface {
		ExecContext(context.Context, string, ...any) (stdsql.Result, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.ExecContext is not supported")
	}
	return ex.ExecContext(ctx, query, args...)
}

// QueryContext allows calling the underlying QueryContext method of the driver if it is supported by it.
// See, database/sql#DB.QueryContext for more information.
func (c *config) QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error) {
	q, ok := c.driver.(interface {
		QueryContext(context.Context, string, ...any) (*stdsql.Rows, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.QueryContext is not supported")
	}
	return q.QueryContext(ctx, query, args...)
}
