// Code generated by novaerp.com, DO NOT EDIT.

package ent

import (
	"vn.vato.zora.be.api/apps/user/internal/data/ent/accountlogin"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/predicate"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/useraccount"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 2)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   accountlogin.Table,
			Columns: accountlogin.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: accountlogin.FieldID,
			},
		},
		Type: "AccountLogin",
		Fields: map[string]*sqlgraph.FieldSpec{
			accountlogin.FieldAccount:      {Type: field.TypeString, Column: accountlogin.FieldAccount},
			accountlogin.FieldAccountType:  {Type: field.TypeString, Column: accountlogin.FieldAccountType},
			accountlogin.FieldPasswordSalt: {Type: field.TypeString, Column: accountlogin.FieldPasswordSalt},
			accountlogin.FieldPasswordHash: {Type: field.TypeString, Column: accountlogin.FieldPasswordHash},
			accountlogin.FieldIsActive:     {Type: field.TypeBool, Column: accountlogin.FieldIsActive},
			accountlogin.FieldCreatedAt:    {Type: field.TypeTime, Column: accountlogin.FieldCreatedAt},
			accountlogin.FieldUpdatedAt:    {Type: field.TypeTime, Column: accountlogin.FieldUpdatedAt},
			accountlogin.FieldCreatedBy:    {Type: field.TypeUUID, Column: accountlogin.FieldCreatedBy},
			accountlogin.FieldUpdatedBy:    {Type: field.TypeUUID, Column: accountlogin.FieldUpdatedBy},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   useraccount.Table,
			Columns: useraccount.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: useraccount.FieldID,
			},
		},
		Type: "UserAccount",
		Fields: map[string]*sqlgraph.FieldSpec{
			useraccount.FieldUserLoginID: {Type: field.TypeUUID, Column: useraccount.FieldUserLoginID},
			useraccount.FieldFullName:    {Type: field.TypeString, Column: useraccount.FieldFullName},
			useraccount.FieldAvatarURL:   {Type: field.TypeString, Column: useraccount.FieldAvatarURL},
			useraccount.FieldPhone:       {Type: field.TypeString, Column: useraccount.FieldPhone},
			useraccount.FieldDateOfBirth: {Type: field.TypeTime, Column: useraccount.FieldDateOfBirth},
			useraccount.FieldGender:      {Type: field.TypeString, Column: useraccount.FieldGender},
			useraccount.FieldAddress:     {Type: field.TypeString, Column: useraccount.FieldAddress},
			useraccount.FieldIsActive:    {Type: field.TypeBool, Column: useraccount.FieldIsActive},
			useraccount.FieldCreatedAt:   {Type: field.TypeTime, Column: useraccount.FieldCreatedAt},
			useraccount.FieldUpdatedAt:   {Type: field.TypeTime, Column: useraccount.FieldUpdatedAt},
			useraccount.FieldCreatedBy:   {Type: field.TypeUUID, Column: useraccount.FieldCreatedBy},
			useraccount.FieldUpdatedBy:   {Type: field.TypeUUID, Column: useraccount.FieldUpdatedBy},
		},
	}
	graph.MustAddE(
		"user_account",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   accountlogin.UserAccountTable,
			Columns: []string{accountlogin.UserAccountColumn},
			Bidi:    false,
		},
		"AccountLogin",
		"UserAccount",
	)
	graph.MustAddE(
		"account_login",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useraccount.AccountLoginTable,
			Columns: []string{useraccount.AccountLoginColumn},
			Bidi:    false,
		},
		"UserAccount",
		"AccountLogin",
	)
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (_q *AccountLoginQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the AccountLoginQuery builder.
func (_q *AccountLoginQuery) Filter() *AccountLoginFilter {
	return &AccountLoginFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *AccountLoginMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the AccountLoginMutation builder.
func (m *AccountLoginMutation) Filter() *AccountLoginFilter {
	return &AccountLoginFilter{config: m.config, predicateAdder: m}
}

// AccountLoginFilter provides a generic filtering capability at runtime for AccountLoginQuery.
type AccountLoginFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *AccountLoginFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *AccountLoginFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(accountlogin.FieldID))
}

// WhereAccount applies the entql string predicate on the account field.
func (f *AccountLoginFilter) WhereAccount(p entql.StringP) {
	f.Where(p.Field(accountlogin.FieldAccount))
}

// WhereAccountType applies the entql string predicate on the account_type field.
func (f *AccountLoginFilter) WhereAccountType(p entql.StringP) {
	f.Where(p.Field(accountlogin.FieldAccountType))
}

// WherePasswordSalt applies the entql string predicate on the password_salt field.
func (f *AccountLoginFilter) WherePasswordSalt(p entql.StringP) {
	f.Where(p.Field(accountlogin.FieldPasswordSalt))
}

// WherePasswordHash applies the entql string predicate on the password_hash field.
func (f *AccountLoginFilter) WherePasswordHash(p entql.StringP) {
	f.Where(p.Field(accountlogin.FieldPasswordHash))
}

// WhereIsActive applies the entql bool predicate on the is_active field.
func (f *AccountLoginFilter) WhereIsActive(p entql.BoolP) {
	f.Where(p.Field(accountlogin.FieldIsActive))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *AccountLoginFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(accountlogin.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *AccountLoginFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(accountlogin.FieldUpdatedAt))
}

// WhereCreatedBy applies the entql [16]byte predicate on the created_by field.
func (f *AccountLoginFilter) WhereCreatedBy(p entql.ValueP) {
	f.Where(p.Field(accountlogin.FieldCreatedBy))
}

// WhereUpdatedBy applies the entql [16]byte predicate on the updated_by field.
func (f *AccountLoginFilter) WhereUpdatedBy(p entql.ValueP) {
	f.Where(p.Field(accountlogin.FieldUpdatedBy))
}

// WhereHasUserAccount applies a predicate to check if query has an edge user_account.
func (f *AccountLoginFilter) WhereHasUserAccount() {
	f.Where(entql.HasEdge("user_account"))
}

// WhereHasUserAccountWith applies a predicate to check if query has an edge user_account with a given conditions (other predicates).
func (f *AccountLoginFilter) WhereHasUserAccountWith(preds ...predicate.UserAccount) {
	f.Where(entql.HasEdgeWith("user_account", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *UserAccountQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the UserAccountQuery builder.
func (_q *UserAccountQuery) Filter() *UserAccountFilter {
	return &UserAccountFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *UserAccountMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the UserAccountMutation builder.
func (m *UserAccountMutation) Filter() *UserAccountFilter {
	return &UserAccountFilter{config: m.config, predicateAdder: m}
}

// UserAccountFilter provides a generic filtering capability at runtime for UserAccountQuery.
type UserAccountFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *UserAccountFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *UserAccountFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(useraccount.FieldID))
}

// WhereUserLoginID applies the entql [16]byte predicate on the user_login_id field.
func (f *UserAccountFilter) WhereUserLoginID(p entql.ValueP) {
	f.Where(p.Field(useraccount.FieldUserLoginID))
}

// WhereFullName applies the entql string predicate on the full_name field.
func (f *UserAccountFilter) WhereFullName(p entql.StringP) {
	f.Where(p.Field(useraccount.FieldFullName))
}

// WhereAvatarURL applies the entql string predicate on the avatar_url field.
func (f *UserAccountFilter) WhereAvatarURL(p entql.StringP) {
	f.Where(p.Field(useraccount.FieldAvatarURL))
}

// WherePhone applies the entql string predicate on the phone field.
func (f *UserAccountFilter) WherePhone(p entql.StringP) {
	f.Where(p.Field(useraccount.FieldPhone))
}

// WhereDateOfBirth applies the entql time.Time predicate on the date_of_birth field.
func (f *UserAccountFilter) WhereDateOfBirth(p entql.TimeP) {
	f.Where(p.Field(useraccount.FieldDateOfBirth))
}

// WhereGender applies the entql string predicate on the gender field.
func (f *UserAccountFilter) WhereGender(p entql.StringP) {
	f.Where(p.Field(useraccount.FieldGender))
}

// WhereAddress applies the entql string predicate on the address field.
func (f *UserAccountFilter) WhereAddress(p entql.StringP) {
	f.Where(p.Field(useraccount.FieldAddress))
}

// WhereIsActive applies the entql bool predicate on the is_active field.
func (f *UserAccountFilter) WhereIsActive(p entql.BoolP) {
	f.Where(p.Field(useraccount.FieldIsActive))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *UserAccountFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(useraccount.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *UserAccountFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(useraccount.FieldUpdatedAt))
}

// WhereCreatedBy applies the entql [16]byte predicate on the created_by field.
func (f *UserAccountFilter) WhereCreatedBy(p entql.ValueP) {
	f.Where(p.Field(useraccount.FieldCreatedBy))
}

// WhereUpdatedBy applies the entql [16]byte predicate on the updated_by field.
func (f *UserAccountFilter) WhereUpdatedBy(p entql.ValueP) {
	f.Where(p.Field(useraccount.FieldUpdatedBy))
}

// WhereHasAccountLogin applies a predicate to check if query has an edge account_login.
func (f *UserAccountFilter) WhereHasAccountLogin() {
	f.Where(entql.HasEdge("account_login"))
}

// WhereHasAccountLoginWith applies a predicate to check if query has an edge account_login with a given conditions (other predicates).
func (f *UserAccountFilter) WhereHasAccountLoginWith(preds ...predicate.AccountLogin) {
	f.Where(entql.HasEdgeWith("account_login", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}
