// Code generated by novaerp.com, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/accountlogin"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/internal"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/predicate"
	"vn.vato.zora.be.api/apps/user/internal/data/ent/useraccount"
)

// UserAccountUpdate is the builder for updating UserAccount entities.
type UserAccountUpdate struct {
	config
	hooks     []Hook
	mutation  *UserAccountMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserAccountUpdate builder.
func (_u *UserAccountUpdate) Where(ps ...predicate.UserAccount) *UserAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserLoginID sets the "user_login_id" field.
func (_u *UserAccountUpdate) SetUserLoginID(v uuid.UUID) *UserAccountUpdate {
	_u.mutation.SetUserLoginID(v)
	return _u
}

// SetNillableUserLoginID sets the "user_login_id" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableUserLoginID(v *uuid.UUID) *UserAccountUpdate {
	if v != nil {
		_u.SetUserLoginID(*v)
	}
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *UserAccountUpdate) SetFullName(v string) *UserAccountUpdate {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableFullName(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// ClearFullName clears the value of the "full_name" field.
func (_u *UserAccountUpdate) ClearFullName() *UserAccountUpdate {
	_u.mutation.ClearFullName()
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserAccountUpdate) SetAvatarURL(v string) *UserAccountUpdate {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableAvatarURL(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *UserAccountUpdate) ClearAvatarURL() *UserAccountUpdate {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *UserAccountUpdate) SetPhone(v string) *UserAccountUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillablePhone(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *UserAccountUpdate) ClearPhone() *UserAccountUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetDateOfBirth sets the "date_of_birth" field.
func (_u *UserAccountUpdate) SetDateOfBirth(v time.Time) *UserAccountUpdate {
	_u.mutation.SetDateOfBirth(v)
	return _u
}

// SetNillableDateOfBirth sets the "date_of_birth" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableDateOfBirth(v *time.Time) *UserAccountUpdate {
	if v != nil {
		_u.SetDateOfBirth(*v)
	}
	return _u
}

// ClearDateOfBirth clears the value of the "date_of_birth" field.
func (_u *UserAccountUpdate) ClearDateOfBirth() *UserAccountUpdate {
	_u.mutation.ClearDateOfBirth()
	return _u
}

// SetGender sets the "gender" field.
func (_u *UserAccountUpdate) SetGender(v string) *UserAccountUpdate {
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableGender(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// ClearGender clears the value of the "gender" field.
func (_u *UserAccountUpdate) ClearGender() *UserAccountUpdate {
	_u.mutation.ClearGender()
	return _u
}

// SetAddress sets the "address" field.
func (_u *UserAccountUpdate) SetAddress(v string) *UserAccountUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableAddress(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *UserAccountUpdate) ClearAddress() *UserAccountUpdate {
	_u.mutation.ClearAddress()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserAccountUpdate) SetIsActive(v bool) *UserAccountUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableIsActive(v *bool) *UserAccountUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAccountUpdate) SetUpdatedAt(v time.Time) *UserAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *UserAccountUpdate) SetCreatedBy(v uuid.UUID) *UserAccountUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableCreatedBy(v *uuid.UUID) *UserAccountUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *UserAccountUpdate) SetUpdatedBy(v uuid.UUID) *UserAccountUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableUpdatedBy(v *uuid.UUID) *UserAccountUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetAccountLoginID sets the "account_login" edge to the AccountLogin entity by ID.
func (_u *UserAccountUpdate) SetAccountLoginID(id uuid.UUID) *UserAccountUpdate {
	_u.mutation.SetAccountLoginID(id)
	return _u
}

// SetAccountLogin sets the "account_login" edge to the AccountLogin entity.
func (_u *UserAccountUpdate) SetAccountLogin(v *AccountLogin) *UserAccountUpdate {
	return _u.SetAccountLoginID(v.ID)
}

// Mutation returns the UserAccountMutation object of the builder.
func (_u *UserAccountUpdate) Mutation() *UserAccountMutation {
	return _u.mutation
}

// ClearAccountLogin clears the "account_login" edge to the AccountLogin entity.
func (_u *UserAccountUpdate) ClearAccountLogin() *UserAccountUpdate {
	_u.mutation.ClearAccountLogin()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useraccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAccountUpdate) check() error {
	if _u.mutation.AccountLoginCleared() && len(_u.mutation.AccountLoginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAccount.account_login"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserAccountUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserAccountUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraccount.Table, useraccount.Columns, sqlgraph.NewFieldSpec(useraccount.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(useraccount.FieldFullName, field.TypeString, value)
	}
	if _u.mutation.FullNameCleared() {
		_spec.ClearField(useraccount.FieldFullName, field.TypeString)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(useraccount.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(useraccount.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(useraccount.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(useraccount.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.DateOfBirth(); ok {
		_spec.SetField(useraccount.FieldDateOfBirth, field.TypeTime, value)
	}
	if _u.mutation.DateOfBirthCleared() {
		_spec.ClearField(useraccount.FieldDateOfBirth, field.TypeTime)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(useraccount.FieldGender, field.TypeString, value)
	}
	if _u.mutation.GenderCleared() {
		_spec.ClearField(useraccount.FieldGender, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(useraccount.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(useraccount.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(useraccount.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useraccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(useraccount.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(useraccount.FieldUpdatedBy, field.TypeUUID, value)
	}
	if _u.mutation.AccountLoginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useraccount.AccountLoginTable,
			Columns: []string{useraccount.AccountLoginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountlogin.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.UserAccount
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountLoginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useraccount.AccountLoginTable,
			Columns: []string{useraccount.AccountLoginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountlogin.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.UserAccount
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.UserAccount
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAccountUpdateOne is the builder for updating a single UserAccount entity.
type UserAccountUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserAccountMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserLoginID sets the "user_login_id" field.
func (_u *UserAccountUpdateOne) SetUserLoginID(v uuid.UUID) *UserAccountUpdateOne {
	_u.mutation.SetUserLoginID(v)
	return _u
}

// SetNillableUserLoginID sets the "user_login_id" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableUserLoginID(v *uuid.UUID) *UserAccountUpdateOne {
	if v != nil {
		_u.SetUserLoginID(*v)
	}
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *UserAccountUpdateOne) SetFullName(v string) *UserAccountUpdateOne {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableFullName(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// ClearFullName clears the value of the "full_name" field.
func (_u *UserAccountUpdateOne) ClearFullName() *UserAccountUpdateOne {
	_u.mutation.ClearFullName()
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserAccountUpdateOne) SetAvatarURL(v string) *UserAccountUpdateOne {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableAvatarURL(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *UserAccountUpdateOne) ClearAvatarURL() *UserAccountUpdateOne {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *UserAccountUpdateOne) SetPhone(v string) *UserAccountUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillablePhone(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *UserAccountUpdateOne) ClearPhone() *UserAccountUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetDateOfBirth sets the "date_of_birth" field.
func (_u *UserAccountUpdateOne) SetDateOfBirth(v time.Time) *UserAccountUpdateOne {
	_u.mutation.SetDateOfBirth(v)
	return _u
}

// SetNillableDateOfBirth sets the "date_of_birth" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableDateOfBirth(v *time.Time) *UserAccountUpdateOne {
	if v != nil {
		_u.SetDateOfBirth(*v)
	}
	return _u
}

// ClearDateOfBirth clears the value of the "date_of_birth" field.
func (_u *UserAccountUpdateOne) ClearDateOfBirth() *UserAccountUpdateOne {
	_u.mutation.ClearDateOfBirth()
	return _u
}

// SetGender sets the "gender" field.
func (_u *UserAccountUpdateOne) SetGender(v string) *UserAccountUpdateOne {
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableGender(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// ClearGender clears the value of the "gender" field.
func (_u *UserAccountUpdateOne) ClearGender() *UserAccountUpdateOne {
	_u.mutation.ClearGender()
	return _u
}

// SetAddress sets the "address" field.
func (_u *UserAccountUpdateOne) SetAddress(v string) *UserAccountUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableAddress(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *UserAccountUpdateOne) ClearAddress() *UserAccountUpdateOne {
	_u.mutation.ClearAddress()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserAccountUpdateOne) SetIsActive(v bool) *UserAccountUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableIsActive(v *bool) *UserAccountUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAccountUpdateOne) SetUpdatedAt(v time.Time) *UserAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *UserAccountUpdateOne) SetCreatedBy(v uuid.UUID) *UserAccountUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *UserAccountUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *UserAccountUpdateOne) SetUpdatedBy(v uuid.UUID) *UserAccountUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableUpdatedBy(v *uuid.UUID) *UserAccountUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetAccountLoginID sets the "account_login" edge to the AccountLogin entity by ID.
func (_u *UserAccountUpdateOne) SetAccountLoginID(id uuid.UUID) *UserAccountUpdateOne {
	_u.mutation.SetAccountLoginID(id)
	return _u
}

// SetAccountLogin sets the "account_login" edge to the AccountLogin entity.
func (_u *UserAccountUpdateOne) SetAccountLogin(v *AccountLogin) *UserAccountUpdateOne {
	return _u.SetAccountLoginID(v.ID)
}

// Mutation returns the UserAccountMutation object of the builder.
func (_u *UserAccountUpdateOne) Mutation() *UserAccountMutation {
	return _u.mutation
}

// ClearAccountLogin clears the "account_login" edge to the AccountLogin entity.
func (_u *UserAccountUpdateOne) ClearAccountLogin() *UserAccountUpdateOne {
	_u.mutation.ClearAccountLogin()
	return _u
}

// Where appends a list predicates to the UserAccountUpdate builder.
func (_u *UserAccountUpdateOne) Where(ps ...predicate.UserAccount) *UserAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAccountUpdateOne) Select(field string, fields ...string) *UserAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserAccount entity.
func (_u *UserAccountUpdateOne) Save(ctx context.Context) (*UserAccount, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAccountUpdateOne) SaveX(ctx context.Context) *UserAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useraccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAccountUpdateOne) check() error {
	if _u.mutation.AccountLoginCleared() && len(_u.mutation.AccountLoginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAccount.account_login"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserAccountUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserAccountUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserAccountUpdateOne) sqlSave(ctx context.Context) (_node *UserAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraccount.Table, useraccount.Columns, sqlgraph.NewFieldSpec(useraccount.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useraccount.FieldID)
		for _, f := range fields {
			if !useraccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useraccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(useraccount.FieldFullName, field.TypeString, value)
	}
	if _u.mutation.FullNameCleared() {
		_spec.ClearField(useraccount.FieldFullName, field.TypeString)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(useraccount.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(useraccount.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(useraccount.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(useraccount.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.DateOfBirth(); ok {
		_spec.SetField(useraccount.FieldDateOfBirth, field.TypeTime, value)
	}
	if _u.mutation.DateOfBirthCleared() {
		_spec.ClearField(useraccount.FieldDateOfBirth, field.TypeTime)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(useraccount.FieldGender, field.TypeString, value)
	}
	if _u.mutation.GenderCleared() {
		_spec.ClearField(useraccount.FieldGender, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(useraccount.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(useraccount.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(useraccount.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useraccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(useraccount.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(useraccount.FieldUpdatedBy, field.TypeUUID, value)
	}
	if _u.mutation.AccountLoginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useraccount.AccountLoginTable,
			Columns: []string{useraccount.AccountLoginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountlogin.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.UserAccount
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountLoginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useraccount.AccountLoginTable,
			Columns: []string{useraccount.AccountLoginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountlogin.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.UserAccount
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.UserAccount
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_spec.AddModifiers(_u.modifiers...)
	_node = &UserAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
