package main

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
	"vn.vato.zora.be.api/pkg/format"
	"vn.vato.zora.be.api/pkg/utils"
)

const (
	ignoreDeleteFolder      = "ent_schema"
	entHookGenFolder        = "ent_hook"
	entInterceptorGenFolder = "ent_interceptor"
	entScriptGenFolder      = "gen_sql"

	entSchemaFolder    = "ent_schema"
	entSchemaGenFolder = "ent"
)

var (
	entSchemaOutputDir      = filepath.Join("data", entSchemaGenFolder)
	entHookOutputDir        = filepath.Join("data", entHookGenFolder)
	entInterceptorOutputDir = filepath.Join("data", entInterceptorGenFolder)
	entScriptOutputDir      = filepath.Join("data", entScriptGenFolder)
)
var ignoreSqlTypeFilters = []string{
	"[]string",
	"map[string]interface",
}

func ensureDependencies() error {
	// TODO: remove kratos log dependency (MUST)
	dependencies := []string{
		"github.com/go-kratos/kratos/v2/log",
		"github.com/jackc/pgx/v5/stdlib",
	}

	for _, dep := range dependencies {
		log.Printf("Ensuring dependency: %s", dep)
		cmd := exec.Command("go", "get", dep)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("failed to get dependency %s: %v", dep, err)
		}
	}
	return nil
}

func fetchInfo() (string, string) {
	// Get the root directory of the current module
	moduleDirs, err := utils.GetModuleDirs()
	if err != nil {
		log.Fatalf("failed to get module directory: %v", err)
	}

	// Locate the root directory of the project
	var projectRoot string
	for _, dir := range moduleDirs {
		root, err := utils.GetProjectRoot(dir, "data")
		if err == nil {
			projectRoot = root
			break
		}
	}
	if projectRoot == "" {
		log.Fatal("failed to find valid project root")
	}

	if err = ensureDependencies(); err != nil {
		log.Fatalf("failed to ensure dependencies: %v", err)
	}

	schemaDir := filepath.Join(projectRoot, "data", ignoreDeleteFolder)

	return projectRoot, schemaDir
}

func tmplFuncMap() template.FuncMap {
	return template.FuncMap{
		"sqlKey": func() string { return "entsql" },
		"findRE": func(pattern, s string) [][]string {
			re := regexp.MustCompile(pattern)
			return re.FindAllStringSubmatch(s, -1)
		},
		"dict": func(values ...interface{}) map[string]interface{} {
			dict := make(map[string]interface{})
			if len(values)%2 != 0 {
				panic("invalid dict call: uneven number of args")
			}
			for i := 0; i < len(values); i += 2 {
				key, ok := values[i].(string)
				if !ok {
					panic("dict keys must be strings")
				}
				dict[key] = values[i+1]
			}
			return dict
		},
		"set": func(m map[string]interface{}, key string, value interface{}) string {
			m[key] = value
			return ""
		},
		"split": strings.Split,
		"hasKey": func(m map[string]interface{}, key string) bool {
			_, exists := m[key]
			return exists
		},
		"append": func(slice interface{}, elems ...interface{}) interface{} {
			switch s := slice.(type) {
			case []string:
				for _, e := range elems {
					if str, ok := e.(string); ok {
						s = append(s, str)
					}
				}
				return s
			default:
				return slice
			}
		},
		"join": strings.Join,
		"list": func(args ...interface{}) []string {
			var result []string
			for _, arg := range args {
				if str, ok := arg.(string); ok {
					result = append(result, str)
				}
			}
			return result
		},
		"hasAnnotation": func(ann *gen.Annotations, key string) bool {
			if ann == nil {
				return false
			}
			_, ok := (*ann)[key]
			return ok
		},
		"pascal": func(input string) string {
			words := strings.Split(input, "_")
			for i := range words {
				words[i] = strings.Title(words[i])
				words[i] = format.NormalizeInitialism(words[i])
			}

			return strings.Join(words, "")

		},
		"hasTSVector": func(fields []*gen.Field) bool {
			for _, f := range fields {
				if f.Name == "ts_vector" {
					return true
				}
			}
			return false
		},
		"lower": strings.ToLower,
		"snakeSchema": func(input string) string {
			return strings.ReplaceAll(strings.ToLower(input), "_", "")
		},
		"isIgnoreSQLType": func(fieldType string) bool {
			for _, f := range ignoreSqlTypeFilters {
				if strings.Contains(fieldType, f) {
					return true
				}
			}
			return false
		},
	}
}

func generateEntSchema(schemaDir, packageName, outputDir string) {
	fmt.Println("generate ent schema at: " + outputDir)
	config := &gen.Config{
		Target:  outputDir,
		Package: packageName,
		Header:  "// Code generated by novaerp.com, DO NOT EDIT.",
		Features: []gen.Feature{
			gen.FeaturePrivacy,
			gen.FeatureIntercept,
			gen.FeatureEntQL,
			gen.FeatureNamedEdges,
			gen.FeatureBidiEdgeRefs,
			gen.FeatureSnapshot,
			gen.FeatureSchemaConfig,
			gen.FeatureLock,
			gen.FeatureModifier,
			gen.FeatureExecQuery,
			gen.FeatureUpsert,
			gen.FeatureVersionedMigration,
		},
	}

	err := entc.Generate(schemaDir, config)
	if err != nil {
		log.Fatalf("running ent codegen: %v", err)
	}

	// fmt.Println("ent schema generation successfully")
}

func generateTableMaps(projectRoot, schemaDir, outputDir string) {
	fmt.Println("generateTableMaps: " + outputDir)
	tmplTableMaps := filepath.Join(projectRoot, "data", "generate", "list_module_tables.tmpl")
	tmpl, err := template.New("list_module_tables").Funcs(tmplFuncMap()).ParseFiles(tmplTableMaps)
	if err != nil {
		log.Fatalf("failed to parse template file %s: %v", tmplTableMaps, err)
	}

	graph, err := entc.LoadGraph(schemaDir, &gen.Config{})
	if err != nil {
		log.Fatalf("failed to load graph from schema: %v", err)
	}

	f, err := os.Create(filepath.Join(outputDir, "list_module_tables_gen.go"))
	if err != nil {
		log.Fatalf("failed to create hook output file: %v", err)
	}
	defer f.Close()

	err = tmpl.ExecuteTemplate(f, "list_module_tables", map[string]any{
		"Graph": graph,
	})
	if err != nil {
		log.Fatalf("failed to execute template: %v", err)
	}
	fmt.Println("init table-- generation successfully")
}

func generateTemplate(projectRoot, schemaDir, packageName, outputDir, tmplName string, data map[string]interface{}) {
	// fmt.Println("generate ent template: " + tmplName)
	tmplPath := filepath.Join(projectRoot, "data", "generate", fmt.Sprintf("%s.tmpl", tmplName))
	tmpl, err := template.New(tmplName).Funcs(tmplFuncMap()).ParseFiles(tmplPath)

	if err != nil {
		log.Fatalf("failed to parse template file %s: %v", tmplPath, err)
	}

	graph, err := entc.LoadGraph(schemaDir, &gen.Config{})
	if err != nil {
		log.Fatalf("failed to load graph from schema: %v", err)
	}

	if data == nil {
		data = map[string]interface{}{}
	}

	fileExt, ok := data["fileExt"]
	if !ok || fileExt == "" {
		fileExt = ".go"
	}

	f, err := os.Create(filepath.Join(outputDir, fmt.Sprintf("%s_gen%s", tmplName, fileExt)))
	if err != nil {
		log.Fatalf("failed to create .go output file: %v", err)
	}
	defer f.Close()

	err = tmpl.ExecuteTemplate(f, tmplName, map[string]any{
		"Graph":  graph,
		"Config": &gen.Config{Package: packageName},
	})
	if err != nil {
		log.Fatalf("failed to execute template: %v", err)
	}

	fmt.Println("ent template generation: " + tmplName + " to " + f.Name())
}

// func executeGenCode() {
// 	// Get the root directory of the current module
// 	moduleDirs, err := utils.GetModuleDirs()
// 	if err != nil {
// 		log.Fatalf("failed to get module directory: %v", err)
// 	}
//
// 	// Locate the root directory of the project
// 	var projectRoot string
// 	for _, dir := range moduleDirs {
// 		root, err := utils.GetProjectRoot(dir, "data")
// 		if err == nil {
// 			projectRoot = root
// 			break
// 		}
// 	}
// 	if projectRoot == "" {
// 		log.Fatal("failed to find valid project root")
// 	}
//
// 	if err = ensureDependencies(); err != nil {
// 		log.Fatalf("failed to ensure dependencies: %v", err)
// 	}
//
// 	schemaDir := filepath.Join(projectRoot, "data", ignoreDeleteFolder)
//
// 	// Load graph from schema
// 	_, err = entc.LoadGraph(schemaDir, &gen.Config{})
// 	if err != nil {
// 		log.Fatalf("failed to load graph from %s: %v", schemaDir, err)
// 	}
//
// 	outputDirs := []string{
// 		filepath.Join(projectRoot, "data", entSchemaGenFolder),
// 		filepath.Join(projectRoot, "data", entHookGenFolder),
// 		filepath.Join(projectRoot, "data", entInterceptorGenFolder),
// 		// filepath.Join(projectRoot, "data", entScriptGenFolder),
// 	}
//
//
// 	fmt.Println("\n---------------------------------------")
// 	generateEntSchema(schemaDir, "", outputDirs[0])
// 	fmt.Println("\n---------------------------------------")
// 	generateTableMaps(projectRoot, schemaDir, outputDirs[1])
//
// 	tmplGens := map[string]string{
// 		// ent
// 		"query_ts_vector":  outputDirs[0],
// 		"query_order_by":   outputDirs[0],
// 		"query_filter_by":  outputDirs[0],
// 		"query_find_first": outputDirs[0],
// 		"query_tags":       outputDirs[0],
//
// 		// // ent_hooks
// 		// "tenant_hook":      outputDirs[1],
// 		// "soft_delete_hook": outputDirs[1],
// 		// "audit_user_hook":  outputDirs[1],
// 		// "register_hooks":   outputDirs[1],
// 		//
// 		// // ent_interceptors
// 		// "tenant_interceptor":      outputDirs[2],
// 		// "soft_delete_interceptor": outputDirs[2],
// 		// "register_interceptors":   outputDirs[2],
// 	}
//
// 	for tmplName, outputDir := range tmplGens {
// 		fmt.Println("\n---------------------------------------")
// 		if tmplName != "tsvector_column_generate" {
// 			generateTemplate(projectRoot, schemaDir, outputDir, tmplName, nil)
// 		} else {
// 			generateTemplate(projectRoot, schemaDir, outputDir, tmplName, map[string]interface{}{
// 				"fileExt": ".sql",
// 			})
// 		}
// 	}
// }

func generateTsVectorScripts(projectRoot, schemaDir, outputDir string) {
	// fmt.Println("generateTsVectorScripts: " + outputDir)
	// tmplPath := filepath.Join(projectRoot, "data", "generate", "tsvector_column_by_module_func.tmpl")
	// tmpl, err := template.New("tsvector_column_by_module_func").Funcs(tmplFuncMap()).ParseFiles(tmplPath)
	// if err != nil {
	// 	log.Fatalf("failed to parse template file %s: %v", tmplPath, err)
	// }
	//
	// graph, err := entc.LoadGraph(schemaDir, &gen.Config{})
	// if err != nil {
	// 	log.Fatalf("failed to load graph from schema: %v", err)
	// }
	//
	// ent_hook.Fetch()
	// modules := ent_hook.ModuleTables
	// for km, module := range modules {
	// 	for fn, tables := range module {
	// 		fmt.Println(tables)
	// 		f, err := os.Create(filepath.Join(outputDir, fmt.Sprintf("%s_%s_tsvector_column_gen.sql", km, fn)))
	// 		if err != nil {
	// 			log.Fatalf("failed to create hook output file: %v", err)
	// 		}
	// 		defer f.Close()
	// 		err = tmpl.ExecuteTemplate(f, "tsvector_column_by_module_func", map[string]any{
	// 			"Graph":    graph,
	// 			"Module":   km,
	// 			"Function": fn,
	// 		})
	// 		if err != nil {
	// 			log.Fatalf("failed to execute template: %v", err)
	// 		}
	// 	}
	// }
	// fmt.Println("tsvector column scripts generation successfully")
}

func schemaGenerating(modulePath string) {
	// Get the root directory of the current module
	moduleDirs, err := utils.GetModuleDirs()
	if err != nil {
		log.Fatalf("failed to get module directory: %v", err)
	}

	// Locate the root directory of the project
	var projectRoot string
	for _, dir := range moduleDirs {
		root, err := utils.GetProjectRoot(dir, "data")
		if err == nil {
			projectRoot = root
			break
		}
	}
	if projectRoot == "" {
		log.Fatal("failed to find valid project root")
	}

	// TODO: remove if no need
	// if err = ensureDependencies(); err != nil {
	// 	log.Fatalf("failed to ensure dependencies: %v", err)
	// }

	schemaDir := filepath.Join(projectRoot, modulePath, entSchemaFolder)

	// fmt.Println("---------------------------------------")
	// fmt.Println("full path:", schemaDir)
	// Load graph from schema
	g, err := entc.LoadGraph(schemaDir, &gen.Config{})
	if err != nil {
		log.Fatalf("failed to load graph from %s: %v", schemaDir, err)
	}
	fmt.Println("ent graph loaded:", g.Schema)
	packageName := filepath.Join(g.Schema, "..", entSchemaGenFolder)
	fmt.Println("ent package name:", packageName)
	fmt.Println("---------------------------------------")

	outputDirs := []string{
		filepath.Join(projectRoot, modulePath, entSchemaGenFolder),
		filepath.Join(projectRoot, modulePath, entHookGenFolder),
		filepath.Join(projectRoot, modulePath, entInterceptorGenFolder),
		filepath.Join(projectRoot, modulePath, entScriptGenFolder),
	}

	for _, outputDir := range outputDirs {
		_ = os.MkdirAll(outputDir, 0755)
	}

	// fmt.Println("\n---------------------------------------")
	generateEntSchema(schemaDir, packageName, outputDirs[0])
	// fmt.Println("\n---------------------------------------")

	tmplGens := map[string]string{
		// ent
		"query_ts_vector": outputDirs[0],
		"query_order_by":  outputDirs[0],
		// "query_filter_by":  outputDirs[0],
		"query_find_first": outputDirs[0],
		"query_tags":       outputDirs[0],
		"runtime_init":     outputDirs[0],

		// ent_hooks
		// "tenant_hook":      outputDirs[1],
		"soft_delete_hook": outputDirs[1],
		"audit_user_hook":  outputDirs[1],
		"register_hooks":   outputDirs[1],

		// ent_interceptors
		"tenant_interceptor":      outputDirs[2],
		"soft_delete_interceptor": outputDirs[2],
		"register_interceptors":   outputDirs[2],

		// sql scripts
		"tsvector_column_generate": outputDirs[3],
	}

	for tmplName, outputDir := range tmplGens {
		// fmt.Println("\n---------------------------------------")
		if tmplName != "tsvector_column_generate" {
			generateTemplate(projectRoot, schemaDir, packageName, outputDir, tmplName, nil)
		} else {
			generateTemplate(projectRoot, schemaDir, packageName, outputDir, tmplName, map[string]interface{}{
				"fileExt": ".sql",
			})
		}
	}

}

func executeGenSqlScript() {
	projectRoot, schemaDir := fetchInfo()

	// Load graph from schema
	_, err := entc.LoadGraph(schemaDir, &gen.Config{})
	if err != nil {
		log.Fatalf("failed to load graph from %s: %v", schemaDir, err)
	}

	outputDirs := []string{
		filepath.Join(projectRoot, "data", entScriptGenFolder),
	}

	fmt.Println("\n---------------------------------------")
	generateTsVectorScripts(projectRoot, schemaDir, outputDirs[0])
}

// args format: domain -> module -> func
//
// e.g. smp iam  or smp iam sql
func main() {
	if len(os.Args) < 1 {
		panic(fmt.Errorf("invalid args"))
	}

	modulePaths := make([]string, 0)
	modulePaths = append(modulePaths, filepath.Join("..", "apps", os.Args[1], "internal", "data"))

	fmt.Println("module paths:", modulePaths)

	// modulePath := filepath.Join("apps", os.Args[1], "internal", os.Args[2], "data")
	// fmt.Println("generating ent schemat at: ", modulePath)

	if err := ensureDependencies(); err != nil {
		log.Fatalf("failed to ensure dependencies: %v", err)
	}

	for _, modulePath := range modulePaths {
		fmt.Println("\n####################################################")
		fmt.Println("generating ent schemat at: ", modulePath)
		schemaGenerating(modulePath)
	}

}

// func main() {
// 	// Check if the first argument is "sql"
// 	fmt.Println(os.Args)
// 	if len(os.Args) > 1 && os.Args[1] == "sql" {
// 		executeGenSqlScript()
// 	} else {
// 		executeGenCode()
// 	}
// }
