// Code generated by novaerp.com, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"vn.vato.zora.be.api/apps/wallet/internal/data/ent/balance"
	"vn.vato.zora.be.api/apps/wallet/internal/data/ent/internal"
	"vn.vato.zora.be.api/apps/wallet/internal/data/ent/predicate"
)

// BalanceDelete is the builder for deleting a Balance entity.
type BalanceDelete struct {
	config
	hooks    []Hook
	mutation *BalanceMutation
}

// Where appends a list predicates to the BalanceDelete builder.
func (_d *BalanceDelete) Where(ps ...predicate.Balance) *BalanceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BalanceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BalanceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BalanceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(balance.Table, sqlgraph.NewFieldSpec(balance.FieldID, field.TypeInt))
	_spec.Node.Schema = _d.schemaConfig.Balance
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BalanceDeleteOne is the builder for deleting a single Balance entity.
type BalanceDeleteOne struct {
	_d *BalanceDelete
}

// Where appends a list predicates to the BalanceDelete builder.
func (_d *BalanceDeleteOne) Where(ps ...predicate.Balance) *BalanceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BalanceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{balance.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BalanceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
