// Code generated by novaerp.com, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"vn.vato.zora.be.api/apps/wallet/internal/data/ent/balance"
)

// BalanceCreate is the builder for creating a Balance entity.
type BalanceCreate struct {
	config
	mutation *BalanceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *BalanceCreate) SetUserID(v int64) *BalanceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetBalance sets the "balance" field.
func (_c *BalanceCreate) SetBalance(v float64) *BalanceCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_c *BalanceCreate) SetNillableBalance(v *float64) *BalanceCreate {
	if v != nil {
		_c.SetBalance(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BalanceCreate) SetCreatedAt(v time.Time) *BalanceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BalanceCreate) SetUpdatedAt(v time.Time) *BalanceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// Mutation returns the BalanceMutation object of the builder.
func (_c *BalanceCreate) Mutation() *BalanceMutation {
	return _c.mutation
}

// Save creates the Balance in the database.
func (_c *BalanceCreate) Save(ctx context.Context) (*Balance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BalanceCreate) SaveX(ctx context.Context) *Balance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BalanceCreate) defaults() {
	if _, ok := _c.mutation.Balance(); !ok {
		v := balance.DefaultBalance
		_c.mutation.SetBalance(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BalanceCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Balance.user_id"`)}
	}
	if _, ok := _c.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "Balance.balance"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Balance.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Balance.updated_at"`)}
	}
	return nil
}

func (_c *BalanceCreate) sqlSave(ctx context.Context) (*Balance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BalanceCreate) createSpec() (*Balance, *sqlgraph.CreateSpec) {
	var (
		_node = &Balance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(balance.Table, sqlgraph.NewFieldSpec(balance.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.Balance
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(balance.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(balance.FieldBalance, field.TypeFloat64, value)
		_node.Balance = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(balance.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(balance.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Balance.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceCreate) OnConflict(opts ...sql.ConflictOption) *BalanceUpsertOne {
	_c.conflict = opts
	return &BalanceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Balance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceCreate) OnConflictColumns(columns ...string) *BalanceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceUpsertOne{
		create: _c,
	}
}

type (
	// BalanceUpsertOne is the builder for "upsert"-ing
	//  one Balance node.
	BalanceUpsertOne struct {
		create *BalanceCreate
	}

	// BalanceUpsert is the "OnConflict" setter.
	BalanceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *BalanceUpsert) SetUserID(v int64) *BalanceUpsert {
	u.Set(balance.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BalanceUpsert) UpdateUserID() *BalanceUpsert {
	u.SetExcluded(balance.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *BalanceUpsert) AddUserID(v int64) *BalanceUpsert {
	u.Add(balance.FieldUserID, v)
	return u
}

// SetBalance sets the "balance" field.
func (u *BalanceUpsert) SetBalance(v float64) *BalanceUpsert {
	u.Set(balance.FieldBalance, v)
	return u
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *BalanceUpsert) UpdateBalance() *BalanceUpsert {
	u.SetExcluded(balance.FieldBalance)
	return u
}

// AddBalance adds v to the "balance" field.
func (u *BalanceUpsert) AddBalance(v float64) *BalanceUpsert {
	u.Add(balance.FieldBalance, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BalanceUpsert) SetUpdatedAt(v time.Time) *BalanceUpsert {
	u.Set(balance.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalanceUpsert) UpdateUpdatedAt() *BalanceUpsert {
	u.SetExcluded(balance.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Balance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalanceUpsertOne) UpdateNewValues() *BalanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(balance.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Balance.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BalanceUpsertOne) Ignore() *BalanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceUpsertOne) DoNothing() *BalanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceCreate.OnConflict
// documentation for more info.
func (u *BalanceUpsertOne) Update(set func(*BalanceUpsert)) *BalanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *BalanceUpsertOne) SetUserID(v int64) *BalanceUpsertOne {
	return u.Update(func(s *BalanceUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *BalanceUpsertOne) AddUserID(v int64) *BalanceUpsertOne {
	return u.Update(func(s *BalanceUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BalanceUpsertOne) UpdateUserID() *BalanceUpsertOne {
	return u.Update(func(s *BalanceUpsert) {
		s.UpdateUserID()
	})
}

// SetBalance sets the "balance" field.
func (u *BalanceUpsertOne) SetBalance(v float64) *BalanceUpsertOne {
	return u.Update(func(s *BalanceUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *BalanceUpsertOne) AddBalance(v float64) *BalanceUpsertOne {
	return u.Update(func(s *BalanceUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *BalanceUpsertOne) UpdateBalance() *BalanceUpsertOne {
	return u.Update(func(s *BalanceUpsert) {
		s.UpdateBalance()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BalanceUpsertOne) SetUpdatedAt(v time.Time) *BalanceUpsertOne {
	return u.Update(func(s *BalanceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalanceUpsertOne) UpdateUpdatedAt() *BalanceUpsertOne {
	return u.Update(func(s *BalanceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BalanceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BalanceUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BalanceUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BalanceCreateBulk is the builder for creating many Balance entities in bulk.
type BalanceCreateBulk struct {
	config
	err      error
	builders []*BalanceCreate
	conflict []sql.ConflictOption
}

// Save creates the Balance entities in the database.
func (_c *BalanceCreateBulk) Save(ctx context.Context) ([]*Balance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Balance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BalanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BalanceCreateBulk) SaveX(ctx context.Context) []*Balance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Balance.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceCreateBulk) OnConflict(opts ...sql.ConflictOption) *BalanceUpsertBulk {
	_c.conflict = opts
	return &BalanceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Balance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceCreateBulk) OnConflictColumns(columns ...string) *BalanceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceUpsertBulk{
		create: _c,
	}
}

// BalanceUpsertBulk is the builder for "upsert"-ing
// a bulk of Balance nodes.
type BalanceUpsertBulk struct {
	create *BalanceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Balance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalanceUpsertBulk) UpdateNewValues() *BalanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(balance.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Balance.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BalanceUpsertBulk) Ignore() *BalanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceUpsertBulk) DoNothing() *BalanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceCreateBulk.OnConflict
// documentation for more info.
func (u *BalanceUpsertBulk) Update(set func(*BalanceUpsert)) *BalanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *BalanceUpsertBulk) SetUserID(v int64) *BalanceUpsertBulk {
	return u.Update(func(s *BalanceUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *BalanceUpsertBulk) AddUserID(v int64) *BalanceUpsertBulk {
	return u.Update(func(s *BalanceUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BalanceUpsertBulk) UpdateUserID() *BalanceUpsertBulk {
	return u.Update(func(s *BalanceUpsert) {
		s.UpdateUserID()
	})
}

// SetBalance sets the "balance" field.
func (u *BalanceUpsertBulk) SetBalance(v float64) *BalanceUpsertBulk {
	return u.Update(func(s *BalanceUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *BalanceUpsertBulk) AddBalance(v float64) *BalanceUpsertBulk {
	return u.Update(func(s *BalanceUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *BalanceUpsertBulk) UpdateBalance() *BalanceUpsertBulk {
	return u.Update(func(s *BalanceUpsert) {
		s.UpdateBalance()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BalanceUpsertBulk) SetUpdatedAt(v time.Time) *BalanceUpsertBulk {
	return u.Update(func(s *BalanceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BalanceUpsertBulk) UpdateUpdatedAt() *BalanceUpsertBulk {
	return u.Update(func(s *BalanceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BalanceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BalanceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
