// Code generated by novaerp.com, DO NOT EDIT.

package ent

import (
	"vn.vato.zora.be.api/apps/wallet/internal/data/ent/balance"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 1)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   balance.Table,
			Columns: balance.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: balance.FieldID,
			},
		},
		Type: "Balance",
		Fields: map[string]*sqlgraph.FieldSpec{
			balance.FieldUserID:    {Type: field.TypeInt64, Column: balance.FieldUserID},
			balance.FieldBalance:   {Type: field.TypeFloat64, Column: balance.FieldBalance},
			balance.FieldCreatedAt: {Type: field.TypeTime, Column: balance.FieldCreatedAt},
			balance.FieldUpdatedAt: {Type: field.TypeTime, Column: balance.FieldUpdatedAt},
		},
	}
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (_q *BalanceQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the BalanceQuery builder.
func (_q *BalanceQuery) Filter() *BalanceFilter {
	return &BalanceFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *BalanceMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the BalanceMutation builder.
func (m *BalanceMutation) Filter() *BalanceFilter {
	return &BalanceFilter{config: m.config, predicateAdder: m}
}

// BalanceFilter provides a generic filtering capability at runtime for BalanceQuery.
type BalanceFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *BalanceFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int predicate on the id field.
func (f *BalanceFilter) WhereID(p entql.IntP) {
	f.Where(p.Field(balance.FieldID))
}

// WhereUserID applies the entql int64 predicate on the user_id field.
func (f *BalanceFilter) WhereUserID(p entql.Int64P) {
	f.Where(p.Field(balance.FieldUserID))
}

// WhereBalance applies the entql float64 predicate on the balance field.
func (f *BalanceFilter) WhereBalance(p entql.Float64P) {
	f.Where(p.Field(balance.FieldBalance))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *BalanceFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(balance.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *BalanceFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(balance.FieldUpdatedAt))
}
