// Code generated by novaerp.com, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Ticket is the predicate function for ticket builders.
type Ticket func(*sql.Selector)

// TicketSeat is the predicate function for ticketseat builders.
type TicketSeat func(*sql.Selector)
