// Code generated by novaerp.com, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in vn.vato.zora.be.api/apps/zalo/internal/data/ent/runtime.go

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
